CHANGELOG.md, aim/profiler/interfaces.py, aim/profiler/profiler.py, aim/profiler/stat.py, aim/sdk/profiler.py, examples/keras_cnn_profiler.py, examples/tf_basic_profiler.py, examples/tf_layers_cnn.py
Update profiler sdk interface and naming
=> Update profiler module importing to not depend on heavy frameworks

README.md
* add steps of how to setup environment
* add project structure
=> WIP: Add development documentation to README

aim/cli/push/commands.py
This is a temporary solution.
Need to receive authentication status from the server and check permissions before sending files.
=> Cancel push and print alert msg if authentication is failed

README.md, aim/cli/cli.py, aim/cli/push/commands.py, aim/engine/aim_container.py, aim/engine/aim_profile.py, aim/engine/aim_protocol.py, aim/logger.py, aim/profiler/interfaces.py, aim/sdk/artifacts/artifact_writer.py, aim/sdk/artifacts/text.py, aim/version_control/git.py, setup.cfg, tests/engine/test_aim_repo.py
- Create PEP8 config files, excluding checks in lib.
- Enable recursive checking with `pycodestyle` and formatting with `autopep8`.
- Update README to include guide for formatting code.
=> Create PEP8 Config File and Enable Recursive Checking & Formatting

aim/artifacts/model.py, aim/artifacts/utils.py, aim/engine/utils.py, examples/tf_model_load.py, examples/tf_model_save.py
The ability to track checkpoints and save models in TensorFlow 1.x has been added using the Saver class following the existing code for PyTorch and Keras. In addition, examples have been added to test saving and loading models in TensorFlow.
Loading models produces the error `tensorflow.python.framework.errors_impl.DataLossError: file is too short to be an sstable` when calling `saver.restore()`. It's possible a file is corrupted/truncated.
EDIT: The issue was resolved by copying the .aim file to a temporary directory and unzipping it there.
=> Add tensorflow 1.x integration with checkpoints and saving/loading models.

README.md
=> Add Tensorboard integration docs 

CHANGELOG.md, README.md, aim/cli/de/commands.py, aim/engine/configs.py, aim/engine/container/container.py
=> Add ability to opt out telemetry

aim/hugging_face.py, aim/sdk/adapters/hugging_face.py, examples/hugging_face_track.py
Integration is not finished.
TODO
- modify set_params to allow integers in hparams keys.
- fix the bug of sessions being closed before validation/prediction.
- test hugging-face's hyper_param_search to work with AimCallback.
Closes #331
=> Add HuggingFace integration

aim/sdk/adapters/xgboost.py, aim/xgboost.py, examples/xgboost_track.py
=> Add xgboost integration

CHANGELOG.md, aim/sdk/adapters/keras.py, aim/sdk/adapters/keras_mixins.py, aim/sdk/adapters/tensorflow.py, examples/keras_track.py, examples/tensorflow_keras_track.py
Allowed Keras users to use repo/experiment arguments instead of creating a session and passing it to the callback.
Closes #461.
=> Update keras implementation

aim/cli/up/utils.py
added '--timeout' and '--graceful-timeout' options for gunicorn server to wait for worker response to up to 300s
=> Set gunicorn timeouts

aim/sdk/session/session.py
Move the session status setting to non-active in close method to a later stage and change the session's queue jobs from threads to python functions
=> Early session closing

aim/web/ui_v2/package.json, aim/web/ui_v2/src/App.tsx, aim/web/ui_v2/src/components/Theme/Theme.tsx, aim/web/ui_v2/src/pages/Metrics/Metrics.tsx, aim/web/ui_v2/src/pages/Metrics/MetricsContainer.tsx, aim/web/ui_v2/src/pages/Metrics/components/AppBar/AppBar.tsx, aim/web/ui_v2/src/pages/Metrics/components/Grouping/Grouping.tsx, aim/web/ui_v2/src/pages/Metrics/components/SelectForm/SelectForm.tsx, aim/web/ui_v2/src/pages/Metrics/metricsStyle.ts, aim/web/ui_v2/src/types/pages/metrics/Metrics.d.ts
- Enabled resize handler on `Box` divider.
- Moved `CssBaseline` to `Theme` component.
- Improved styles in `Metrics` component.
=> Add metrics explore panel resize functionality

aim/artifacts/utils.py, aim/sdk/session/session.py, aim/web/api/utils.py
Fixed the error regarding potential collections.abc depreciation warnings using a try catch statement. Multiple files altered to protect against Depreciation.
=> Issues fix/collections abc import 367

aim/web/ui_v2/src/hooks/resize/usePanelResize.ts, aim/web/ui_v2/src/pages/Metrics/Metrics.tsx, aim/web/ui_v2/src/pages/Metrics/MetricsContainer.tsx, aim/web/ui_v2/src/types/pages/metrics/Metrics.d.ts
- Added usePanelResize reusable custom hook
=> Add panel resize reusable custom hook

.github/workflows/python-package.yml
@gorarakelyan please take a look. This PR contains only the workflow file. It has to be added to master in order to enable Actions
=> github actions workflow for master merge

aim/storage/run_metadata/entities.py, aim/storage/run_metadata/sql_engine/entities.py, aim/storage/run_metadata/sql_engine/utils.py
* Make `Run/Tag/Experiment` interfaces returning iterable to return collection
* Minor fixes
* Added `__repr__` to mapped classes
=> support for 'tag_name' in run.tags QL construct

aim/storage/container.py, aim/storage/encoding.py, aim/storage/query.py, aim/storage/treeutils.py, aim/storage/treeview.py
This branch introduces non-strict mode intended for union of key-value based storage.
=> Non strict mode

aim/web/api/commits/utils.py
Bring back old utils to be used for converting old storage files to new ones
=> Bring back old methods in 'aim/web/api/commit/utils.py'

aim/storage/run.py, aim/web/api/commits/utils.py, requirements.txt
Fix broken functionalities after recent changes on 'pre_release_v3' branch and cast epochs and iters to 'float64' before encoding
=> Fix broken functionalities for 'pre_release_v3'

aim/web/ui_v2/src/components/ChartPanel/ChartPanel.tsx, aim/web/ui_v2/src/components/GroupingPopover/GroupingPopover.tsx, aim/web/ui_v2/src/pages/Metrics/components/Grouping/Grouping.tsx, aim/web/ui_v2/src/pages/Metrics/components/GroupingItem/groupingItemStyle.scss, aim/web/ui_v2/src/services/models/metrics/metricsAppModel.ts, aim/web/ui_v2/src/types/components/GroupingPopover/GroupingPopover.d.ts, aim/web/ui_v2/src/types/pages/metrics/Metrics.d.ts, aim/web/ui_v2/src/types/pages/metrics/components/GroupingItem/GroupingItem.d.ts, aim/web/ui_v2/src/types/services/models/metrics/metricsAppModel.d.ts, aim/web/ui_v2/src/utils/d3/drawHoverAttributes.ts
- Added additional select options for grouping (group by metric name, experiment name, run hash, context?) 
- Changed grouping selectOptions items type
=> Add group option additional fields

aim/storage/query.py, aim/storage/sdk/repo.py, aim/storage/sdk/run.py, aim/storage/treeview.py, aim/storage/union.py, aim/web/api/commits/utils.py, aim/web/api/commits/views.py, aim/web/api/projects/views.py
Add run creation timestamp, last tracked values for each trace in run meta tree and restructure run storage to save user defined attributes under 'attrs' key
=> Run storage modifications

aim/web/ui_v2/src/services/models/metrics/metricsAppModel.ts, aim/web/ui_v2/src/types/services/models/metrics/metricsAppModel.d.ts
- Refactored metric app model state refs part
=> Refactor metric app model state

aim/web/ui_v2/src/services/models/metrics/metricsAppModel.ts
- Fixed setComponetsRef function param type
=> Fix setComponetsRef function param type

aim/web/ui_v2/src/App.tsx, aim/web/ui_v2/src/components/NotificationContainer/NotificationContainer.tsx, aim/web/ui_v2/src/config/notification-messages/notificationMessages.ts, aim/web/ui_v2/src/pages/Bookmarks/Bookmarks.tsx, aim/web/ui_v2/src/pages/Metrics/Metrics.tsx, aim/web/ui_v2/src/pages/Metrics/MetricsContainer.tsx, aim/web/ui_v2/src/routes/routes.tsx, aim/web/ui_v2/src/services/api/api.ts, aim/web/ui_v2/src/services/api/apps/appsService.ts, aim/web/ui_v2/src/services/api/dashboard/dashboardService.ts, aim/web/ui_v2/src/services/api/metrics/metricsService.ts, aim/web/ui_v2/src/services/api/projects/projectsService.ts, aim/web/ui_v2/src/services/models/bookmarks/bookmarksAppModel.ts, aim/web/ui_v2/src/services/models/metrics/metricsAppModel.ts, aim/web/ui_v2/src/types/components/NotificationContainer/NotificationContainer.d.ts, aim/web/ui_v2/src/types/pages/bookmarks/Bookmarks.d.ts, aim/web/ui_v2/src/types/pages/bookmarks/components/BookmarkCard.d.ts, aim/web/ui_v2/src/types/pages/metrics/Metrics.d.ts, aim/web/ui_v2/src/types/services/models/metrics/metricsAppModel.d.ts, aim/web/ui_v2/src/types/services/services.d.ts
- Added NotificationContainer component
- Added notification add and delete logic
- Added BookmarksNotificationEnum
- Added logic of fetching app config data from back and setting it to metricAppModel
=> Add ability to display notifications on actions

aim/web/api/dashboard_apps/pydantic_models.py, aim/web/api/dashboard_apps/views.py, aim/web/api/dashboards/pydantic_models.py, aim/web/api/dashboards/views.py, aim/web/api/experiments/pydantic_models.py, aim/web/api/experiments/views.py, aim/web/api/projects/pydantic_models.py, aim/web/api/projects/views.py, aim/web/api/runs/pydantic_models.py, aim/web/api/runs/utils.py, aim/web/api/runs/views.py, aim/web/api/tags/pydantic_models.py, aim/web/api/tags/views.py, tests/api/test_run_api.py, tests/api/test_structured_data_api.py
Add pydantic models for request data validations and response schema creations
=> Custom open api

aim/web/ui_v2/src/components/AggregationPopover/AggregationPopover.tsx, aim/web/ui_v2/src/components/ChartPanel/PopoverContent/PopoverContent.tsx, aim/web/ui_v2/src/components/HighlightModesPopover/HighlightEnum.ts, aim/web/ui_v2/src/components/HighlightModesPopover/HighlightModesPopover.tsx, aim/web/ui_v2/src/pages/Metrics/Metrics.tsx, aim/web/ui_v2/src/pages/Metrics/MetricsContainer.tsx, aim/web/ui_v2/src/pages/Metrics/components/Controls/Controls.tsx, aim/web/ui_v2/src/services/models/metrics/metricsAppModel.ts, aim/web/ui_v2/src/types/components/AggregationPopover/AggregationPopover.d.ts, aim/web/ui_v2/src/types/components/HighPlot/HighPlot.d.ts, aim/web/ui_v2/src/types/components/LineChart/LineChart.d.ts, aim/web/ui_v2/src/types/pages/metrics/Metrics.d.ts, aim/web/ui_v2/src/types/pages/metrics/components/AppBar/AppBar.d.ts, aim/web/ui_v2/src/types/pages/metrics/components/BookmarkForm/BookmarkForm.d.ts, aim/web/ui_v2/src/types/pages/metrics/components/Grouping/Grouping.d.ts, aim/web/ui_v2/src/types/pages/metrics/components/controls/Controls.d.ts, aim/web/ui_v2/src/types/services/models/metrics/metricsAppModel.d.ts, aim/web/ui_v2/src/types/utils/d3/drawHoverAttributes.d.ts, aim/web/ui_v2/src/types/utils/d3/drawLines.d.ts, aim/web/ui_v2/src/types/utils/d3/drawParallelHoverAttributes.d.ts, aim/web/ui_v2/src/utils/aggregateGroupData.ts, aim/web/ui_v2/src/utils/d3/drawHoverAttributes.ts, aim/web/ui_v2/src/utils/d3/processData.ts
Add: 
- controls sidebar aggregation methods functionality
Fix:
- some types
- enhance HighLightModesPopover component
=> Add ability to change LineChart aggregation methods

aim/web/ui_v2/src/pages/Metrics/Metrics.tsx, aim/web/ui_v2/src/pages/Metrics/MetricsContainer.tsx, aim/web/ui_v2/src/pages/Metrics/components/AppBar/AppBar.tsx, aim/web/ui_v2/src/services/models/metrics/metricsAppModel.ts, aim/web/ui_v2/src/types/pages/metrics/Metrics.d.ts, aim/web/ui_v2/src/types/pages/metrics/components/AppBar/AppBar.d.ts
- Added reset metric model config state functionality
=> Add reset metric model config state functionality

aim/cli/up/utils.py, aim/web/api/config.py, aim/web/api/dashboard_apps/pydantic_models.py, aim/web/api/dashboards/pydantic_models.py, aim/web/api/dashboards/views.py, aim/web/api/db.py, aim/web/migrations/env.py, tests/api/examples.py, tests/api/test_dashboards_api.py, tests/base.py, tests/conftest.py, tests/utils.py
- add unit-tests for dashboards and dashboard apps endpoints
- make necessary changes for sqlite test db creation
- minor fixes regarding dashboards and apps pydantic models
=> Unittests for 'dashboards' and 'apps' endpoints 

aim/storage/sdk/repo.py, aim/web/api/projects/pydantic_models.py
Change 'metrics' in 'api/projects/params' endpoint from plain list to… dict[metric_name, ctx_list]
=> Change 'metrics' reporting for autocomplete

aim/web/ui_v2/src/pages/Metrics/components/SelectForm/SelectForm.tsx, aim/web/ui_v2/src/services/api/projects/projectsService.ts, aim/web/ui_v2/src/services/models/projects/projectsModel.ts, aim/web/ui_v2/src/types/services/models/projects/projectsModel.d.ts
- Add request handler for `/project/params` endpoint
- Set project metrics and params on `projectsModel`
=> Add handler for fetching and setting project metrics and params

setup.py
Please approve whoever is available
=> Added treeutils_ Cython extension

aim/web/ui_v2/src/components/HighPlot/HighPlot.tsx, aim/web/ui_v2/src/components/TagForm/TagForm.tsx, aim/web/ui_v2/src/pages/Metrics/Metrics.tsx, aim/web/ui_v2/src/pages/Metrics/MetricsContainer.tsx, aim/web/ui_v2/src/pages/Metrics/components/SelectForm/SelectForm.tsx, aim/web/ui_v2/src/services/models/metrics/metricsAppModel.ts, aim/web/ui_v2/src/types/pages/metrics/Metrics.d.ts, aim/web/ui_v2/src/types/pages/metrics/components/SelectForm/SelectForm.d.ts, aim/web/ui_v2/src/types/services/models/metrics/metricsAppModel.d.ts
- Add event handlers for `SelectFrom` elements
- Construct search query from metrics model config's select field state
=> Implement query constructions from SelectForm actions

aim/web/ui_v2/src/pages/Metrics/components/SelectForm/SelectForm.tsx, aim/web/ui_v2/src/pages/Metrics/components/TableColumns/TableColumns.tsx, aim/web/ui_v2/src/services/models/metrics/metricsAppModel.ts, aim/web/ui_v2/src/types/services/models/metrics/metricsAppModel.d.ts
- Do not make search request with an empty query
- Fix metric label selection toggling
- Fix issue with displaying objects in table
=> Improve UX for select section

aim/storage/migrations/env.py, tests/api/test_run_api.py, tests/api/test_structured_data_api.py, tests/base.py, tests/conftest.py, tests/test_upgrade_cmd.py, tests/utils.py
moved from list comparison to set comparison (order does not matter) in unit-tests assersions
=> fixed unit-tests internal dependency issues

aim/web/ui_v2/src/pages/Bookmarks/Bookmarks.tsx, aim/web/ui_v2/src/services/models/metrics/metricsAppModel.ts, aim/web/ui_v2/src/styles/_global.scss, aim/web/ui_v2/src/styles/abstracts/_index.scss, aim/web/ui_v2/src/styles/abstracts/_mixins.scss, aim/web/ui_v2/src/styles/abstracts/_variables.scss
- Added variables and mixin for content container
- Fixed metrics query params
=> Add content container for bookmarks

aim/web/ui_v2/src/pages/Metrics/components/MetricsBar/MetricsBar.scss, aim/web/ui_v2/src/pages/Metrics/components/MetricsBar/MetricsBar.tsx
- Added update bookmark button
=> Add update bookmark button

aim/web/ui_v2/src/pages/Metrics/MetricsContainer.tsx, aim/web/ui_v2/src/pages/Metrics/components/MetricsBar/MetricsBar.tsx, aim/web/ui_v2/src/services/api/api.ts, aim/web/ui_v2/src/services/models/metrics/metricsAppModel.ts, aim/web/ui_v2/src/utils/storage.ts
- Added ability to save page url in local storage
- Added local storage reusable helper
- Fixed setting bookmark app state on app model config state
=> Add ability to save page url in local storage

aim/web/ui_v2/src/components/BusyLoaderWrapper/BusyLoaderWrapper.tsx, aim/web/ui_v2/src/components/Table/Table.tsx, aim/web/ui_v2/src/pages/Bookmarks/Bookmarks.tsx, aim/web/ui_v2/src/pages/Bookmarks/BookmarksContainer.tsx, aim/web/ui_v2/src/pages/Bookmarks/components/BookmarkCard/BookmarkCard.scss, aim/web/ui_v2/src/services/models/bookmarks/bookmarksAppModel.ts, aim/web/ui_v2/src/services/models/metrics/metricsAppModel.ts, aim/web/ui_v2/src/types/pages/bookmarks/Bookmarks.d.ts, aim/web/ui_v2/src/types/services/models/bookmarks/bookmarksAppModel.d.ts
- Implement content loader and no data placeholder for bookmarks page
- Fixed minor Table style issue
=> Implement content loader and no data placeholder for bookmarks page

aim/web/ui_v2/src/components/ConfirmModal/ConfirmModal.scss, aim/web/ui_v2/src/components/ConfirmModal/ConfirmModal.tsx, aim/web/ui_v2/src/pages/Bookmarks/components/BookmarkCard/BookmarkCard.tsx, aim/web/ui_v2/src/pages/Tags/TagDelete.tsx, aim/web/ui_v2/src/pages/Tags/TagSoftDelete.tsx, aim/web/ui_v2/src/pages/Tags/TagsList.tsx, aim/web/ui_v2/src/styles/_global.scss, aim/web/ui_v2/src/styles/_utils.scss, aim/web/ui_v2/src/styles/abstracts/_variables.scss, aim/web/ui_v2/src/types/components/ConfirmModal/ConfirmModal.d.ts, aim/web/ui_v2/src/types/pages/tags/Tags.d.ts
- Created Reusable ConfirmModal Component
- Used ConfirmModal component on bookmarks page for delete bookmark action
- Used ConfirmModal component on tags page for delete/hide/show tag action
=> Confirmation popover styling

aim/sdk/repo.py, aim/sdk/trace.py, aim/storage/structured/db.py, aim/storage/structured/sql_engine/entities.py, aim/web/api/runs/utils.py, aim/web/api/runs/views.py, tests/api/test_run_api.py
Add pagination with limit and offset for runs search endpoint ('api/runs/search/run/')
=> Run search pagination

aim/web/ui_v2/src/components/BusyLoaderWrapper/BusyLoaderWrapper.tsx, aim/web/ui_v2/src/components/ChartLoader/ChartLoader.scss, aim/web/ui_v2/src/components/ChartLoader/ChartLoader.tsx, aim/web/ui_v2/src/components/TableLoader/TableLoader.scss, aim/web/ui_v2/src/components/TableLoader/TableLoader.tsx, aim/web/ui_v2/src/pages/Metrics/Metrics.scss, aim/web/ui_v2/src/pages/Metrics/Metrics.tsx, aim/web/ui_v2/src/pages/Metrics/MetricsContainer.tsx, aim/web/ui_v2/src/pages/Params/Params.tsx, aim/web/ui_v2/src/pages/Params/ParamsContainer.tsx, aim/web/ui_v2/src/pages/Params/components/SelectForm/SelectForm.tsx, aim/web/ui_v2/src/services/models/metrics/metricsAppModel.ts, aim/web/ui_v2/src/services/models/params/paramsAppModel.ts, aim/web/ui_v2/src/types/components/BusyLoaderWrapper/BusyLoaderWrapper.d.ts, aim/web/ui_v2/src/types/pages/metrics/Metrics.d.ts, aim/web/ui_v2/src/types/pages/params/Params.d.ts
- Add content loader in metrics page
- Add content loader in params page
=> Add content loader in metrics page

aim/web/ui_v2/src/components/Button/Button.tsx, aim/web/ui_v2/src/components/ConfirmModal/ConfirmModal.tsx, aim/web/ui_v2/src/components/Theme/Theme.tsx, aim/web/ui_v2/src/pages/Bookmarks/components/BookmarkCard/BookmarkCard.scss, aim/web/ui_v2/src/pages/Bookmarks/components/BookmarkCard/BookmarkCard.tsx
-  Remove redundant right padding of chips
-  Tune name and description styling
-  "View bookmark" ghost button
=> fix bookmark card styles

aim/web/ui_v2/package.json, aim/web/ui_v2/src/components/CopyToClipBoard/CopyToClipBoard.tsx, aim/web/ui_v2/src/pages/Home/components/Activity/Activity.tsx, aim/web/ui_v2/src/pages/Home/components/ExploreAimCard/ExploreAimCard.scss
-  Fix description text weight of "explore aim" cards
-  Set 0 as default value of experiment count
-  Set 0 as  default value of runs count
-  "Copied !" to "Copied!"
-  Add Firefox support for copy to clipboard functionality
=> Fix home page styles

aim/web/ui_v2/src/components/ChartPanel/ChartPanel.tsx, aim/web/ui_v2/src/components/LineChart/LineChart.tsx, aim/web/ui_v2/src/components/TooltipContentPopover/TooltipContentPopover.tsx, aim/web/ui_v2/src/pages/Metrics/Metrics.tsx, aim/web/ui_v2/src/services/models/metrics/metricsAppModel.ts, aim/web/ui_v2/src/utils/d3/drawAxes.ts
Add:
- LineChart yAxis ticks overlap fix
- Code parts which removed from resolving merge conflict
=> Fix LineChart axes formatting issues

aim/storage/query.py, aim/web/api/runs/pydantic_models.py, aim/web/api/tags/pydantic_models.py
- add parenthesis to handle '\n's
- remove redundant spaces
=> Fix query stripping

aim/sdk/__init__.py, aim/web/ui_v2/src/pages/Home/components/SetupGuide/SetupGuide.tsx, setup.cfg
added aliases to Run and Repo in sdk
changed experiment track code sample in UI
=> aim.sdk main class aliases

aim/web/ui_v2/src/components/AlignmentPopover/AlignmentPopover.tsx, aim/web/ui_v2/src/components/Table/Table.tsx, aim/web/ui_v2/src/hooks/resize/usePanelResize.ts, aim/web/ui_v2/src/pages/Metrics/Metrics.tsx, aim/web/ui_v2/src/pages/Metrics/MetricsContainer.tsx, aim/web/ui_v2/src/pages/Metrics/components/Controls/Controls.tsx, aim/web/ui_v2/src/services/models/projects/projectsModel.ts, aim/web/ui_v2/src/types/components/AlignmentPopover/AlignmentPopover.d.ts, aim/web/ui_v2/src/types/pages/metrics/Metrics.d.ts, aim/web/ui_v2/src/types/pages/metrics/components/controls/Controls.d.ts
Add: 
- Use projects Model in metricsContainer
=> Fix issue with showing metric name in alignment popover

aim/web/ui_v2/src/components/CustomTable/TableCell.tsx, aim/web/ui_v2/src/components/CustomTable/TableColumn.tsx, aim/web/ui_v2/src/components/Table/Table.tsx, aim/web/ui_v2/src/services/models/metrics/metricsAppModel.ts
- Implemented set hovered row functionality
- Implemented set active row functionality
- Implemented scroll to active row functionality
- Attached handlers to row event listeners
=> Add custom table row actions

aim/storage/container.py, aim/web/api/views.py
- remove missing_ok argument for path unlink
- fix static file paths
=> Minor fixes on storage and backend

aim/web/.gitignore, aim/web/ui_v2/package-lock.json, aim/web/ui_v2/package.json, aim/web/ui_v2/src/components/CustomTable/TableColumn.tsx, aim/web/ui_v2/src/components/Table/Table.tsx, aim/web/ui_v2/src/pages/Metrics/Metrics.tsx, aim/web/ui_v2/src/pages/Metrics/components/MetricsTableGrid/MetricsTableGrid.tsx, aim/web/ui_v2/src/services/models/metrics/metricsAppModel.ts
- Edit `homepage`  field in `package.json` for static files serving
- Remove `package-lock.json` file from `.gitignore`
- Add table group expand/collapse actions
=> Add table group expand/collapse actions

aim/web/ui_v2/src/components/HeatMap/HeatMap.tsx, aim/web/ui_v2/src/components/Table/Table.tsx, aim/web/ui_v2/src/pages/Metrics/Metrics.tsx, aim/web/ui_v2/src/pages/Runs/Runs.tsx, aim/web/ui_v2/src/pages/Runs/RunsContainer.tsx, aim/web/ui_v2/src/pages/Runs/RunsTable.tsx, aim/web/ui_v2/src/pages/Runs/components/RunsTableColumns/RunsTableColumns.tsx, aim/web/ui_v2/src/services/models/metrics/metricsAppModel.ts, aim/web/ui_v2/src/services/models/runs/runsAppModel.ts, aim/web/ui_v2/src/types/components/Table/Table.d.ts, aim/web/ui_v2/src/types/pages/runs/Runs.d.ts, aim/web/ui_v2/src/types/services/models/params/paramsAppModel.d.ts
- Table config caching mechanism for Metrics and Runs tables
- Runs Table's actions functionality
- Fix the syntax of the query generated on Activity board's Cell click action
=> Add runs table actions

aim/web/ui_v2/src/components/GroupingPopover/GroupingPopover.tsx, aim/web/ui_v2/src/pages/Metrics/components/Grouping/Grouping.tsx, aim/web/ui_v2/src/pages/Metrics/components/GroupingItem/GroupingItem.tsx, aim/web/ui_v2/src/pages/Metrics/components/MetricsBar/MetricsBar.scss, aim/web/ui_v2/src/pages/Metrics/components/StrokePopover/StrokePopoverAdvanced.scss, aim/web/ui_v2/src/pages/Metrics/components/StrokePopover/StrokePopoverAdvanced.tsx, aim/web/ui_v2/src/pages/Params/Params.tsx, aim/web/ui_v2/src/services/models/metrics/metricsAppModel.ts, aim/web/ui_v2/src/services/models/params/paramsAppModel.ts, aim/web/ui_v2/src/services/models/runs/runsAppModel.ts, aim/web/ui_v2/src/types/pages/metrics/Metrics.d.ts, aim/web/ui_v2/src/types/pages/params/Params.d.ts, aim/web/ui_v2/src/types/services/models/metrics/metricsAppModel.d.ts, aim/web/ui_v2/src/types/services/models/params/paramsAppModel.d.ts
- Fixed grouping subtitles
- Renamed style grouping title to stroke
=> Fix grouping subtitles

aim/web/ui_v2/src/components/NotificationContainer/NotificationContainer.scss, aim/web/ui_v2/src/pages/Bookmarks/components/BookmarkCard/BookmarkCard.tsx, aim/web/ui_v2/src/pages/Params/Params.tsx, aim/web/ui_v2/src/pages/Params/ParamsContainer.tsx, aim/web/ui_v2/src/routes/routes.tsx, aim/web/ui_v2/src/services/models/params/paramsAppModel.ts, aim/web/ui_v2/src/types/pages/params/Params.d.ts
- Improve state recovering when navigating from bookmarks to Params page
- Add update bookmark button and functionality to Params page
- Display toast on bookmark create/update to Params page
=> Display toaster on bookmarks create update

aim/web/ui_v2/src/pages/RunDetail/RunDetail.tsx, aim/web/ui_v2/src/pages/RunDetail/RunDetailParamsTab.tsx
- Add a content loader
- Redirect to runs explorer when clicking on breadcrumbs Runs item
=> tune single run page

aim/storage/container.py
initialize container's writable db when container object is created, instead of first write access
=> Fix run finalization

aim/web/ui_v2/src/components/Table/Table.tsx, aim/web/ui_v2/src/pages/Runs/RunsTable.tsx
Fixed Runs table unmount-mount issue caused by `key` prop value change.
=> Recover scroll position on new data load

aim/web/ui_v2/src/pages/Runs/Runs.tsx, aim/web/ui_v2/src/pages/Runs/RunsContainer.tsx, aim/web/ui_v2/src/pages/Runs/components/RunsTableColumns/RunsTableColumns.tsx, aim/web/ui_v2/src/services/models/metrics/metricsAppModel.ts, aim/web/ui_v2/src/services/models/runs/runsAppModel.ts, aim/web/ui_v2/src/types/pages/metrics/components/TableColumns/TableColumns.d.ts, aim/web/ui_v2/src/types/pages/runs/Runs.d.ts
- Add ability to toggle visibility of a single column
- Add ability to hide/show all columns
- Add ability to hide columns with the same value for each row (show table diff)
=> Add ability to toggle column visibility in Runs table

aim/web/ui_v2/src/components/ChartPanel/ChartPanel.tsx, aim/web/ui_v2/src/pages/Metrics/Metrics.scss, aim/web/ui_v2/src/pages/Metrics/Metrics.tsx, aim/web/ui_v2/src/pages/Metrics/components/SelectForm/SelectForm.scss, aim/web/ui_v2/src/pages/Metrics/components/SelectForm/SelectForm.tsx, aim/web/ui_v2/src/pages/Params/Params.scss, aim/web/ui_v2/src/pages/Params/Params.tsx, aim/web/ui_v2/src/pages/Params/components/SelectForm/SelectForm.scss, aim/web/ui_v2/src/pages/Params/components/SelectForm/SelectForm.tsx, aim/web/ui_v2/src/types/components/ChartPanel/ChartPanel.d.ts
- added min width container in params and metric pages
- improve  select form tags box element styles
=> Add min-width to container for responsiveness

aim/web/ui_v2/src/hooks/resize/usePanelResize.ts, aim/web/ui_v2/src/pages/Metrics/Metrics.scss, aim/web/ui_v2/src/pages/Params/Params.scss
- Fixed panel resizing state bug
- Set min height in table and chart components
=> Fix panel resizing state bug

aim/web/ui_v2/src/pages/Metrics/components/Controls/Controls.tsx, aim/web/ui_v2/src/pages/Params/components/Controls/Controls.tsx
- Added tooltips for chart control buttons
=> Add tooltips for chart control buttons

aim/web/ui_v2/src/components/Table/Table.tsx, aim/web/ui_v2/src/services/api/api.ts, aim/web/ui_v2/src/services/models/runs/runsAppModel.ts
- Added Table's prop custom comparator to re-render or not by changing some props
- Added API level exception handling, to handle exceptions easily
- Handled Query Syntax exceptions on runs page
=> Exception handler

aim/web/ui_v2/src/components/ControlPopover/ControlPopover.tsx, aim/web/ui_v2/src/components/CustomTable/Table.scss, aim/web/ui_v2/src/components/CustomTable/TableColumn.tsx, aim/web/ui_v2/src/types/components/ControlPopover/ControlPopover.d.ts
- Updated table grouping action popover
- Added ability to render ControlPopover component props as function
=> Update table grouping action popover

aim/web/ui_v2/src/pages/Params/components/ParamsTableGrid/ParamsTableGrid.tsx, aim/web/ui_v2/src/pages/Runs/components/RunsTableColumns/RunsTableColumns.tsx, aim/web/ui_v2/src/services/models/params/paramsAppModel.ts, aim/web/ui_v2/src/services/models/runs/runsAppModel.ts
- Implement metrics columns in `Runs` table
- Implement metrics columns in `Params` table
=> Implement metrics columns in table

aim/web/ui_v2/src/components/CustomTable/TableCell.tsx, aim/web/ui_v2/src/pages/Metrics/components/MetricsTableGrid/MetricsTableGrid.tsx, aim/web/ui_v2/src/services/models/metrics/metricsAppModel.ts, aim/web/ui_v2/src/types/services/models/metrics/metricsAppModel.d.ts
- Provide custom row renderer for Metrics page table
- Add navigation link for run detail page on run cell
=> Add ability to provide custom row renderer for Table component

aim/web/ui_v2/src/components/Table/Table.tsx, aim/web/ui_v2/src/pages/Runs/Runs.scss, aim/web/ui_v2/src/pages/Runs/RunsContainer.tsx, aim/web/ui_v2/src/pages/Runs/RunsTable.tsx, aim/web/ui_v2/src/services/models/runs/runsAppModel.ts
- Added loader component
- Changed the logic of taking last row's hash
- Added the logic to do not fetch new runs if there are no more runs
=> Add loader component as an infinite loader on runs page

aim/web/ui_v2/src/components/Table/Table.tsx, aim/web/ui_v2/src/pages/Metrics/components/MetricsTableGrid/MetricsTableGrid.tsx, aim/web/ui_v2/src/pages/Params/components/ParamsTableGrid/ParamsTableGrid.tsx, aim/web/ui_v2/src/pages/Runs/Runs.scss, aim/web/ui_v2/src/pages/Runs/RunsTable.tsx, aim/web/ui_v2/src/pages/Runs/components/RunsTableGrid/RunsTableGrid.tsx, aim/web/ui_v2/src/services/models/metrics/metricsAppModel.ts, aim/web/ui_v2/src/services/models/params/paramsAppModel.ts, aim/web/ui_v2/src/services/models/runs/runsAppModel.ts
- Add custom row renderer for Runs table
- Add custom row renderer for Params table
- Add nav links for the Run single page
- Improved infinite scroll load handler
=> Add ability to navigate to run single page from table

aim/web/ui_v2/src/components/Table/Table.tsx, aim/web/ui_v2/src/services/models/metrics/metricsAppModel.ts, aim/web/ui_v2/src/services/models/params/paramsAppModel.ts, aim/web/ui_v2/src/services/models/runs/runsAppModel.ts
- Fix handling bug of api error corner cases
- change memo's comparator logic to re-render table after changing rowHeight prop
=> Fix handling bug of api error corner cases

aim/web/ui_v2/src/pages/Params/Params.tsx, aim/web/ui_v2/src/pages/Params/ParamsContainer.tsx, aim/web/ui_v2/src/services/models/metrics/metricsAppModel.ts, aim/web/ui_v2/src/services/models/params/paramsAppModel.ts, aim/web/ui_v2/src/services/models/runs/runsAppModel.ts, aim/web/ui_v2/src/types/pages/params/Params.d.ts
- Add an ability to hide all columns with the same value for each row in Params Explorer
- Improved state for all hidden rows for Metrics Explorer
- Improved state for all hidden rows for Params Explorer
=> Add ability to show table diff in Params Explorer

aim/web/ui_v2/src/components/ChartPanel/config.ts, aim/web/ui_v2/src/services/models/metrics/metricsAppModel.ts, aim/web/ui_v2/src/services/models/params/paramsAppModel.ts, aim/web/ui_v2/src/services/models/runs/runsAppModel.ts
We need to get table raw data for table export without custom row renderer data(without JSX)
=> Fix table export with custom row renderer

aim/web/ui_v2/src/components/CustomTable/Table.scss, aim/web/ui_v2/src/components/CustomTable/Table.tsx, aim/web/ui_v2/src/components/Table/Table.tsx, aim/web/ui_v2/src/config/table/tableConfigs.ts, aim/web/ui_v2/src/pages/Metrics/components/Table/RowHeightPopover/RowHeightPopover.tsx
Added css variable for cell height and group margin to be able to change their value based on table container className
which is being changed once user selects new mode for row height
=> Add row height change functionality on table

aim/web/ui_v2/src/pages/Home/components/ExploreAim/ExploreAim.scss
Tuned get involved cards links
=> Fix visited state color of "get involved" cards links

aim/web/ui_v2/src/components/CustomTable/Table.scss, aim/web/ui_v2/src/components/Table/Table.tsx, aim/web/ui_v2/src/pages/Metrics/Metrics.scss, aim/web/ui_v2/src/pages/Metrics/components/MetricsTableGrid/MetricsTableGrid.tsx, aim/web/ui_v2/src/services/models/metrics/metricsAppModel.ts, aim/web/ui_v2/src/services/models/params/paramsAppModel.ts, aim/web/ui_v2/src/services/models/runs/runsAppModel.ts
- Modify value column content for group header rows
- Apply group aggregation data change to table dynamic update function
=> Add group aggregation data to table value column

aim/sdk/run.py
Check that run has no params set and set to empty dict
=> set run params to empty dict to newly created run

aim/web/ui_v2/src/components/HighPlot/HighPlot.scss, aim/web/ui_v2/src/components/HighPlot/HighPlot.tsx, aim/web/ui_v2/src/services/models/params/paramsAppModel.ts, aim/web/ui_v2/src/types/utils/d3/drawParallelAxes.d.ts, aim/web/ui_v2/src/utils/d3/drawParallelAxes.ts, aim/web/ui_v2/src/utils/getInnerTextFromHtml.ts
Add: 
- dimension title width and position dynamic calculation
Fix: 
- dimension ticks formatting
=> HighPlot tune dimensions ticks and titles

aim/web/ui_v2/src/components/Table/Table.tsx, aim/web/ui_v2/src/pages/Metrics/Metrics.tsx, aim/web/ui_v2/src/pages/Params/Params.tsx
Updated rendering dependencies in Table component
---
- Deleted unnecessary key property from Table component (Metrics/Params)
=> Update rendering dependencies in Table component

aim/web/ui_v2/src/components/TagLabel/TagLabel.scss, aim/web/ui_v2/src/components/TagLabel/TagLabel.tsx, aim/web/ui_v2/src/pages/Bookmarks/components/BookmarkCard/BookmarkCard.scss, aim/web/ui_v2/src/pages/Metrics/components/MetricsTableGrid/MetricsTableGrid.tsx, aim/web/ui_v2/src/pages/Metrics/components/SelectForm/SelectForm.scss, aim/web/ui_v2/src/pages/Params/components/ParamsTableGrid/ParamsTableGrid.tsx, aim/web/ui_v2/src/pages/Params/components/SelectForm/SelectForm.scss, aim/web/ui_v2/src/pages/Runs/components/RunsTableGrid/RunsTableGrid.tsx, aim/web/ui_v2/src/types/components/SelectTag/SelectTag.d.ts
Set size property on TagLabel component and updated styles
---
- Applied size prop to TagLabel component in project
=> Tune TagLabel component

aim/web/ui_v2/src/components/CustomTable/Table.scss, aim/web/ui_v2/src/config/table/tableConfigs.ts, aim/web/ui_v2/src/pages/Metrics/Metrics.scss
- Improve table value column size for grouped mode
- Changed groups gap sizes
=> Improve aggregation values column layout for area None mode

aim/web/ui_v2/src/components/CustomTable/Table.tsx, aim/web/ui_v2/src/components/CustomTable/TableColumn.tsx, aim/web/ui_v2/src/components/Table/Table.tsx, aim/web/ui_v2/src/pages/Metrics/MetricsContainer.tsx
- Add ability to `hide` the column from column actions popover
- Add ability to `pin/unpin` the column from columns actions popover
- Add ability to change the column order within pinned pane from column actions popover
=> Add table column actions handlers

MANIFEST.in
due to some unknown reason migration files (both storage and ui) and UI static files are not added in source distribution.
added all required files to MANIFEST.in.
tested installation of both sdist and bdist_wheel
=> added UI files and migration files to source distribution.

aim/web/ui_v2/src/components/CustomTable/Table.scss, aim/web/ui_v2/src/components/CustomTable/TableCell.tsx, aim/web/ui_v2/src/components/CustomTable/TableColumn.tsx, aim/web/ui_v2/src/pages/Metrics/components/MetricsTableGrid/MetricsTableGrid.tsx, aim/web/ui_v2/src/pages/Params/components/ParamsTableGrid/ParamsTableGrid.tsx, aim/web/ui_v2/src/services/models/metrics/metricsAppModel.ts, aim/web/ui_v2/src/services/models/params/paramsAppModel.ts
- Add group config elements to table group first column
- Display row color on rows first cell
=> Display group config properties in table

aim/web/ui_v2/src/components/CustomTable/Table.scss, aim/web/ui_v2/src/components/CustomTable/TableColumn.tsx, aim/web/ui_v2/src/components/ResizePanel/ResizePanel.scss, aim/web/ui_v2/src/components/SideBar/Sidebar.scss, aim/web/ui_v2/src/pages/Metrics/components/MetricsBar/MetricsBar.scss, aim/web/ui_v2/src/pages/Metrics/components/MetricsBar/MetricsBar.tsx, aim/web/ui_v2/src/pages/Metrics/components/MetricsTableGrid/MetricsTableGrid.tsx, aim/web/ui_v2/src/pages/Params/components/ParamsTableGrid/ParamsTableGrid.tsx
Wrapped icons with Button component
---
- Updated Aim logo size in sidebar
- Wrapped table action buttons with Tooltip component
=> Tune table icon buttons

aim/web/ui_v2/src/components/Table/Table.tsx, aim/web/ui_v2/src/pages/Metrics/Metrics.tsx, aim/web/ui_v2/src/pages/Metrics/MetricsContainer.tsx, aim/web/ui_v2/src/pages/Params/Params.tsx, aim/web/ui_v2/src/pages/Params/ParamsContainer.tsx, aim/web/ui_v2/src/pages/Runs/Runs.tsx, aim/web/ui_v2/src/pages/Runs/RunsContainer.tsx, aim/web/ui_v2/src/pages/Runs/RunsTable.tsx, aim/web/ui_v2/src/services/models/metrics/metricsAppModel.ts, aim/web/ui_v2/src/services/models/params/paramsAppModel.ts, aim/web/ui_v2/src/services/models/runs/runsAppModel.ts, aim/web/ui_v2/src/types/pages/metrics/Metrics.d.ts, aim/web/ui_v2/src/types/pages/params/Params.d.ts, aim/web/ui_v2/src/types/pages/runs/Runs.d.ts, aim/web/ui_v2/src/types/services/models/metrics/metricsAppModel.d.ts
- Added updateColumnWidth method to paramsAppModel, runsAppModel and metricsAppModel
- Implement column width value storing in Params, Runs and Metrics pages
- Implement reset width functionality
=> Implement store column resized width value

aim/storage/encoding/encoding.py, aim/storage/encoding/encoding_native.pxd, aim/storage/encoding/encoding_native.pyx, aim/storage/hashing/c_hash.pyi, aim/storage/hashing/c_hash.pyx, aim/storage/hashing/hashing.py
This PR adds documentation, details on implementations and tricks on Encodings and Hashing.
The change also includes a slight refactoring of source code.
=> Storage Documentation for Encodings & Hashing

aim/web/ui/src/pages/Metrics/Metrics.tsx, aim/web/ui/src/pages/Metrics/MetricsContainer.tsx, aim/web/ui/src/pages/Metrics/components/Controls/Controls.tsx, aim/web/ui/src/services/models/metrics/metricsAppModel.ts, aim/web/ui/src/types/pages/metrics/Metrics.d.ts, aim/web/ui/src/types/pages/metrics/components/controls/Controls.d.ts, aim/web/ui/src/types/services/models/metrics/metricsAppModel.d.ts, aim/web/ui/src/utils/d3/processData.ts
Reverted Ignore outliers state
---
- Set Ignore outliers state true by default
- Renamed display outliers property to ignore outliers
=> Fix Ignore outliers functionality

aim/web/ui/src/components/ChartPanel/ChartPanel.tsx, aim/web/ui/src/components/ChartPanel/ChartPopover/ChartPopover.tsx, aim/web/ui/src/types/components/ChartPanel/PopoverContent.d.ts, aim/web/ui/src/utils/getPositionBasedOnOverflow.ts
Fix: 
- there are some cases when tooltip hide active point
=> Fix chart tooltip positioning

aim/web/ui/src/components/HighPlot/HighPlot.tsx, aim/web/ui/src/components/LineChart/LineChart.tsx, aim/web/ui/src/hooks/resize/usePanelResize.ts, aim/web/ui/src/hooks/window/useResizeObserver.ts, aim/web/ui/src/utils/d3/drawHoverAttributes.ts, aim/web/ui/src/utils/d3/drawParallelHoverAttributes.ts
On chart mouse over handle function wrapped by request animation frame to improve rendering performance
=> Add requestAnimation frame on chart mouse move

aim/web/ui/src/services/api/api.ts, aim/web/ui/src/services/models/metrics/metricsAppModel.ts, aim/web/ui/src/services/models/params/paramsAppModel.ts, aim/web/ui/src/services/models/runs/runsAppModel.ts
Call api specific exception handler for the corner cases (i.e. couldn't fetch, etc.)
=> Call api specific exception handler for the corner cases

aim/web/ui/src/components/AppBar/AppBar.scss, aim/web/ui/src/components/ChartPanel/ChartPopover/ChartPopover.tsx, aim/web/ui/src/pages/Metrics/components/MetricsBar/MetricsBar.scss, aim/web/ui/src/pages/Metrics/components/MetricsBar/MetricsBar.tsx, aim/web/ui/src/utils/d3/drawParrallelArea.ts
Set drawing parallel area with and height with px instead of percent
---
- Tuned bookmark button in metrics page app bar
=> Fix HighPlot chart drawing issue on Safari

aim/web/ui/src/components/CustomTable/TableColumn.tsx, aim/web/ui/src/pages/Bookmarks/components/BookmarkCard/BookmarkCard.scss, aim/web/ui/src/pages/Bookmarks/components/BookmarkCard/BookmarkCard.tsx, aim/web/ui/src/pages/Metrics/components/MetricsTableGrid/MetricsTableGrid.tsx, aim/web/ui/src/pages/Params/Params.tsx, aim/web/ui/src/pages/Params/ParamsContainer.tsx, aim/web/ui/src/pages/Params/components/ParamsTableGrid/ParamsTableGrid.tsx, aim/web/ui/src/pages/Runs/Runs.tsx, aim/web/ui/src/pages/Runs/RunsContainer.tsx
Deleted unnecessary setDefaultConfig function from ParamsContainer
---
- Tuned Icon Button sizes
- Tuned paths in RunsContainer and Runs components
=> Fix params app state issue while routing from bookmarks

aim/web/ui/src/services/models/metrics/metricsAppModel.ts, aim/web/ui/src/services/models/params/paramsAppModel.ts
Disabled updating table rows in onActivePointChange function on hidden table
=> Disable row updating on hidden table

aim/web/ui/src/pages/Metrics/components/MetricsBar/MetricsBar.tsx, aim/web/ui/src/pages/Metrics/components/SelectForm/SelectForm.scss, aim/web/ui/src/pages/Metrics/components/SelectForm/SelectForm.tsx, aim/web/ui/src/pages/Params/components/SelectForm/SelectForm.scss, aim/web/ui/src/pages/Params/components/SelectForm/SelectForm.tsx, aim/web/ui/src/pages/Runs/components/SearchBar/SearchBar.scss, aim/web/ui/src/pages/Runs/components/SearchBar/SearchBar.tsx
- Disabled spell check from SelectForm inputs (Metrics/Params/Runs)
- Set font family to monospace (Metrics/Params/Runs)
=> Tune SelectForm input

aim/web/ui/src/services/models/metrics/metricsAppModel.ts, aim/web/ui/src/services/models/params/paramsAppModel.ts
- Update URL on chart tooltip content change
- Fixed URL update on chart focused point change
=> Update URL on chart tooltip content change

aim/web/ui/src/components/ChartLoader/ChartLoader.scss, aim/web/ui/src/components/ChartLoader/ChartLoader.tsx, aim/web/ui/src/components/ResizePanel/ResizePanel.scss, aim/web/ui/src/components/ResizePanel/ResizePanel.tsx, aim/web/ui/src/pages/Metrics/Metrics.tsx, aim/web/ui/src/pages/Metrics/components/Controls/Controls.scss, aim/web/ui/src/pages/Params/Params.tsx, aim/web/ui/src/services/models/metrics/metricsAppModel.ts, aim/web/ui/src/services/models/params/paramsAppModel.ts, aim/web/ui/src/styles/abstracts/_variables.scss, aim/web/ui/src/types/components/ChartLoader/ChartLoader.d.ts, aim/web/ui/src/types/services/models/metrics/metricsAppModel.d.ts
Updated resize panel styles with new design
---
- Fixed unnecessary loading state in metrics page
- Added controlsCount property ChartLoader skeleton and fixed styles
=> Update resize panel styles

aim/web/ui/src/services/models/metrics/metricsAppModel.ts
Update URL on chart settings update:
- Highlight mode change
- Chart zooming change
=> Add URL update on highlight mode and zoom change

aim/web/ui/package-lock.json, aim/web/ui/package.json, aim/web/ui/src/pages/Metrics/components/ColorPopoverAdvanced/ColorPopoverAdvanced.tsx, aim/web/ui/src/pages/Metrics/components/StrokePopover/StrokePopoverAdvanced.tsx, aim/web/ui/src/services/models/metrics/metricsAppModel.ts, aim/web/ui/src/services/models/params/paramsAppModel.ts, aim/web/ui/src/services/models/runs/runsAppModel.ts, aim/web/ui/src/types/services/models/metrics/metricsAppModel.d.ts, aim/web/ui/src/utils/encoder/encoder.ts
Fixed persistence change issue
---
- Added `md5` encoder for one way hashing
- Added `groupName` argument in `getGroupingPersistIndex` function
- Added `oneWayHashing`  in `encode` function
=> Fix persistence change functionality

aim/web/ui/src/components/AppBar/AppBar.scss, aim/web/ui/src/components/AxesScalePopover/AxesScalePopover.scss, aim/web/ui/src/components/ControlPopover/ControlPopover.scss, aim/web/ui/src/components/CustomTable/Table.scss, aim/web/ui/src/components/Theme/Theme.tsx, aim/web/ui/src/components/ToggleButton/ToggleButton.scss, aim/web/ui/src/pages/Metrics/Metrics.tsx, aim/web/ui/src/pages/Metrics/MetricsContainer.tsx, aim/web/ui/src/pages/Metrics/components/ColorPopoverAdvanced/ColorPopoverAdvanced.scss, aim/web/ui/src/pages/Metrics/components/ColorPopoverAdvanced/ColorPopoverAdvanced.tsx, aim/web/ui/src/pages/Metrics/components/Grouping/Grouping.tsx, aim/web/ui/src/pages/Metrics/components/GroupingItem/groupingItemStyle.scss, aim/web/ui/src/pages/Metrics/components/StrokePopover/StrokePopoverAdvanced.scss, aim/web/ui/src/pages/Metrics/components/StrokePopover/StrokePopoverAdvanced.tsx, aim/web/ui/src/pages/Params/Params.tsx, aim/web/ui/src/pages/Params/ParamsContainer.tsx, aim/web/ui/src/services/models/metrics/metricsAppModel.ts, aim/web/ui/src/services/models/params/paramsAppModel.ts, aim/web/ui/src/styles/abstracts/_variables.scss, aim/web/ui/src/styles/components/_inputs.scss, aim/web/ui/src/types/components/GroupingPopover/GroupingPopover.d.ts, aim/web/ui/src/types/pages/metrics/Metrics.d.ts, aim/web/ui/src/types/pages/metrics/components/Grouping/Grouping.d.ts, aim/web/ui/src/types/pages/params/Params.d.ts
Added ability to shuffle colors and strokes in grouping persistence mode
---
- Implemented in params and metrics explore pages
=> Add shuffling seed value functionality

aim/web/ui/src/components/CustomTable/Table.scss, aim/web/ui/src/components/Table/BaseTable.scss, aim/web/ui/src/components/TagForm/TagForm.scss, aim/web/ui/src/components/TagForm/TagForm.tsx, aim/web/ui/src/components/kit/Badge/Badge.scss, aim/web/ui/src/pages/Bookmarks/components/BookmarkCard/BookmarkCard.scss, aim/web/ui/src/pages/Home/components/ExploreAim/ExploreAim.scss, aim/web/ui/src/pages/Home/components/ExploreAimCard/ExploreAimCard.scss, aim/web/ui/src/pages/RunDetail/RunDetail.scss, aim/web/ui/src/pages/Runs/Runs.scss, aim/web/ui/src/pages/Tags/TagDelete.tsx, aim/web/ui/src/pages/Tags/TagSoftDelete.tsx, aim/web/ui/src/pages/Tags/Tags.scss, aim/web/ui/src/pages/Tags/TagsList.tsx, aim/web/ui/src/pages/Tags/TagsTable.tsx, aim/web/ui/src/styles/abstracts/_variables.scss
- Implemented `Text` component in Tags page
- Added `$border-grey` scss variable
=> implement Text component in Tags page

aim/web/ui/src/components/ConfirmModal/ConfirmModal.scss, aim/web/ui/src/components/ConfirmModal/ConfirmModal.tsx, aim/web/ui/src/pages/Bookmarks/components/BookmarkCard/BookmarkCard.scss, aim/web/ui/src/pages/Bookmarks/components/BookmarkCard/BookmarkCard.tsx
- Refactored `BookmarkCard.scss` and `ConfirmModal.scss`
- Implemented Text component in `ConfirmModal` component
=> Implement Text component in Bookmarks page

aim/web/ui/src/pages/RunDetail/RunDetail.scss, aim/web/ui/src/pages/RunDetail/RunDetail.tsx, aim/web/ui/src/pages/RunDetail/RunDetailParamsTab.tsx, aim/web/ui/src/pages/RunDetail/RunDetailSettingsTab.tsx, aim/web/ui/src/pages/RunDetail/RunMetricCard.tsx
- Implemented Text component in runs page
- Tuned archive/unArchive button
=> Implement Text component in Runs page

aim/storage/structured/sql_engine/entities.py, aim/web/api/experiments/pydantic_models.py, aim/web/api/experiments/views.py, aim/web/api/runs/pydantic_models.py, aim/web/api/runs/utils.py, aim/web/api/tags/views.py, tests/api/test_run_api.py, tests/api/test_structured_data_api.py
Made some minor changes for 'runs/{run_id}/info/' and 'tags/{tag}/runs/' endpoints along the way
=> Add pagination for 'experiments/{exp_id}/runs/' endpoint 

aim/storage/rockscontainer.py, setup.py
Added `flush` and `flush_wal` on container close and changed db write options based on previous discussions
=> Flush methods on container close

aim/cli/init/commands.py
Fix typo on aim init command comments
=> Fix typo on aim init command comments

aim/sdk/objects/image.py
Added image mode and image type. Image type is hard-coded to 'PIL.Image'
=> [feat] Additional properties for Aim Images built from PIL.Image.Image

aim/storage/arrayview.py, aim/web/api/runs/image_utils.py
Added method to select N values from the given [start, stop) range
of tracked steps. Entire range is loaded into memory so the number of
items can be identified and sliced correctly.
=> Slice image sequence by index for the given steps range.

aim/web/ui/src/components/ImagesList/ImageBox.tsx, aim/web/ui/src/components/ImagesPanel/ImagesPanel.tsx, aim/web/ui/src/config/imagesConfigs/imagesConfig.ts
Changed images URIs get by batch request delay from `1s` to `300ms`
=> Update images URI batch request delay

aim/sdk/objects/image.py, examples/pytorch_track_images.py
Added support for tf.Tensor and torch.Tensor.
Added support for numpy.array.
Refactored PIL.Image support.
=> Support of Image input additional data sources.

aim/web/ui/src/utils/d3/drawAxes.ts, aim/web/ui/src/utils/d3/processData.ts
- Apply `remove outliers` functionality on min and max values of all lines
- Improve X-axis ticks range calculation for time alignment
=> Improve line chart outliers calculation

aim/web/ui/src/components/ImagesList/ImageBox.tsx, aim/web/ui/src/components/ImagesPanel/ImagesPanel.tsx, aim/web/ui/src/config/imagesConfigs/imagesConfig.ts, aim/web/ui/src/services/models/imagesExplore/imagesExploreAppModel.ts
Implement throttling behavior for blobs iterative rendering.
=> Apply throttling on images blob data update

aim/sdk/__init__.py, aim/sdk/distribution_sequence.py, aim/sdk/objects/__init__.py, aim/sdk/objects/distribution.py, aim/sdk/repo.py, aim/sdk/run.py, aim/storage/context.py, aim/storage/inmemorytreeview.py, aim/storage/query.py, aim/storage/treeutils_.pyx, aim/web/api/runs/image_utils.py, aim/web/api/runs/pydantic_models.py, aim/web/api/runs/utils.py, aim/web/api/runs/views.py, tests/api/test_run_images_api.py
- Add `Distribution`: `CustomObject` sub-class
- Add `Distributions`: `Sequence` sub-class
- Add utility functions for distributions and allow querying for distributions
- Add endpoints and utils for visualization of distributions on single run page view
- Some refactoring along the way
=> Add ability to track distributions

aim/sdk/run.py, aim/web/api/runs/image_utils.py, aim/web/api/runs/utils.py, aim/web/api/runs/views.py, tests/api/test_run_images_api.py
Add support for images' tab record and index ranges in single run page. Fix sequence retrieval method to check compatibility between requested sequence dtypes and tracked sequence dtype.
=> Single run images tab ranges

aim/web/ui/src/components/ImagesList/ImageBox.tsx, aim/web/ui/src/components/ImagesList/ImagesList.d.ts, aim/web/ui/src/components/ImagesList/ImagesList.tsx, aim/web/ui/src/components/ImagesPanel/ImagesPanel.d.ts, aim/web/ui/src/components/ImagesPanel/ImagesPanel.tsx, aim/web/ui/src/components/ImagesSet/ImagesSet.d.ts, aim/web/ui/src/components/ImagesSet/ImagesSet.tsx, aim/web/ui/src/pages/ImagesExplore/ImagesExplore.tsx, aim/web/ui/src/services/models/imagesExplore/imagesExploreAppModel.ts, aim/web/ui/src/services/models/imagesExplore/imagesURIModel.ts, aim/web/ui/src/services/models/model.ts, aim/web/ui/src/types/services/models/imagesExplore/imagesExploreAppModel.d.ts, aim/web/ui/src/types/services/models/model.d.ts
- Add a pub/sub mechanism for rendering images blob data
- Add ability to abort blob data stream request
=> Add separate model for handling images blob data rendering

README.md
Have also removed the time because the roadmap keeps growing
=> Update Roadmap with two adaptors

aim/storage/union.py
Left a `TODO` item to get rid of the messy hierarchy of containers
=> Quick fix for `RocksUnionSubContainer`

aim/web/ui/src/pages/Runs/Runs.scss
Fixed calculated height style for runs explorer table panel
---
=> Fix table panel height issue in runs explorer page

CHANGELOG.md, aim/web/ui/src/pages/ImagesExplore/components/ImagesExploreTableGrid/ImagesExploreTableGrid.tsx, aim/web/ui/src/pages/Metrics/components/MetricsTableGrid/MetricsTableGrid.tsx, aim/web/ui/src/pages/Params/components/ParamsTableGrid/ParamsTableGrid.tsx
Set table groups column order to left by default
---
=> Fix table groups column default order

aim/web/ui/src/pages/RunDetail/DistributionsVisualizer/DistributionVisualizer.tsx, aim/web/ui/src/pages/RunDetail/DistributionsVisualizer/temp/Heatmap/Heatmap.js, aim/web/ui/src/pages/RunDetail/DistributionsVisualizer/temp/Wrapper.js, aim/web/ui/src/pages/RunDetail/TraceVisualizationContainer/RangePanel.tsx, aim/web/ui/src/services/models/runs/util.ts
- show the original step value on heatmap's x axis, and histogram's title
=> Show original steps on distributions charts

aim/web/ui/src/pages/ImagesExplore/components/SelectForm/SelectForm.tsx, aim/web/ui/src/pages/RunDetail/TraceVisualizationContainer/TraceVisualizationContainer.scss, aim/web/ui/src/pages/RunDetail/TraceVisualizationContainer/TraceVisualizationContainer.tsx, aim/web/ui/src/services/models/runs/util.ts, aim/web/ui/src/utils/alphabeticalSortComparator.ts
- Show contexts list ordered by stringified value alphabetically
=> Sort context names alphabetically

.github/workflows/pull-request.yml
Added `pull_request_target` to pipeline triggers.
=> [feat] Enable pull request pipeline for external PRs.

aim/web/ui/src/components/Table/BaseTable.tsx, aim/web/ui/src/components/Table/utils.ts, aim/web/ui/src/services/models/explorer/createAppModel.ts, aim/web/ui/src/services/models/imagesExplore/imagesExploreAppModel.ts, aim/web/ui/src/services/models/runs/util.ts, aim/web/ui/src/utils/app/getGroupConfig.ts, aim/web/ui/src/utils/app/getTooltipData.ts, aim/web/ui/src/utils/formatValue.ts, aim/web/ui/src/utils/getObjectPaths.ts, aim/web/ui/src/utils/helper/getPathSegments/getPathSegments.ts, aim/web/ui/src/utils/helper/getValue/getValue.ts, aim/web/ui/src/utils/helper/index.ts
Lodash get function works with issues and we decided to create our custom getValue function
=> Refactor lodash get function to custom to avoid URL compatibility issues

aim/sdk/adapters/hugging_face.py
This PR adds custom run parameters to the Huggingface Callback.
It tries to solve this [feature](https://github.com/aimhubio/aim/issues/1116) request.
=> Add run parameters to huggingface callback

CHANGELOG.md, aim/web/ui/src/utils/formatValue.ts, aim/web/ui/src/utils/helper/getValue/getValue.ts
Fix:
- getValue function to show correct chart title
- formatValue function to show correct formatted data
=> Fix getValue function to show correct chart title

aim/ext/notebook/notebook.py
=> Enable caching in colab

CHANGELOG.md, aim/web/ui/src/services/models/explorer/createAppModel.ts
- Fix issue with not providing point density value in live-update query
=> Fix issue with not providing point density value in live-update query

aim/web/ui/src/components/kit/AudioBox/AudioBox.scss, aim/web/ui/src/components/kit/AudioBox/AudioBox.tsx, aim/web/ui/src/styles/abstracts/_variables.scss
- Added ability to download audio before playing
- Tuned disabled state of volume controller
=> Enhance AudioPlayer component

aim/sdk/objects/image.py
Adds features:
- Read image content from file path
- Let user define extra PIL save parameters
=> [feat] image object enhancements

aim/sdk/adapters/pytorch_lightning.py
fixes bug as mentioned in #404
=> (fix) handling omegaconf params

CHANGELOG.md, aim/sdk/run.py, aim/storage/structured/sql_engine/entities.py
Change timestamps to be timezone aware instead of using local timezone
=> Fix timezone issues

CHANGELOG.md, aim/web/api/runs/views.py, aim/web/ui/src/components/ConfirmModal/ConfirmModal.scss, aim/web/ui/src/components/ConfirmModal/ConfirmModal.tsx, aim/web/ui/src/components/kit/ActionCard/ActionCard.d.ts, aim/web/ui/src/components/kit/ActionCard/ActionCard.scss, aim/web/ui/src/components/kit/ActionCard/ActionCard.tsx, aim/web/ui/src/components/kit/ActionCard/index.tsx, aim/web/ui/src/components/kit/index.ts, aim/web/ui/src/pages/Bookmarks/components/BookmarkCard/BookmarkCard.tsx, aim/web/ui/src/pages/RunDetail/RunDetail.scss, aim/web/ui/src/pages/RunDetail/RunDetailSettingsTab.tsx, aim/web/ui/src/pages/Tags/TagDelete.tsx, aim/web/ui/src/pages/Tags/Tags.scss, aim/web/ui/src/services/api/runs/runsService.ts, aim/web/ui/src/services/models/runs/runDetailAppModel.ts, aim/web/ui/src/services/models/tags/tagsAppModel.ts, aim/web/ui/src/styles/abstracts/_variables.scss, aim/web/ui/src/types/components/ConfirmModal/ConfirmModal.d.ts
- Added `id` as `run.hash` prop to run delete endpoint response object
- Added delete button to run settings tab
- Changed archive button styles
=> Add delete button to single run page.

aim/web/ui/src/components/MediaPanel/MediaPanel.tsx, aim/web/ui/src/components/MediaSet/MediaSet.tsx, aim/web/ui/src/pages/RunDetail/DistributionsVisualizer/DistributionsVisualizer.scss, aim/web/ui/src/pages/RunDetail/TraceVisualizationContainer/TraceVisualizationContainer.scss
- Tuned Run Detail page styles
- Fixed ErrorBoundary issue in Run Detail Page
=> Tune Run Details page styles

CHANGELOG.md, aim/web/ui/src/pages/Metrics/components/Table/SortPopover/SortPopover.tsx, aim/web/ui/src/pages/Metrics/components/Table/SortPopover/SortPopoverList.tsx, aim/web/ui/src/services/models/explorer/createAppModel.ts, aim/web/ui/src/services/models/imagesExplore/imagesExploreAppModel.ts, aim/web/ui/src/utils/app/getGroupingSelectOptions.ts
- Added `run.creation_time` option to sorting popover
- Applied `run.creation_time` as default ordering option
=> Add ability to apply sorting by run creation_time on table rows

aim/web/ui/package.json, aim/web/ui/src/components/ConfirmModal/ConfirmModal.scss, aim/web/ui/src/components/ConfirmModal/ConfirmModal.tsx, aim/web/ui/src/components/SideBar/SideBar.tsx, aim/web/ui/src/pages/Home/components/ExploreAim/ExploreAim.tsx, aim/web/ui/src/pages/ImagesExplore/components/Controls/Controls.tsx
- Fix slack URL
- Fix docs URL
- Change version in package.json
- Move tooltip config control to the bottom of the controls sidebar in Images Explorer
- Change ConfirmModal close icon
=> Update slack and docs URLs in sidebar

aim/web/ui/src/config/controls/controlsDefaultConfig.ts
Change X Axis Properties default value to Maximum in Metrics explorer
=> Change X Axis Properties default value to Maximum in Metrics explorer

aim/web/ui/src/components/CustomTable/TableColumn.tsx, aim/web/ui/src/components/Table/ArchiveModal.tsx, aim/web/ui/src/components/Table/DeleteModal.tsx, aim/web/ui/src/pages/ImagesExplore/components/ImagesExploreTableGrid/ImagesExploreTableGrid.tsx, aim/web/ui/src/pages/RunDetail/RunDetail.tsx, aim/web/ui/src/pages/RunDetail/RunSelectPopoverContent.tsx, aim/web/ui/src/services/models/explorer/createAppModel.ts
- Added default value as "default". If there isn't an experiment name tracked.
=> Add experiment name default value in images explore table

.github/workflows/pull-request.yml, .github/workflows/python-package.yml, performance_tests/requirements.txt, requirements.dev.txt, tests/requirements.txt
Created `tests/requriements.txt` and `performance_tests/requirements.txt`
Moved testing to these files.
Updated pipeline `.yml` files accordingly.
=> [fix] Separate requirements.txt for testing and packaging.

CHANGELOG.md, aim/web/ui/src/pages/ImagesExplore/components/ImagesExploreTableGrid/ImagesExploreTableGrid.tsx, aim/web/ui/src/services/models/imagesExplore/imagesExploreAppModel.ts
- Fixed images explore table experiment name.
=> Fix experiment name 

CHANGELOG.md, aim/web/ui/src/components/GroupingPopover/GroupingPopover.tsx, aim/web/ui/src/components/TooltipContentPopover/TooltipContentPopover.tsx, aim/web/ui/src/services/models/explorer/createAppModel.ts
Fix Autocomplete states' resetting issue when live-update is on
=> [fix] Grouping and Tooltip popovers states' resetting issue when live-update is on

CHANGELOG.md, aim/web/ui/src/pages/ImagesExplore/components/ImagesExploreTableGrid/ImagesExploreTableGrid.tsx, aim/web/ui/src/pages/Metrics/components/MetricsTableGrid/MetricsTableGrid.tsx, aim/web/ui/src/pages/Params/components/ParamsTableGrid/ParamsTableGrid.tsx, aim/web/ui/src/services/models/explorer/createAppModel.ts
- Fix table column's sorting issue in Params Explorer
- Fix table column's sorting issue in Scatters Explorer
- Fix table column's sorting issue in Metrics Explorer
- Fix table column's sorting issue in Images Explorer
=> [fix] Table column's sort functionality issue in params and scatters explorers

CHANGELOG.md, aim/storage/treeutils_.pyx, aim/storage/treeutils_non_native.py
=> [fix] handling omegaconf in nested structure

CHANGELOG.md, aim/web/ui/src/components/ChartPanel/ChartPopover/ChartPopover.tsx, aim/web/ui/src/components/DepthDropdown/DepthDropdown.d.ts, aim/web/ui/src/components/DepthDropdown/DepthDropdown.scss, aim/web/ui/src/components/DepthDropdown/DepthDropdown.tsx, aim/web/ui/src/components/DepthDropdown/index.tsx, aim/web/ui/src/components/DepthSlider/DepthSlider.d.ts, aim/web/ui/src/components/DepthSlider/DepthSlider.scss, aim/web/ui/src/components/DepthSlider/DepthSlider.tsx, aim/web/ui/src/components/DepthSlider/index.tsx, aim/web/ui/src/components/MediaList/ImageBox.tsx, aim/web/ui/src/components/MediaPanel/MediaPanel.tsx, aim/web/ui/src/components/MediaSet/MediaSet.scss, aim/web/ui/src/components/MediaSet/MediaSet.tsx, aim/web/ui/src/components/ScatterPlot/ScatterPlot.tsx
- decrease amount of unnecessarily renderings on mouse hovering(especially outside of the media panel)
- memoize functions (use callback hooks)
- separate `DepthDropdown` and `DepthSlider` components to have more readable and reusable code
=> [feat] Improve media panel rendering performance

CHANGELOG.md, aim/web/ui/src/App.scss
Change background transparency in `colab` when using dark mode of system
=> [fix] Change background transparency in colab when using dark mode of system

aim/web/ui/src/components/kit/ToggleButton/ToggleButton.tsx
- Add value prop change listener to handle the value in toggle button component dynamically
=>  [fix]  Add ability to change value prop of toggle button component dynamically

aim/cli/convert/commands.py, aim/cli/convert/utils.py, docs/source/guides/integrations/basic_aim_tensorflow_event_conversion.md, docs/source/guides/training_reproducibility.md, docs/source/index.rst, docs/source/refs/cli.md
added guides to
- #1272 
- #1203
=> [docs] added feature guide for tf logs conversion & params auto tracking

aim/web/ui/src/services/models/imagesExplore/imagesExploreAppModel.ts
Fixed the issue with images explore apply and search buttons initial disability.
=> Prevent  images explore apply and search buttons initial disability 

CHANGELOG.md, aim/web/ui/src/utils/app/manageSystemMetricColumns.ts
- Checked is system metrics exists in logs ?
- Updated CHANGELOG.md
=> [fix] Fix rendering issue in runs explorer page

aim/sdk/adapters/pytorch_lightning.py
Refactor `AimLogger` class for pytorch lightning to follow the guidelines for PL loggers and provide more flexibility for the users to derive and write their own custom loggers
=> PL adapter refactoring

CHANGELOG.md, aim/web/ui/src/pages/Metrics/components/Table/ManageColumnsPopover/ColumnItem/ColumnItem.scss, aim/web/ui/src/pages/Metrics/components/Table/ManageColumnsPopover/ColumnItem/ColumnItem.tsx, aim/web/ui/src/pages/Metrics/components/Table/ManageColumnsPopover/ManageColumnsPopover.tsx
Added focused, hovered and selected states styles
=> Tune manage columns items highlighting styles

aim/web/ui/src/components/GroupingPopover/GroupingPopover.tsx, aim/web/ui/src/components/TooltipContentPopover/TooltipContentPopover.tsx
- Fixed controlling state issue in `Autocomplete` component
=> Fix Autocomplete state issue in grouping popover

aim/web/api/runs/object_views.py, aim/web/api/runs/pydantic_models.py
Removed generic support for custom object views
=> Fix metaclass conflicts for pydantic models (py 3.6)

aim/sdk/adapters/pytorch_lightning.py
=> [fix] AimLogger save_dir AttributeError

CHANGELOG.md, aim/web/ui/src/pages/ImagesExplore/ImagesExplore.tsx, aim/web/ui/src/pages/ImagesExplore/components/SelectForm/SelectForm.tsx, aim/web/ui/src/pages/Metrics/Metrics.tsx, aim/web/ui/src/pages/Metrics/MetricsContainer.tsx, aim/web/ui/src/pages/Metrics/components/SelectForm/SelectForm.tsx, aim/web/ui/src/pages/Params/Params.tsx, aim/web/ui/src/pages/Params/ParamsContainer.tsx, aim/web/ui/src/pages/Params/components/SelectForm/SelectForm.tsx, aim/web/ui/src/pages/Runs/Runs.tsx, aim/web/ui/src/pages/Runs/RunsContainer.tsx, aim/web/ui/src/pages/Runs/components/SearchBar/SearchBar.tsx, aim/web/ui/src/pages/Scatters/Scatters.tsx, aim/web/ui/src/pages/Scatters/ScattersContainer.tsx, aim/web/ui/src/pages/Scatters/components/SelectForm/SelectForm.tsx, aim/web/ui/src/services/models/explorer/createAppModel.ts, aim/web/ui/src/services/models/imagesExplore/imagesExploreAppModel.ts, aim/web/ui/src/types/pages/imagesExplore/components/SelectForm/SelectForm.d.ts, aim/web/ui/src/types/pages/metrics/Metrics.d.ts, aim/web/ui/src/types/pages/metrics/components/SelectForm/SelectForm.d.ts, aim/web/ui/src/types/pages/params/Params.d.ts, aim/web/ui/src/types/pages/params/components/SelectForm/SelectForm.d.ts, aim/web/ui/src/types/pages/scatters/Scatters.d.ts, aim/web/ui/src/types/pages/scatters/components/SelectForm/SelectForm.d.ts, aim/web/ui/src/types/services/models/imagesExplore/imagesExploreAppModel.d.ts, aim/web/ui/src/types/services/models/metrics/metricsAppModel.d.ts, aim/web/ui/src/types/services/models/params/paramsAppModel.d.ts, aim/web/ui/src/types/services/models/scatter/scatterAppModel.d.ts, aim/web/ui/src/utils/app/getParamsSuggestions.ts
- Fixed select form search suggestions list
=> [fix] Fix rendering issue on Select form search suggestions list

CHANGELOG.md, aim/web/ui/src/components/CustomTable/Table.scss, aim/web/ui/src/components/CustomTable/TableColumn.tsx, aim/web/ui/src/pages/ImagesExplore/components/ImagesExploreTableGrid/ImagesExploreTableGrid.tsx, aim/web/ui/src/pages/Metrics/components/MetricsTableGrid/MetricsTableGrid.tsx, aim/web/ui/src/pages/Params/components/ParamsTableGrid/ParamsTableGrid.tsx, aim/web/ui/src/pages/RunDetail/RunDetail.scss, aim/web/ui/src/pages/RunDetail/RunSelectPopoverContent.tsx, aim/web/ui/src/services/models/imagesExplore/imagesExploreAppModel.ts
- Fixed `None` value rendering in table `Groups` column
- Add user select support for browser safari
=> [fix] None value not displayed in group column

CHANGELOG.md, aim/web/api/runs/object_api_utils.py, aim/web/api/runs/object_views.py, aim/web/ui/src/pages/RunDetail/PlotlyVisualizer/PlotlyVisualizer.tsx, aim/web/ui/src/services/models/runs/runTracesModel.ts, aim/web/ui/src/services/models/runs/util.ts
- Fix Plotly animation
- Add optimization for figure data loading
=> [fix] Plotly figures issue

docs/source/ui/pages/explorers.md
Added Params explore docs with topics
- Easily query any metrics and params
- Group runs by color, stroke, or chart
- Make the crossings easier with curve interpolation
- Learn patterns and colorations easier colored by the last dimension with a color indicator
=> [doc] Added params explore documentation

docs/source/ui/pages/run_management.md
- Added documentation for Runs Management on UI.
=> [doc] Add documentation for Runs Management on UI.

docs/source/ui/pages/run_management.md
Add run single page images for docs
=> Add run single page images for docs

aim/web/ui/src/config/analytics/analyticsKeysMap.ts, aim/web/ui/src/pages/TextExplorer/TextExplorer.tsx, aim/web/ui/src/services/api/textExplorer/textExplorerService.ts, aim/web/ui/src/services/models/textExplorer/textExplorerAppModel.ts, aim/web/ui/src/types/services/models/textExplorer/texteExplorerAppModel.d.ts
Add some methods for textAppModel 
Created api service for text explorer
Created initialization calls(get params, projects, sync urls) for text explorer
=> [feat] Add initialization methods to TextExplorer app model

.github/workflows/pull-request.yml, setup.py
This change configures all the extensions with third-party libs, shared objects and headers to build `aim` with.
=> Cython Bindings / Setup

docs/source/using/sagemaker_notebook_ui.md
- Change script url 
- Fix typos
=> [docs] Fix typos in SageMaker usage guide.

aim/web/api/runs/object_views.py, aim/web/ui/src/pages/TextExplorer/TextExplorer.tsx, aim/web/ui/src/pages/TextExplorer/components/SelectForm/SelectForm.scss, aim/web/ui/src/pages/TextExplorer/components/SelectForm/SelectForm.tsx, aim/web/ui/src/services/api/textExplorer/textExplorerService.ts, aim/web/ui/src/services/models/imagesExplore/imagesExploreAppModel.ts, aim/web/ui/src/services/models/textExplorer/textExplorerAppModel.ts, aim/web/ui/src/types/pages/imagesExplore/components/SelectForm/SelectForm.d.ts, aim/web/ui/src/types/pages/textsExplorer/components/SelectForm/SelectForm.d.ts, aim/web/ui/src/types/services/models/projects/projectsModel.d.ts, aim/web/ui/src/types/services/models/textExplorer/texteExplorerAppModel.d.ts
- added Text Explorer data processing/rendering parts
=> Add Text Explorer SelectForm component

aim/web/ui/src/pages/TextExplorer/TextExplorer.tsx, aim/web/ui/src/services/models/textExplorer/textExplorerAppModel.ts
- Added resize panel functionality
=> [feat] Add resizing functionality between two tables

aim/web/ui/src/components/SideBar/SideBar.tsx, aim/web/ui/src/components/kit/ExpressionAutoComplete/ExpressionAutoComplete.scss, aim/web/ui/src/config/enums/routesEnum.ts, aim/web/ui/src/pages/TextExplorer/TextExplorer.tsx, aim/web/ui/src/pages/TextExplorer/components/SelectForm/SelectForm.scss, aim/web/ui/src/pages/TextExplorer/components/SelectForm/SelectForm.tsx, aim/web/ui/src/routes/routes.tsx, aim/web/ui/src/services/models/textExplorer/textExplorerAppModel.ts, aim/web/ui/src/types/pages/textsExplorer/components/SelectForm/SelectForm.d.ts
- Added advanced options for select form
- Fix styles crush for ExpressionAutocomplete
=> [feat] Add advanced options for select form

aim/storage/containertreeview.pxd, aim/storage/containertreeview.py, aim/storage/inmemorytreeview.pxd, aim/storage/inmemorytreeview.py, aim/storage/prefixview.pxd, aim/storage/prefixview.py, aim/storage/rockscontainer.pyx, aim/storage/union.pyx, setup.py
- Minor typing fixes,
- Minor optimizations,
- Bindings for `TreeViews`,
- `ItemIterators` on top of `BaseIterators`,
- `PrefixView` refactor,
- Removing unnecessary implementations.
=> Cython Bindings / Tree View & Items Iterators

docs/source/ui/pages/bookmarks.md
Only grammar changes. Added space between sections for easy reading.
=> Edit UI bookmarks

aim/web/ui/src/pages/TextExplorer/TextExplorer.tsx, aim/web/ui/src/pages/TextExplorer/components/TextPanelGrid/TextPanelGrid.tsx, aim/web/ui/src/services/models/textExplorer/textExplorerAppModel.ts, aim/web/ui/src/types/services/models/textExplorer/texteExplorerAppModel.d.ts
- Added text panel table pin functionality
- fixed text panel table data rendering
=> [feat] Add text explorer table panel actions

aim/web/ui/src/config/analytics/analyticsKeysMap.ts, aim/web/ui/src/pages/TextExplorer/TextExplorer.scss, aim/web/ui/src/pages/TextExplorer/TextExplorer.tsx, aim/web/ui/src/services/models/textExplorer/textExplorerAppModel.ts
- Added RangePanel
- Connect to model.
=> [feat] Added range panel

CHANGELOG.md, aim/ext/notebook/notebook.py
There is a javascript syntax error in time of rendering iframe. Also added a link which will open the ui in a new browser tab.
=> [fix] Fix ui rendering issue on colab

aim/web/ui/src/pages/TextExplorer/TextExplorer.scss, aim/web/ui/src/pages/TextExplorer/TextExplorer.tsx, aim/web/ui/src/services/models/textExplorer/textExplorerAppModel.ts
- Added loading state and tune `Text Explorer`
- Tuned `Text Explorer` initial styles
=> [feat] Add loading state and tune text explorer

README.md
Previous example failed if one simply copy+pasted the code.
Verified that this one works.
=> Fix example in Quickstart.

aim/web/ui/src/pages/RunDetail/RunDetail.scss, aim/web/ui/src/pages/RunDetail/RunOverviewTab/RunOverviewTab.scss, aim/web/ui/src/pages/RunDetail/RunOverviewTab/components/GitInfoCard/index.tsx, aim/web/ui/src/pages/RunDetail/RunOverviewTab/components/RunOverviewSidebar/RunOverviewSidebar.scss
- fixed container padding issue in single run page tabs
=> [fix] Container padding issue in run single page tabs

aim/web/ui/src/pages/RunDetail/RunDetail.tsx
- fixed loading spinner position in single run page tabs
=> [fix] Loading spinner position in single run page tabs

CHANGELOG.md
wrong placement(under 3.7.0) for newly merged enhancement
=> [fix] changelog conflicts

CHANGELOG.md, aim/web/ui/src/components/MediaSet/MediaSet.scss, aim/web/ui/src/styles/abstracts/_variables.scss
- Change icon styles. it is visible despite background color.
=> Fix full view toggle icon styles

CHANGELOG.md
- Updated changelog for patch release
=> [fix] update changelog for patch release

CHANGELOG.md, aim/web/ui/src/pages/RunDetail/RunDetail.tsx, aim/web/ui/src/pages/RunDetail/TraceVisualizationContainer/TraceVisualizationContainer.tsx
- Added missing names for dynamically imported files in single run page
=> [fix] Add missing names for dynamically imported files in single run page

CHANGELOG.md, aim/web/ui/src/pages/RunDetail/TraceVisualizationContainer/RangePanel.tsx, aim/web/ui/src/services/models/runs/runTracesModel.ts
Fixed `RangePanel` density input validation in a run single page.
=> Range panel density input validation max and min value calculation

aim/sdk/adapters/hugging_face.py
Make HF adapter underlying run reopenable, and provide top level closing interface
=> [feat] Reoepanble HF `AimCallback`

CHANGELOG.md, aim/web/ui/src/pages/RunDetail/hooks/useRunMetricsBatch.tsx
- Added request aborting functionality on unmount single run page tabs
=> [feat] Add request aborting functionality in single run page tabs

CHANGELOG.md, aim/storage/structured/sql_engine/utils.py
Manually commit changes when `autocommit` is set to `True`
=> [fix] Run structured properties not being set properly

CHANGELOG.md, aim/ext/utils.py
Added more checks when collecting git info. 
In case if one command fails its more likely others will fail too. In such case no data is collected and the process is stopped.
=> [fix] git info collection

aim/web/api/__init__.py, aim/web/api/experiments/views.py, aim/web/api/runs/object_views.py, aim/web/api/runs/views.py, tests/api/test_structured_data_api.py
partially reverts [60b99dc](https://github.com/aimhubio/aim/commit/60b99dc8a509f989ed9fd819454c87ac5d2b0257)
=> [fix] revert implementation of error handling

CONTRIBUTING.md
- Add semver link
- Add release notes link
- Add component name param to section of Adding new component code blocks
- Fix some typos
=> [doc] Add some links and fix some typos

aim/web/api/__init__.py, aim/web/api/experiments/views.py, aim/web/api/runs/object_views.py, aim/web/api/runs/utils.py, aim/web/api/runs/views.py, aim/web/ui/src/components/NotificationContainer/NotificationContainer.tsx, aim/web/ui/src/services/api/api.ts, aim/web/ui/src/utils/app/exceptionHandler.ts, tests/api/test_structured_data_api.py
- Separated error message unification into a new branch
- Changed `exception handler` method to work with new error response structure
=> [feat] error message unification

aim/web/middlewares/profiler/profiler.py, docs/source/index.rst, docs/source/understanding/running_aim_with_profiling.md
- hangs on `get-batch`
- not working on `<4.0.0`
=> [fix] profiler issues

aim/web/ui/src/components/CustomTable/TableColumn.tsx
Fix column values set sorting for color scale
=> [fix] Change sorting of column values set

docs/source/ui/pages/run_management.md
- Added overview tab documentation
- Updated single run tabs images in CDN
=> [doc] Add overview tab documentation in a run single page

README.md
Moved cloud-storage related items to "In Progress"
=> [doc] Update roadmap

CHANGELOG.md, aim/web/ui/src/services/models/explorer/createAppModel.ts
Increased live update requests delay to `7000` for all explorers
=> [fix] Increase live update requests delay to prevent performance issues

docs/source/ui/pages/run_management.md
Add documentation for the info message in the slider of the Range Panel which has only 1 value tracked
=> [docs] Added range panel info message docs

CHANGELOG.md, aim/web/ui/src/components/ExportPreview/config.ts, aim/web/ui/src/components/HighPlot/HighPlot.scss, aim/web/ui/src/components/LineChart/LineChart.scss, aim/web/ui/src/components/ScatterPlot/styles.scss, aim/web/ui/src/utils/d3/drawAxes.ts, aim/web/ui/src/utils/d3/drawParallelAxes.ts, docs/source/ui/pages/run_management.md
- add a limit to Highplot axis ticks count
- tune charts minimum ticks count and minimum dimensions
=> [fix] Highplot axis ticks overlapping

CHANGELOG.md, aim/web/ui/src/components/ChartPanel/ChartGrid/ChartGrid.d.ts, aim/web/ui/src/components/ChartPanel/ChartGrid/ChartGrid.tsx, aim/web/ui/src/components/ChartPanel/ChartPanel.tsx, aim/web/ui/src/components/HighPlot/HighPlot.tsx, aim/web/ui/src/components/LineChart/LineChart.tsx, aim/web/ui/src/components/ScatterPlot/ScatterPlot.tsx, aim/web/ui/src/components/ScatterPlot/types.d.ts, aim/web/ui/src/components/Table/DeleteModal.tsx, aim/web/ui/src/pages/RunDetail/RunSelectPopoverContent.tsx, aim/web/ui/src/types/components/HighPlot/HighPlot.d.ts, aim/web/ui/src/types/components/LineChart/LineChart.d.ts
Fix updating of the chart height when resizing mode changed
=> [fix] Update chart height when resizing mode changed

CHANGELOG.md, aim/sdk/adapters/hugging_face.py
Added also step/epoch values to tracked metrics and process rank 0 checks
=> [fix] HF callback context capturing 

CHANGELOG.md, aim/web/ui/src/utils/app/getGroupingPersistIndex.ts
Fix:
- replace the hardcoded color variable with dynamic
=> [fix] Fix affecting stroke types after changing color persistence

aim/web/ui/package-lock.json
Upgrade the following packages to the versions which resolve security issues:
- `minimist`
- `nanoid`
- `moment`
- `async`
- `cross-fetch`
=> [chore] Upgrade UI packages with security issues

aim/web/ui/src/services/models/explorer/createAppModel.ts
Fix:
- After resolving the merge conflict in [PR](https://github.com/aimhubio/aim/pull/1726) have removed part of the code by mistake
=> [fix] Fix mistake after resolving the merge conflict

aim/web/api/views.py, requirements.dev.txt, setup.py
Updated `setup.py` to include README.md contents as a long description and provide long description content type.
Updated `requirements.dev.txt` to set minimum required version of `twine` and `wheel` for Github-style markdown support.
=> [feat] Add description to aim package PyPI project

CHANGELOG.md, aim/web/ui/public/index.html, aim/web/ui/src/App.scss, aim/web/ui/src/App.tsx, aim/web/ui/src/components/AutocompleteInput/AutocompleteInput.tsx, aim/web/ui/src/pages/RunDetail/RunLogsTab/RunLogsTab.tsx
- Added pre-loader animation to Aim UI
- Pre-loading and caching necessary resources for UI.
=> [feat] Pre-loading and caching necessary resources, add pre-loader animation to Aim UI

aim/web/ui/src/components/AutocompleteInput/AutocompleteInput.tsx, aim/web/ui/src/pages/RunDetail/RunLogsTab/RunLogsTab.scss, aim/web/ui/src/pages/RunDetail/RunLogsTab/RunLogsTab.tsx
- Fixed value updating frequency of Autocomplete input
=> [fix] Fix Autocomplete input value updating frequency

CHANGELOG.md, aim/web/ui/src/components/AutocompleteInput/AutocompleteInput.tsx, aim/web/ui/src/pages/RunDetail/RunOverviewTab/components/ParamsCard/RunOverviewTabParamsCard.tsx, aim/web/ui/src/utils/app/onSelectRunQueryChange.ts
- Fix run overview tab params card error in the single run page
- Fix Autocomplete setting previous state issue.
=> [fix] Fix run overview tab params card error

CHANGELOG.md, aim/web/ui/src/services/models/explorer/createAppModel.ts, aim/web/ui/src/services/models/imagesExplore/imagesExploreAppModel.ts
=> [fix] Prevent drops options duplication

CHANGELOG.md, aim/web/ui/src/services/live-update/Worker.ts, aim/web/ui/src/services/models/explorer/createAppModel.ts, aim/web/ui/src/utils/app/setDefaultAppConfigData.ts
- Added the next requests scheduler after the last one will be handled (decoded, parsed)
- Increased live update delay to 10000
- Added a code block for backward compatibility on changing live update delay
=> [fix] Fix issue with live update requests scheduler

CHANGELOG.md, aim/web/ui/src/pages/RunDetail/RunLogsTab/RunLogsTab.scss, aim/web/ui/src/pages/RunDetail/RunLogsTab/RunLogsTab.tsx
=> [fix] Adjust SRP logs rows height

CHANGELOG.md, aim/web/ui/src/components/Table/Table.tsx, aim/web/ui/src/pages/Metrics/Metrics.scss, aim/web/ui/src/pages/Metrics/components/MetricsTableGrid/MetricsTableGrid.tsx, aim/web/ui/src/pages/Scatters/Scatters.scss, aim/web/ui/src/services/models/explorer/createAppModel.ts, aim/web/ui/src/types/services/models/metrics/metricsAppModel.d.ts, aim/web/ui/src/utils/aggregateGroupData.ts
- Display std. dev/err aggregated values in the table
- Dynamically update row data during chart hovering
=> [feat] Display std. dev/err aggregated values in the table

aim/web/ui/package-lock.json, aim/web/ui/src/App.tsx, aim/web/ui/src/components/ChartPanel/PopoverContent/PopoverContent.tsx, aim/web/ui/src/components/MediaList/ImageBox.tsx, aim/web/ui/src/components/ProjectWrapper/ProjectWrapper.tsx, aim/web/ui/src/config/pageTitles/pageTitles.ts, aim/web/ui/src/pages/Bookmarks/Bookmarks.tsx, aim/web/ui/src/pages/ImagesExplore/ImagesExplore.tsx, aim/web/ui/src/pages/ImagesExplore/components/ImagesExploreTableGrid/ImagesExploreTableGrid.tsx, aim/web/ui/src/pages/Metrics/Metrics.tsx, aim/web/ui/src/pages/Metrics/components/MetricsTableGrid/MetricsTableGrid.tsx, aim/web/ui/src/pages/PageWrapper.tsx, aim/web/ui/src/pages/Params/Params.tsx, aim/web/ui/src/pages/Params/components/ParamsTableGrid/ParamsTableGrid.tsx, aim/web/ui/src/pages/RunDetail/RunDetail.tsx, aim/web/ui/src/pages/Runs/components/RunsBar/RunsBar.tsx, aim/web/ui/src/routes/routes.tsx, aim/web/ui/src/services/models/explorer/createAppModel.ts, aim/web/ui/src/services/models/imagesExplore/imagesExploreAppModel.ts, aim/web/ui/src/services/models/runs/util.ts, aim/web/ui/src/types/services/models/imagesExplore/imagesExploreAppModel.d.ts, aim/web/ui/src/types/services/models/metrics/metricsAppModel.d.ts, aim/web/ui/src/utils/app/getGroupingSelectOptions.ts, aim/web/ui/src/utils/app/getTooltipData.ts
- Add run props to grouping select options for all explorers and remove hardcoded run props
- Improve document page titles
=> [feat] Improve groupings popovers content

CHANGELOG.md, aim/ext/resource/tracker.py, aim/sdk/run.py
- Isolated run tracking methods, to be able to track when run has no references
=> [fix] Log capturing crashes during run garbage collection

aim/web/ui/src/services/models/explorer/createAppModel.ts, aim/web/ui/src/services/models/imagesExplore/imagesExploreAppModel.ts
Remove high-level params from tables of explorers
=> [fix] Remove high-level params from table

CHANGELOG.md, aim/web/ui/src/components/AutocompleteInput/ AutocompleteInput.d.ts, aim/web/ui/src/components/AutocompleteInput/AutocompleteInput.scss, aim/web/ui/src/components/AutocompleteInput/AutocompleteInput.tsx, aim/web/ui/src/pages/ImagesExplore/components/SelectForm/SelectForm.tsx, aim/web/ui/src/pages/Metrics/components/SelectForm/SelectForm.tsx, aim/web/ui/src/pages/Params/components/SelectForm/SelectForm.tsx, aim/web/ui/src/pages/Runs/components/SearchBar/SearchBar.tsx, aim/web/ui/src/pages/Scatters/components/SelectForm/SelectForm.tsx, aim/web/ui/src/services/models/explorer/createAppModel.ts, aim/web/ui/src/services/models/imagesExplore/imagesExploreAppModel.ts
- Fixed search input typing latency issue
=> [fix] Resolve typing latency issue in the query search input

CHANGELOG.md, aim/web/ui/src/components/Table/ArchiveModal.tsx, aim/web/ui/src/components/Table/DeleteModal.tsx, aim/web/ui/src/components/Table/Table.scss, aim/web/ui/src/components/kit/Modal/Modal.d.ts, aim/web/ui/src/components/kit/Modal/Modal.tsx
Adjust the content overflowing of the Delete and the Archive modals.
=> [fix] Adjust the content overflowing of the Delete and the Archive modals

aim/web/ui/src/App.tsx, aim/web/ui/src/modules/BaseExplorerCore/pipeline/adapter/index.ts, aim/web/ui/src/modules/BaseExplorerCore/pipeline/index.ts, aim/web/ui/src/modules/BaseExplorerCore/pipeline/query/index.ts, aim/web/ui/src/pages/BaseExplorer/index.tsx
- Beautified Query phase, add possibility to pass status changes listener callback
- Promisified adapter, add statusCallback into adapter
- Add E2E pipeline with statusChanges
=> [refactor] Cleanup pipeline phases codebase and add status changes callbacks

CHANGELOG.md, aim/cli/runs/commands.py, aim/cli/runs/utils.py, docs/source/refs/cli.md, docs/source/using/manage_runs.md
This PR is aimed at resolving issue #1690. Currently, this PR supports cloud storage backups with the aim runs to an AWS s3 bucket.
=> [feat] Add cloud storage backups for aim runs to aws s3

.github/workflows/pull-request.yml, aim/cli/runs/commands.py, aim/cli/runs/utils.py
Add sanity checks for whole `aim` package, not only for some subdirectories
Also fixed:
- flake8 checks
- remove redundant code blocks
=> [fix] Remove `boto3` dependency 

CHANGELOG.md, aim/web/ui/src/config/dates/dates.ts, aim/web/ui/src/pages/RunDetail/RunDetail.scss, aim/web/ui/src/pages/RunDetail/RunDetail.tsx, aim/web/ui/src/pages/RunDetail/RunSelectPopoverContent.tsx
Add the date and duration of the run in the run page header
=> [feat] Add the date and duration of the run in the run page header

CHANGELOG.md, aim/web/api/runs/utils.py, aim/web/ui/src/pages/RunDetail/RunLogsTab/RunLogsTab.scss, aim/web/ui/src/pages/RunDetail/RunLogsTab/RunLogsTab.tsx, aim/web/ui/src/services/models/runs/runDetailAppModel.ts
- Add loader to the top of the logs box on the run page
- Change the limit of the logs count per request to 500
=> [feat] Add loader the top of the logs box

CHANGELOG.md, aim/web/ui/src/components/AutocompleteInput/AutocompleteInput.scss, aim/web/ui/src/components/CodeBlock/CodeBlock.scss, aim/web/ui/src/components/CustomTable/Table.scss, aim/web/ui/src/config/dates/dates.ts, aim/web/ui/src/pages/RunDetail/RunDetail.scss, aim/web/ui/src/pages/RunDetail/RunLogsTab/RunLogsTab.scss, aim/web/ui/src/pages/RunDetail/RunSelectPopoverContent.tsx, aim/web/ui/src/styles/abstracts/_mixins.scss
- Remove the "arrows" icon
- Set monospace font
- Increase font sizes
=> [fix] Adjust runs navigation dropdown

aim/web/ui/src/components/LineChart/LineChart.scss, aim/web/ui/src/components/ProgressBar/ProgressBar.scss, aim/web/ui/src/pages/RunDetail/RunLogsTab/RunLogsTab.scss, aim/web/ui/src/pages/RunDetail/RunLogsTab/RunLogsTab.tsx, aim/web/ui/src/services/models/explorer/createAppModel.ts, aim/web/ui/src/services/models/imagesExplore/imagesExploreAppModel.ts, aim/web/ui/src/types/components/Table/Table.d.ts, aim/web/ui/src/utils/d3/drawLines.ts
The table data doesn’t update, depending on the request status
=> [fix] Fix issue with updating table data

CHANGELOG.md, aim/web/ui/package.json
- Add prosemirror-tables missing package.
=> [fix] Resolve Notes tab loading issue in Run page

CHANGELOG.md, aim/cli/convert/processors/tensorboard.py
=> [fix] Left typo on tb audios conversion 

aim/sdk/sequence.py, aim/sdk/sequences/metric.py
Need to check the impact on performance_tests
=> [fix] Delay Sequence data and series_tree members creation

CHANGELOG.md, aim/cli/convert/processors/tensorboard.py
=> [fix] Tensorboard convert while converting tensor

aim/web/ui/src/components/AxesPropsPopover/AxesPropsPopover.tsx, docs/source/ui/pages/explorers.md
- Added documentation for manual axes range selection
- Removed documentation for steps density selection
=> [docs] Add docs for the axes properties popover

CHANGELOG.md, aim/web/ui/src/components/kit/index.ts, aim/web/ui/src/pages/RunDetail/RunDetail.scss, aim/web/ui/src/pages/RunDetail/RunDetailMetricsAndSystemTab.tsx, aim/web/ui/src/pages/RunDetail/RunMetricCard.tsx, aim/web/ui/src/pages/RunDetail/RunOverviewTab/RunOverviewTab.tsx, aim/web/ui/src/pages/RunDetail/hooks/useRunMetricsBatch.tsx, aim/web/ui/src/pages/RunDetail/types.d.ts, aim/web/ui/src/services/models/runs/runDetailAppModel.ts
Fetching only those metrics which are visible in the viewport.
Implemented with `Intersection Observer`.
=> [feat] Apply lazy loading on metrics in Run Page

aim/web/ui/src/pages/RunDetail/RunDetail.scss, aim/web/ui/src/pages/RunDetail/RunMetricCard.tsx
Moved pin button to top right corner of the metric card and added outlined styles to the button.
=> [feat] Adjust styles for metric card pin button

aim/web/ui/src/hooks/useDepthMap.tsx, aim/web/ui/src/modules/BaseExplorer/components/BoxVirtualizer/BoxVirtualizer.d.ts, aim/web/ui/src/modules/BaseExplorer/components/BoxVirtualizer/BoxVirtualizer.tsx, aim/web/ui/src/modules/BaseExplorer/components/BoxWrapper/BoxWrapper.d.ts, aim/web/ui/src/modules/BaseExplorer/components/BoxWrapper/BoxWrapper.tsx, aim/web/ui/src/modules/BaseExplorer/components/Visualizer/Visualizer.tsx
- Add `sync` property to the `useDepthMap` custom hook
- Fix resetting depth map values on box config change
=> [feat] Add the ability to sync sliders of stacked boxes

aim/web/ui/src/pages/BaseExplorer/index.tsx
- Set the min-height and min-width to 200
- Set default height and width to 400
=> [feat] Adjust default box configs

CHANGELOG.md, aim/web/ui/src/services/live-update/Worker.ts
Added a retry for the failed network requests.
=> [fix] Add retry logic for failed network requests in live update

CHANGELOG.md, aim/web/ui/src/components/CopyToClipBoard/CopyToClipBoard.tsx, aim/web/ui/src/components/IllustrationBlock/IllustrationBlock.scss, aim/web/ui/src/components/IllustrationBlock/IllustrationBlock.tsx, aim/web/ui/src/hooks/useCopy/useCopy.ts, aim/web/ui/src/services/models/explorer/createAppModel.ts, aim/web/ui/src/services/models/imagesExplore/imagesExploreAppModel.ts, aim/web/ui/src/utils/app/onSearchQueryCopy.ts, aim/web/ui/src/utils/onCopyToClipBoard.ts
- Fix CodeBlock copying functionality
- Tuned `IllustrationBlock` styles
- Added `useCopy` hooks
- Added `onCopyToClipBoard` helper function
=> [fix] Fix code block content and query copying functionality

aim/web/ui/src/config/monacoConfig/monacoConfig.ts, aim/web/ui/src/modules/BaseExplorer/components/BoxFullViewPopover/BoxFullViewPopover.tsx, aim/web/ui/src/services/models/explorer/index.ts
- Need to check `run` existence before using it
- Remove `Figures` from `appnameEnum` to avoid the compile time errors
=> [fix] Fix figures explorer crashing issue

docs/source/using/search.md
- add usage of `created_at`, `finalized_at`, `duration`, `metrics` properties
=> [doc] Improve documentation for run search

aim/web/ui/src/modules/BaseExplorer/components/Grouping/GroupingPopover/GroupingPopover.scss, aim/web/ui/src/modules/BaseExplorer/components/Grouping/GroupingPopover/GroupingPopover.tsx, aim/web/ui/src/modules/BaseExplorerCore/pipeline/grouping/getGroupValues.ts, aim/web/ui/src/pages/BaseExplorer/index.tsx
- Fix issue with ordering group items
- Add toggle switcher for grouping order to grouping popover
=> [feat] Add ability to change group values order

CHANGELOG.md, aim/web/ui/src/components/ExportPreview/ExportPreview.tsx, aim/web/ui/src/components/kit/Input/Input.tsx
- fix input validation issue in `InputWrapper` component
=> [fix] Fix chart exporting issue

CHANGELOG.md, aim/cli/convert/commands.py, aim/cli/convert/processors/__init__.py, aim/cli/convert/processors/wandb.py, docs/source/quick_start/convert_data.md, examples/requirements.txt
Added wandb to aim log converter.
=> [feat] Add wandb to aim log converter

CHANGELOG.md, aim/web/ui/src/App.scss, aim/web/ui/src/components/AttachedTagsList/AttachedTagsList.scss, aim/web/ui/src/components/AttachedTagsList/AttachedTagsList.tsx, aim/web/ui/src/components/SelectTag/SelectTag.scss, aim/web/ui/src/modules/BaseExplorer/components/BoxFullViewPopover/BoxFullViewPopover.tsx, aim/web/ui/src/pages/RunDetail/RunOverviewTab/components/RunOverviewSidebar/RunOverviewSidebar.tsx, aim/web/ui/src/types/components/AttachedTagsList/AttachedTagsList.d.ts
- Add the ability to edit tags from the Run Page overview sidebar
- Apply optimistic updates on tags edit functionality
- Tune styles for the edit button in `<AttachedTagsList />` component
=> [feat] Add the ability to edit tags from the Run Page

CHANGELOG.md, aim/web/ui/src/components/CustomTable/Table.scss, aim/web/ui/src/components/CustomTable/Table.tsx, aim/web/ui/src/components/CustomTable/TableCell.tsx, aim/web/ui/src/components/CustomTable/TableColumn.tsx
- Fixed the color badge when there is no grouping applied
- Always showing the color badge
=> [fix] Adjust the visibility of the color of the run in the table

docs/source/quick_start/convert_data.md
Added Weights & Biases link on converters list
=> [fix] Add wandb section link on converters page

CHANGELOG.md, aim/sdk/adapters/pytorch_lightning.py
Change imports in `aim.sdk.adaptors.pytorch_lightning` to handle deprecations in PL v1.7.
Fixes issue #2105
=> [fix] Deprecation issues with PL v1.7

aim/web/ui/src/utils/app/getCompatibleSelectConfig.ts
Add checker for selected options compatibility checking method
=> [fix] Add checker for selected options compatibility checking method

aim/web/ui/src/components/kit/ListItem/Index.ts, aim/web/ui/src/components/kit/ListItem/ListItem.d.ts, aim/web/ui/src/components/kit/ListItem/ListItem.tsx, aim/web/ui/src/pages/Home/components/HomeLeft/HomeLeft.scss, aim/web/ui/src/pages/Home/components/HomeLeft/HomeLeft.tsx, aim/web/ui/src/pages/Home/components/HomeLeft/QuickLinks/QuickLinks.scss, aim/web/ui/src/pages/Home/components/HomeLeft/QuickLinks/QuickLinks.tsx
- Added quick links to explore runs
=> [feat] Add quick links to explore runs

aim/web/api/dashboards/pydantic_models.py, aim/web/api/dashboards/serializers.py, aim/web/ui/src/components/kit/DataList/DataList.tsx, aim/web/ui/src/components/kit/DataList/SearchBar/SearchBar.tsx, aim/web/ui/src/components/kit/DataList/SearchBar/types.d.ts, aim/web/ui/src/modules/core/api/dashboardsApi/index.ts, aim/web/ui/src/modules/core/api/dashboardsApi/types.ts, aim/web/ui/src/pages/Bookmarks/components/BookmarkCard/BookmarkCard.tsx, aim/web/ui/src/pages/Home/Home.tsx, aim/web/ui/src/pages/Home/components/ExperimentsCard/ExperimentsCard.scss, aim/web/ui/src/pages/Home/components/ExperimentsCard/ExperimentsCard.tsx, aim/web/ui/src/pages/Home/components/ExperimentsCard/useExperimentsCard.tsx, aim/web/ui/src/pages/Home/components/HomeLeft/HomeBookmarks/HomeBookmarks.scss, aim/web/ui/src/pages/Home/components/HomeLeft/HomeBookmarks/HomeBookmarks.tsx, aim/web/ui/src/pages/Home/components/HomeLeft/HomeBookmarks/HomeBookmarksStore.ts, aim/web/ui/src/pages/Home/components/HomeLeft/HomeBookmarks/useHomeBookmarks.tsx, aim/web/ui/src/pages/Home/components/HomeLeft/HomeLeft.scss, aim/web/ui/src/pages/Home/components/HomeLeft/HomeLeft.tsx
- Display `bookmarks list` in the `Home` page
=> [feat] Display bookmarks list

docker/Dockerfile
Initializing aim repo inside docker image in order to not fail during docker container start.
=> [fix]Resolved failure during docker container start

aim/web/ui/src/components/kit/DataList/DataList.d.ts, aim/web/ui/src/components/kit/DataList/DataList.scss, aim/web/ui/src/components/kit/DataList/DataList.tsx, aim/web/ui/src/components/kit/DataList/SearchBar/SearchBar.tsx, aim/web/ui/src/components/kit/DataList/SearchBar/SearchInput/index.tsx, aim/web/ui/src/components/kit/DataList/SearchBar/types.d.ts, aim/web/ui/src/pages/Home/Home.scss, aim/web/ui/src/pages/Home/components/HomeLeft/ExperimentsCard/ExperimentsCard.scss, aim/web/ui/src/pages/Home/components/HomeLeft/ExperimentsCard/ExperimentsCard.tsx, aim/web/ui/src/pages/Home/components/HomeLeft/ExperimentsCard/useExperimentsCard.tsx, aim/web/ui/src/pages/Home/components/HomeLeft/HomeLeft.scss, aim/web/ui/src/pages/Home/components/HomeLeft/QuickLinks/QuickLinks.scss, aim/web/ui/src/pages/Home/components/HomeLeft/TagsCard/TagsCard.scss, aim/web/ui/src/pages/Home/components/HomeLeft/TagsCard/TagsCard.tsx, aim/web/ui/src/pages/Home/components/HomeLeft/TagsCard/useTagsCard.tsx, aim/web/ui/src/pages/Home/components/HomeRight/GuideDocs/GuideDocs.tsx, aim/web/ui/src/pages/Home/components/HomeRight/ReleaseNotes/ReleaseNotes.tsx, aim/web/ui/src/styles/abstracts/_variables.scss
Tuned Experiments and Tags table style
=> [feat] Change the experiments and tags table style on the dashboard page

aim/web/ui/src/pages/Home/components/HomeLeft/DashboardBookmarks/DashboardBookmarks.scss, aim/web/ui/src/pages/Home/components/HomeLeft/DashboardBookmarks/DashboardBookmarks.tsx, aim/web/ui/src/pages/Home/components/HomeLeft/DashboardBookmarks/DashboardBookmarksStore.ts, aim/web/ui/src/pages/Home/components/HomeLeft/DashboardBookmarks/useDashboardBookmarks.tsx, aim/web/ui/src/pages/Home/components/HomeLeft/HomeLeft.scss, aim/web/ui/src/pages/Home/components/HomeLeft/HomeLeft.tsx, aim/web/ui/src/pages/Home/components/HomeLeft/TagsCard/TagsCard.scss
Changed bookmarks style on the Dashboard page
=> [feat] Change bookmarks style on the Dashboard page

aim/web/ui/src/components/StatisticsBar/StatisticsBar.scss, aim/web/ui/src/components/StatisticsBar/StatisticsBar.tsx, aim/web/ui/src/components/StatisticsCard/StatisticsCard.d.ts, aim/web/ui/src/components/StatisticsCard/StatisticsCard.scss, aim/web/ui/src/components/StatisticsCard/StatisticsCard.tsx, aim/web/ui/src/pages/Home/components/ProjectStatistics/ProjectStatistics.d.ts, aim/web/ui/src/pages/Home/components/ProjectStatistics/ProjectStatistics.tsx, aim/web/ui/src/styles/abstracts/_variables.scss
- Added links to corresponding explorers on statistics cards on the Dashboard page
- Added highlighting on cards hover
=> [feat] Add ability to navigate to existing explorers with statistic cards

aim/web/ui/src/components/HeatMap/HeatMapStyle.scss, aim/web/ui/src/pages/Home/components/ExploreSection/DashboardBookmarks/DashboardBookmarks.tsx, aim/web/ui/src/pages/Home/components/ExploreSection/ExploreSection.scss, aim/web/ui/src/pages/Home/components/ExploreSection/TagsCard/TagsCard.scss, aim/web/ui/src/pages/Home/components/ExploreSection/TagsCard/TagsCard.tsx, aim/web/ui/src/pages/Home/components/ProjectContributions/ProjectContributions.scss
Provide nav link to tag page in case of empty data
=> [feat] Display nav link to tag page in case of empty data

aim/web/ui/src/modules/core/utils/createResource.ts, aim/web/ui/src/pages/Home/components/ActiveRunsTable/ActiveRunsStore.ts, aim/web/ui/src/pages/Home/components/ActiveRunsTable/useActiveRunsTable.tsx, aim/web/ui/src/pages/Home/components/ContributionsFeed/ContributionsFeedStore.ts, aim/web/ui/src/pages/Home/components/ContributionsFeed/useContributionsFeed.ts, aim/web/ui/src/pages/Home/components/ExploreSection/DashboardBookmarks/DashboardBookmarksStore.ts, aim/web/ui/src/pages/Home/components/ExploreSection/DashboardBookmarks/useDashboardBookmarks.tsx, aim/web/ui/src/pages/Home/components/ExploreSection/ExperimentsCard/ExperimentsStore.ts, aim/web/ui/src/pages/Home/components/ExploreSection/ExperimentsCard/useExperimentsCard.tsx, aim/web/ui/src/pages/Home/components/ExploreSection/TagsCard/TagsStore.ts, aim/web/ui/src/pages/Home/components/ExploreSection/TagsCard/useTagsCard.tsx, aim/web/ui/src/pages/Home/components/HomeRight/ReleaseNotes/ReleasesStore.ts, aim/web/ui/src/pages/Home/components/ProjectContributions/ProjectContributionsStore.ts, aim/web/ui/src/pages/Home/components/ProjectContributions/useProjectContributions.tsx, aim/web/ui/src/pages/Home/components/ProjectStatistics/ProjectStatisticsStore.ts, aim/web/ui/src/pages/Home/components/ProjectStatistics/useProjectStatistics.tsx
Fixed state destroying issue in the Dashboard page
=> [fix] Fix state destroying issue in the Dashboard page

aim/web/ui/src/modules/core/api/releaseNotesApi/index.ts, aim/web/ui/src/pages/Dashboard/components/ContributionsFeed/useContributionsFeed.ts, aim/web/ui/src/services/NetworkService/index.ts
Add missing timezone property in the request headers
=> [fix] Add timezone to request headers

CHANGELOG.md, aim/web/ui/package-lock.json, aim/web/ui/src/components/TooltipContentPopover/TooltipContentPopover.scss, aim/web/ui/src/components/TooltipContentPopover/TooltipContentPopover.tsx, aim/web/ui/src/pages/RunDetail/RunLogsTab/LogRow.tsx, aim/web/ui/src/utils/formatAnsiToHtml.ts, aim/web/ui/src/utils/saveRecentSearches.ts
- Implement ANSI to HTML formatting method for color formatting in the logs tab
- Tune the size of the option in the tooltip content popover
=> [feat] Implement the color formatting in the logs tab

aim/web/ui/src/components/kit_v2/Button/Button.d.ts, aim/web/ui/src/components/kit_v2/Button/Button.tsx, aim/web/ui/src/components/kit_v2/IconButton/IconButton.d.ts, aim/web/ui/src/components/kit_v2/IconButton/IconButton.test.tsx, aim/web/ui/src/components/kit_v2/IconButton/IconButton.tsx, aim/web/ui/src/components/kit_v2/IconButton/__snapshots__/IconButton.test.tsx.snap, aim/web/ui/src/components/kit_v2/IconButton/index.ts, aim/web/ui/src/components/kit_v2/utils/getButtonStyles.ts, aim/web/ui/src/stories/IconButton.stories.tsx
Add IconButton component for ui kit v2
=> [feat] Create IconButton component

CHANGELOG.md, aim/web/ui/src/components/AttachedTagsList/AttachedTagsList.tsx, aim/web/ui/src/components/ChartPanel/ChartPopover/ChartPopover.tsx, aim/web/ui/src/components/ImageFullViewPopover/ImageFullViewPopover.tsx, aim/web/ui/src/components/MediaPanel/MediaPanel.tsx, aim/web/ui/src/components/TooltipContentPopover/TooltipContentPopover.tsx, aim/web/ui/src/config/illustrationConfig/illustrationConfig.tsx, aim/web/ui/src/modules/BaseExplorer/components/QueryForm/QueryForm.tsx, aim/web/ui/src/modules/BaseExplorer/components/Visualizations/Visualizations.tsx, aim/web/ui/src/modules/core/BaseError.ts, aim/web/ui/src/modules/core/engine/pipeline/index.ts, aim/web/ui/src/modules/core/engine/pipeline/state.ts, aim/web/ui/src/modules/core/engine/types.ts, aim/web/ui/src/modules/core/pipeline/PipelineError.ts, aim/web/ui/src/modules/core/pipeline/adapter/AdapterError.ts, aim/web/ui/src/modules/core/pipeline/adapter/index.ts, aim/web/ui/src/modules/core/pipeline/grouping/GroupingError.ts, aim/web/ui/src/modules/core/pipeline/grouping/index.ts, aim/web/ui/src/modules/core/pipeline/index.ts, aim/web/ui/src/modules/core/pipeline/query/QueryError.ts, aim/web/ui/src/modules/core/pipeline/query/index.ts, aim/web/ui/src/modules/core/utils/getQueryStringFromSelect.ts, aim/web/ui/src/pages/Dashboard/components/ProjectStatistics/useProjectStatistics.tsx, aim/web/ui/src/pages/Runs/RunsContainer.tsx, aim/web/ui/src/services/models/imagesExplore/imagesExploreAppModel.ts, aim/web/ui/src/types/components/NotificationContainer/NotificationContainer.d.ts, aim/web/ui/src/utils/app/getQueryStringFromSelect.ts, aim/web/ui/src/utils/removeSyntaxErrBrackets.ts
- add syntax error state on pipeline engine
- add syntax error highlighter using pipeline error state
- remove redundant `and ()` from the query, if there are no selected form data
=> [feat] Add the ability to highlight syntax error on query form

aim/web/ui/src/components/kit_v2/Button/Button.d.ts, aim/web/ui/src/components/kit_v2/Button/Button.tsx, aim/web/ui/src/components/kit_v2/Button/buttonConfig.ts, aim/web/ui/src/components/kit_v2/IconButton/IconButton.tsx, aim/web/ui/src/components/kit_v2/utils/getButtonStyles.ts
Add a horizontal spacing property for the Button component
=> [refactor] Refactor `Button` component spacing

aim/web/ui/src/components/kit_v2/ListItem/ListItem.d.ts, aim/web/ui/src/components/kit_v2/ListItem/ListItem.tsx, aim/web/ui/src/components/kit_v2/ListItem/index.ts, aim/web/ui/src/stories/ListItem.stories.tsx
Add `ListItem` component for ui kit v2
=> [feat] Add `ListItem` component

CHANGELOG.md, aim/web/ui/src/pages/Metrics/components/Table/ManageColumnsPopover/ColumnItem/ColumnItem.scss, aim/web/ui/src/pages/Metrics/components/Table/ManageColumnsPopover/ColumnItem/ColumnItem.tsx, aim/web/ui/src/pages/Metrics/components/Table/ManageColumnsPopover/ManageColumnsPopover.tsx
Change the icon color contrast of the manage columns popover
=> [feat] Change the icon color contrast of the manage columns popover

aim/web/ui/package-lock.json, aim/web/ui/package.json
Added the immer module to the dependency list
=> [feat] Added the immer module to the dependency list

CHANGELOG.md, aim/web/ui/package-lock.json, aim/web/ui/package.json, aim/web/ui/src/modules/BaseExplorer/components/Controls/CaptionProperties/CaptionPropertiesPopover/CaptionPropertiesPopover.tsx, aim/web/ui/src/modules/BaseExplorer/components/Grouping/GroupingPopover/GroupingPopover.tsx
Fixed the losses of selected options in the time of search in ControlPopover and Groupings dropdowns.
Also fixed the accessibility issues for the `Enter` and `Backspace` behavior.
=> [fix] Fix dropdowns selected options losses in time of searching other options in Figures Explorer

aim/web/ui/package-lock.json, aim/web/ui/package.json, aim/web/ui/src/components/kit_v2/Checkbox/Checkbox.d.ts, aim/web/ui/src/components/kit_v2/Checkbox/Checkbox.tsx, aim/web/ui/src/components/kit_v2/Checkbox/index.ts, aim/web/ui/src/config/stitches/stitches.config.ts, aim/web/ui/src/stories/Checkbox.stories.tsx
Add Checkbox component for ui kit v2
=> [feat] Add `Checkbox` component

aim/web/ui/package-lock.json, aim/web/ui/package.json, aim/web/ui/src/components/kit_v2/Text/Text.d.ts, aim/web/ui/src/components/kit_v2/Text/Text.tsx, aim/web/ui/src/components/kit_v2/Text/index.ts, aim/web/ui/src/config/stitches/stitches.config.ts, aim/web/ui/src/modules/core/engine/explorer-engine/index.ts, aim/web/ui/src/pages/FiguresExplorer/index.tsx, aim/web/ui/src/stories/Text.stories.tsx
Create polymorphic `Text` component for UI kit v2.
=> [feat] Add polymorphic `Text` component

aim/web/ui/src/components/Table/Table.tsx, aim/web/ui/src/config/analytics/analyticsKeysMap.ts, aim/web/ui/src/config/table/tableConfigs.ts, aim/web/ui/src/pages/Dashboard/components/ActiveRunsTable/ActiveRunsTable.scss, aim/web/ui/src/pages/Dashboard/components/ExploreSection/ExperimentsCard/ExperimentsCard.scss, aim/web/ui/src/pages/Dashboard/components/ExploreSection/ExperimentsCard/useExperimentsCard.tsx, aim/web/ui/src/pages/Experiment/Experiment.tsx, aim/web/ui/src/pages/Experiment/components/ExperimentNotesTab/useExperimentNotes.tsx, aim/web/ui/src/pages/Experiment/components/ExperimentOverviewTab/ExperimentContributions/useExperimentContributions.tsx, aim/web/ui/src/pages/Experiment/components/ExperimentOverviewTab/ExperimentContributionsFeed/ExperimentContributionsFeed.tsx, aim/web/ui/src/pages/Experiment/components/ExperimentOverviewTab/ExperimentContributionsFeed/ExperimentContributionsFeedStore.ts, aim/web/ui/src/pages/Experiment/components/ExperimentOverviewTab/ExperimentContributionsFeed/index.ts, aim/web/ui/src/pages/Experiment/components/ExperimentOverviewTab/ExperimentContributionsFeed/useExperimentContributionsFeed.tsx, aim/web/ui/src/pages/Experiment/components/ExperimentRunsTab/ExperimentRunsStore.ts, aim/web/ui/src/pages/Experiment/components/ExperimentRunsTab/ExperimentRunsTab.d.ts, aim/web/ui/src/pages/Experiment/components/ExperimentRunsTab/ExperimentRunsTab.scss, aim/web/ui/src/pages/Experiment/components/ExperimentRunsTab/ExperimentRunsTab.tsx, aim/web/ui/src/pages/Experiment/components/ExperimentRunsTab/ExperimentRunsTable/ExperimentRunsTable.d.ts, aim/web/ui/src/pages/Experiment/components/ExperimentRunsTab/ExperimentRunsTable/ExperimentRunsTable.scss, aim/web/ui/src/pages/Experiment/components/ExperimentRunsTab/ExperimentRunsTable/ExperimentRunsTable.tsx, aim/web/ui/src/pages/Experiment/components/ExperimentRunsTab/ExperimentRunsTable/index.ts, aim/web/ui/src/pages/Experiment/components/ExperimentRunsTab/ExperimentRunsTable/useExperimentRunsTable.tsx, aim/web/ui/src/pages/Experiment/components/ExperimentRunsTab/index.ts
Implement the runs tab of the experiment page
Implement the experiment runs table
=> [feat] Implement the runs tab of the experiment page

aim/web/ui/src/components/kit/AudioBox/AudioBox.scss, aim/web/ui/src/components/kit/AudioBox/AudioBox.tsx, aim/web/ui/src/modules/BaseExplorer/components/AudioBox/AudioBox.d.ts, aim/web/ui/src/modules/BaseExplorer/components/AudioBox/AudioBox.scss, aim/web/ui/src/modules/BaseExplorer/components/AudioBox/AudioBox.tsx, aim/web/ui/src/modules/BaseExplorer/components/AudioBox/AudioBoxProgress.tsx, aim/web/ui/src/modules/BaseExplorer/components/AudioBox/index.tsx, aim/web/ui/src/modules/BaseExplorer/components/BoxWrapper/BoxWrapper.tsx
Reproduction steps:
1. play any audio in Audio explorer
2. open audio in full-view mode
3. try to change the audio start-time (progress slider)
=> [fix] Fix issue with playing audio in full view mode

aim/web/ui/src/pages/Dashboard/components/ExploreSection/TagsCard/useTagsCard.tsx, aim/web/ui/src/pages/Experiment/components/ExperimentOverviewTab/ExperimentContributions/useExperimentContributions.tsx, aim/web/ui/src/pages/Experiment/components/ExperimentOverviewTab/ExperimentContributionsFeed/useExperimentContributionsFeed.tsx, aim/web/ui/src/pages/Experiment/components/ExperimentRunsTab/ExperimentRunsTable/ExperimentRunsTable.tsx, aim/web/ui/src/pages/Experiment/components/ExperimentRunsTab/ExperimentRunsTable/useExperimentRunsTable.tsx
- Fixed experiment contributions feed state issue while navigating through experiments tabs
- Fix the Tags tables' select all checkbox button functionality on the Dashboard page
=> [fix] Fix experiment contributions feed state issue 

aim/web/ui/src/components/kit_v2/Box/Box.d.ts, aim/web/ui/src/components/kit_v2/Box/Box.tsx, aim/web/ui/src/components/kit_v2/Box/Index.ts, aim/web/ui/src/stories/Box.stories.tsx
Add polymorphic `Box` component for UI kit v2
=> [feat] Add polymorphic `Box` component

aim/web/ui/src/components/ContributionsFeed/ContributionsFeed.tsx, aim/web/ui/src/components/ContributionsFeed/FeedItem/FeedItem.tsx, aim/web/ui/src/components/ContributionsFeed/FeedItem/index.ts, aim/web/ui/src/components/ContributionsFeed/index.ts, aim/web/ui/src/components/SelectTag/SelectTag.tsx, aim/web/ui/src/components/kit/ActionCard/ActionCard.tsx, aim/web/ui/src/modules/BaseExplorer/types.ts, aim/web/ui/src/pages/Dashboard/components/ActiveRunsTable/useActiveRunsTable.tsx, aim/web/ui/src/pages/Dashboard/components/DashboardRight/ReleaseNotes/ReleaseNotes.tsx, aim/web/ui/src/pages/Dashboard/components/DashboardRight/ReleaseNotes/useReleaseNotes.ts, aim/web/ui/src/pages/Experiment/Experiment.tsx, aim/web/ui/src/pages/ImagesExplore/components/ImagesExploreTableGrid/ImagesExploreTableGrid.tsx, aim/web/ui/src/pages/Metrics/components/MetricsTableGrid/MetricsTableGrid.tsx, aim/web/ui/src/pages/Params/components/ParamsTableGrid/ParamsTableGrid.tsx, aim/web/ui/src/pages/RunDetail/RunDetail.tsx, aim/web/ui/src/pages/Runs/components/RunsTableGrid/RunsTableGrid.tsx, aim/web/ui/src/services/models/explorer/createAppModel.ts, aim/web/ui/src/types/components/CopyToClipBoard/CopyToClipBoard.d.ts, aim/web/ui/src/types/components/Table/Table.d.ts, aim/web/ui/src/utils/d3/drawHoverAttributes.ts, aim/web/ui/src/utils/roundValue.ts
Fix: 
- errors reported in the console
- listing issues
=> [fix] Fix linting issues and cleanup the code

aim/web/ui/package.json, aim/web/ui/src/App.test.tsx, aim/web/ui/src/components/kit/Input/Input.tsx, aim/web/ui/src/components/kit/Input/__snapshots__/Input.test.tsx.snap, aim/web/ui/src/components/kit/Test/Test.tsx, aim/web/ui/src/components/kit/Test/__snapshots__/Test.test.tsx.snap, aim/web/ui/src/services/models/runs/util.test.ts
Fixed lodash-es jest tests failing issue
=> [fix] Fix `lodash-es` jest tests failing issue

CHANGELOG.md, aim/ext/resource/stat.py
Fixes #2420. See the commit messages for additional details.
=> [fix] Track gpu stats even if gathering one stat fails

aim/web/ui/src/modules/core/pipeline/grouping/getGroupValues.ts, aim/web/ui/src/modules/core/pipeline/grouping/group.ts, aim/web/ui/src/pages/MetricsExplorer/config.tsx
Added a type property of a hashed object as group key.
=> [feat] Add group type property while creating hash key for the grouping

CHANGELOG.md, aim/sb3.py, aim/sdk/adapters/sb3.py, docs/source/quick_start/integrations.md, examples/paddle_track.py, examples/sb3_track.py
Created a AimCallback class for initializing a Run, and an extra class AimOutputFormat for tracking the metrics. This solution is forced by sb3 design.
=> [feat] Add Stable-Baselines3 integration

CHANGELOG.md, aim/acme.py, aim/sdk/adapters/acme.py, docs/source/quick_start/integrations.md, examples/acme_track.py
=> [feat] Add Acme integration

CHANGELOG.md, aim/ext/transport/handlers.py, aim/ext/transport/remote_tracking.py, aim/ext/transport/server.py, aim/sdk/remote_repo_proxy.py, aim/sdk/remote_run_reporter.py, aim/sdk/reporter/__init__.py, aim/sdk/reporter/file_manager.py, aim/sdk/run.py
- Extract the file management (polling, touching) from the `class CheckIn` into separate class.
- Change remote tracking handlers to use kwargs.
- Implementation of proxy class for file management.
=> [feat] Provide support for signaling run events via Remote Tracking

aim/web/ui/src/components/LineChart/LineChart.tsx, aim/web/ui/src/modules/BaseExplorer/components/Metrics/hooks/useAlignMetricsData.tsx, aim/web/ui/src/modules/core/api/runsApi/index.ts, aim/web/ui/src/modules/core/engine/explorer-engine/index.ts, aim/web/ui/src/modules/core/engine/pipeline/index.ts, aim/web/ui/src/modules/core/engine/pipeline/state.ts, aim/web/ui/src/modules/core/pipeline/custom/index.ts, aim/web/ui/src/modules/core/pipeline/index.ts, aim/web/ui/src/pages/MetricsExplorer/Controls/ConfigureAxes/Popover/Alignment.tsx, aim/web/ui/src/utils/d3/drawHoverAttributes.ts, aim/web/ui/src/utils/d3/drawParallelHoverAttributes.ts, aim/web/ui/src/utils/encoder/streamEncoding.ts
A custom phase has been added to the UI core pipeline engine, providing the ability for additional querying and data processing.
=> [feat] Add custom phase into UI core pipeline engine

CHANGELOG.md, aim/web/ui/src/pages/RunDetail/RunOverviewTab/components/RunOverviewSidebar/RunOverviewSidebar.scss, aim/web/ui/src/pages/RunDetail/RunOverviewTab/components/RunOverviewSidebar/RunOverviewSidebar.tsx
Added copy icon near the run hash in the run page
=> [feat] Add the ability to easily copy run hash with a single click

aim/web/ui/src/modules/BaseExplorer/components/Metrics/Metrics.tsx, aim/web/ui/src/pages/MetricsExplorer/Controls/IgnoreOutliers/IgnoreOutliers.d.ts, aim/web/ui/src/pages/MetricsExplorer/Controls/IgnoreOutliers/IgnoreOutliers.tsx, aim/web/ui/src/pages/MetricsExplorer/Controls/IgnoreOutliers/index.ts, aim/web/ui/src/pages/MetricsExplorer/config.tsx
- Added ignore outliers control
=> [feat] Add ignore outliers control to the Metrics explorer v2

aim/web/ui/src/modules/BaseExplorer/components/Metrics/Metrics.tsx, aim/web/ui/src/modules/BaseExplorer/components/Metrics/hooks/index.ts, aim/web/ui/src/modules/BaseExplorer/components/Metrics/hooks/useAlignMetricsData.tsx, aim/web/ui/src/modules/BaseExplorer/components/Metrics/hooks/useSmoothChartData.tsx, aim/web/ui/src/pages/MetricsExplorer/Controls/Smoothing/Popover/SmoothingPopover.d.ts, aim/web/ui/src/pages/MetricsExplorer/Controls/Smoothing/Popover/SmoothingPopover.scss, aim/web/ui/src/pages/MetricsExplorer/Controls/Smoothing/Popover/SmoothingPopover.tsx, aim/web/ui/src/pages/MetricsExplorer/Controls/Smoothing/Popover/index.ts, aim/web/ui/src/pages/MetricsExplorer/Controls/Smoothing/Smoothing.d.ts, aim/web/ui/src/pages/MetricsExplorer/Controls/Smoothing/Smoothing.tsx, aim/web/ui/src/pages/MetricsExplorer/Controls/Smoothing/index.ts, aim/web/ui/src/pages/MetricsExplorer/config.tsx
=> [feat] Add smoothing control to the Metrics explorer v2

CHANGELOG.md, aim/sdk/adapters/hugging_face.py
Added model info in parameters
=> [feat] Add HF transformers model info

CHANGELOG.md, aim/sdk/adapters/hugging_face.py
Added support to track multiple datasets metrics in case one uses a dictionary of datasets for evaluation and/or training
=> [feat] Support multiple datasets tracking for HF trainer

aim/web/ui/src/components/LineChart/LineChart.tsx, aim/web/ui/src/components/ZoomOutPopover/ZoomOutPopover.tsx, aim/web/ui/src/config/controls/controlsDefaultConfig.ts, aim/web/ui/src/modules/BaseExplorer/components/Metrics/Metrics.tsx, aim/web/ui/src/modules/BaseExplorer/components/Metrics/hooks/useSmoothChartData.tsx, aim/web/ui/src/pages/MetricsExplorer/Controls/Smoothing/Smoothing.tsx, aim/web/ui/src/pages/MetricsExplorer/Controls/Zoom/Popover/ZoomInPopover/ZoomInPopover.d.ts, aim/web/ui/src/pages/MetricsExplorer/Controls/Zoom/Popover/ZoomInPopover/ZoomInPopover.scss, aim/web/ui/src/pages/MetricsExplorer/Controls/Zoom/Popover/ZoomInPopover/ZoomInPopover.tsx, aim/web/ui/src/pages/MetricsExplorer/Controls/Zoom/Popover/ZoomInPopover/index.ts, aim/web/ui/src/pages/MetricsExplorer/Controls/Zoom/Popover/ZoomOutPopover/ZoomOutPopover.d.ts, aim/web/ui/src/pages/MetricsExplorer/Controls/Zoom/Popover/ZoomOutPopover/ZoomOutPopover.scss, aim/web/ui/src/pages/MetricsExplorer/Controls/Zoom/Popover/ZoomOutPopover/ZoomOutPopover.tsx, aim/web/ui/src/pages/MetricsExplorer/Controls/Zoom/Popover/ZoomOutPopover/index.ts, aim/web/ui/src/pages/MetricsExplorer/Controls/Zoom/Popover/index.ts, aim/web/ui/src/pages/MetricsExplorer/Controls/Zoom/Zoom.d.ts, aim/web/ui/src/pages/MetricsExplorer/Controls/Zoom/Zoom.tsx, aim/web/ui/src/pages/MetricsExplorer/Controls/Zoom/index.ts, aim/web/ui/src/pages/MetricsExplorer/config.tsx, aim/web/ui/src/types/services/models/metrics/metricsAppModel.d.ts, aim/web/ui/src/types/utils/d3/drawBrush.d.ts, aim/web/ui/src/utils/d3/drawBrush.ts
=> [feat] Add zoom in/out controls to the Metrics explorer v2

CHANGELOG.md, aim/web/ui/src/components/CodeBlock/CodeBlock.scss, aim/web/ui/src/components/CommunityPopup/CommunityPopup.d.ts, aim/web/ui/src/components/CommunityPopup/CommunityPopup.scss, aim/web/ui/src/components/CommunityPopup/CommunityPopup.tsx, aim/web/ui/src/components/CommunityPopup/index.tsx, aim/web/ui/src/components/SideBar/SideBar.tsx
- Added "join community" popup
=> [feat] Add "join community" popup to the sidebar

CHANGELOG.md, aim/web/ui/src/pages/Metrics/Metrics.tsx, aim/web/ui/src/pages/Params/Params.tsx, aim/web/ui/src/pages/Scatters/Scatters.tsx, aim/web/ui/src/services/models/explorer/createAppModel.ts, aim/web/ui/src/types/components/LineChart/LineChart.d.ts
- Fix the issue with hidden runs state reset after the live update
- Fix the issue with the wrong chart index being provided when there are hidden charts
=> [fix] Recover hidden lines state after the live update

aim/web/ui/src/modules/BaseExplorer/components/BoxVirtualizer/BoxVirtualizer.tsx, aim/web/ui/src/modules/BaseExplorer/components/Grouping/Grouping/Grouping.tsx, aim/web/ui/src/modules/BaseExplorer/components/ProgressBar/ProgressBarWrapper.tsx, aim/web/ui/src/modules/BaseExplorer/components/Widgets/VisualizerTooltip/getTooltipContent.ts, aim/web/ui/src/modules/BaseExplorer/getDefaultHydration.tsx, aim/web/ui/src/modules/core/pipeline/grouping/getGroupValues.ts
- Fixed rulers inconsistent disappearing issue in Base explorers
=> [fix] Fix rulers inconsistent disappearing issue in Base explorers

CHANGELOG.md, aim/cli/init/commands.py, aim/cli/runs/commands.py, aim/cli/server/commands.py, aim/cli/storage/commands.py
resolves #2440 
@alberttorosyan sorry I had to close the previous pull request, anyways I've removed the changes I made to the `aim up` command since `force_init` already works fine
=> [feat] Add -y option to Aim CLI commands

CHANGELOG.md, aim/web/ui/src/components/SideBar/SideBar.tsx, aim/web/ui/src/components/SideBar/Sidebar.scss, aim/web/ui/src/styles/base/_reset.scss
When the sidebar items are too much and the screen is small, community popup overflows the UI body.
- Fixed the community popup overflowing issue
=> [fix] Fix the community popup overflowing issue

aim/web/ui/package-lock.json, aim/web/ui/package.json, aim/web/ui/src/components/kit_v2/Tabs/Tabs.d.ts, aim/web/ui/src/components/kit_v2/Tabs/Tabs.style.ts, aim/web/ui/src/components/kit_v2/Tabs/Tabs.test.tsx, aim/web/ui/src/components/kit_v2/Tabs/Tabs.tsx, aim/web/ui/src/components/kit_v2/Tabs/index.ts, aim/web/ui/src/components/kit_v2/index.ts, aim/web/ui/src/stories/Tabs.stories.tsx
Add `Tabs` component for UI Kit v2
=> [feat] Create `Tabs` component for UI Kit

aim/web/ui/src/modules/BaseExplorer/components/Grouping/Grouping/Grouping.tsx, aim/web/ui/src/modules/BaseExplorer/components/Grouping/GroupingPopover/GroupingPopover.tsx, aim/web/ui/src/modules/BaseExplorer/components/Visualizer/Visualizer.tsx, aim/web/ui/src/modules/BaseExplorer/getDefaultHydration.tsx, aim/web/ui/src/modules/core/engine/custom-states/index.ts, aim/web/ui/src/modules/core/engine/explorer-engine/index.ts, aim/web/ui/src/modules/core/engine/explorer/groupings/index.ts, aim/web/ui/src/modules/core/engine/explorer/groupings/state.ts, aim/web/ui/src/modules/core/engine/pipeline/index.ts, aim/web/ui/src/stories/Select.stories.tsx, aim/web/ui/src/utils/d3/drawLegends.ts
- Added the ability to persist explorer grouping state for Base Explorers
=> [feat] Add the ability to persist grouping state

aim/web/ui/.storybook/preview.js, aim/web/ui/src/components/kit_v2/Breadcrumb/Breadcrumb.style.ts, aim/web/ui/src/components/kit_v2/Breadcrumb/Breadcrumb.tsx, aim/web/ui/src/components/kit_v2/Breadcrumb/index.ts, aim/web/ui/src/stories/Breadcrumb.stories.tsx
Add the `Breadcrumb` component for UI Kit
=> [feat] Create Breadcrumb component for UI Kit

aim/web/ui/src/config/references/index.ts, docs/source/index.rst, docs/source/using/huggingface_spaces.md
Added docs on deploying aim logs on Hugging Face Spaces.
=> [doc] Add Hugging Face Spaces doc

aim/web/ui/src/pages/Board/Board.tsx, aim/web/ui/src/pages/Board/BoardContainer.tsx, aim/web/ui/src/pages/Boards/Boards.tsx
- Fixed issue with canceling creation of new Board
=> [fix] Fix issue with canceling creation of new Board

aim/web/ui/src/components/kit_v2/Link/Link.d.ts, aim/web/ui/src/components/kit_v2/Link/Link.style.ts, aim/web/ui/src/components/kit_v2/Link/Link.tsx, aim/web/ui/src/components/kit_v2/Link/index.ts, aim/web/ui/src/components/kit_v2/index.ts, aim/web/ui/src/stories/Link.stories.tsx
Added Link component for UI Kit
=> [feat] Create Link component for UI Kit

aim/web/ui/src/App.tsx, aim/web/ui/src/modules/core/engine/event-system/index.ts, aim/web/ui/src/pages/Board/Board.tsx, aim/web/ui/src/services/pyodide/pyodide.ts, aim/web/ui/src/services/pyodide/store.ts, aim/web/ui/src/services/pyodide/usePyodide.ts
- Created store with zustand for pyodide
- Separated states for pyodide
- Included states: `isRunning`, `isLoading`, `namespace` and `pyodide` itself
- Added events service to store
- Integrated new store to `pyodide.ts`
- After changing store resolved the critical issue “Repo is undefined”
=> [feat] Revamp `pyodide` store for custom Boards page

aim/web/ui/src/components/kit_v2/Textarea/Textarea.d.ts, aim/web/ui/src/components/kit_v2/Textarea/Textarea.style.ts, aim/web/ui/src/components/kit_v2/Textarea/Textarea.tsx, aim/web/ui/src/components/kit_v2/Textarea/index.ts, aim/web/ui/src/stories/Textarea.stories.tsx
Added the `Textarea` component for UI Kit v2
=> [feat] Create `Textarea` component for UI Kit

aim/web/ui/public/aim_ui_core.py, aim/web/ui/src/components/kit_v2/Textarea/Textarea.tsx, aim/web/ui/src/components/kit_v2/Textarea/index.ts, aim/web/ui/src/components/kit_v2/index.ts, aim/web/ui/src/pages/Board/components/dataVizElementsMap.tsx
- added python interface for `TextArea` component
=> [feat] Add python interface for `TextArea` component

README.md
=> style: reduce bit misspell README

aim/web/ui/public/aim_ui_core.py, aim/web/ui/src/pages/Board/Board.scss, aim/web/ui/src/pages/Board/components/VisualizationElements/RunLogsVizElement.tsx, aim/web/ui/src/pages/Board/components/VisualizationElements/RunMessagesVizElement.tsx, aim/web/ui/src/pages/Board/components/VisualizationElements/TextInputVizElement.tsx, aim/web/ui/src/pages/Board/components/VisualizationElements/TextsVizElement.tsx, aim/web/ui/src/pages/Board/components/VisualizationElements/index.ts, aim/web/ui/src/pages/RunDetail/RunLogRecords/LogRecordItem/LogRecordItem.tsx
- Add RunLogs to viz elements map
- Add python interface for RunLogs
=> [feat] Add python interface for RunLogs

CHANGELOG.md, aim/web/ui/src/pages/RunDetail/RunLogRecords/RunLogRecords.d.ts, aim/web/ui/src/pages/RunDetail/RunLogRecords/RunLogRecords.tsx, aim/web/ui/src/pages/RunDetail/RunLogRecords/RunLogRecordsStore.ts, aim/web/ui/src/pages/RunDetail/RunLogRecords/useRunLogRecords.tsx
- Fix run messages duplication issue
- Fix run messages virtualized list items height recalculation issue
=> [fix] Resolve run messages duplication issue for in progress runs

aim/web/ui/src/modules/BaseExplorer/components/Grouping/GroupingItem/GroupingItem.tsx, aim/web/ui/src/modules/BaseExplorer/components/Grouping/GroupingPopover/useGroupingPopover.tsx, aim/web/ui/src/pages/Board/Board.tsx, aim/web/ui/src/pages/Board/BoardContainer.tsx, aim/web/ui/src/services/models/board/boardAppModel.ts, aim/web/ui/src/services/pyodide/pyodide.ts
- Fixed issue with automatically navigating to the board edit mode on creating a new board
=> [fix] Fix issue with automatically navigating to the board edit mode on creating a new board

aim/web/ui/public/aim_ui_core.py, aim/web/ui/src/pages/Board/components/VisualizationElements/index.ts
- Added a wrapper class for rendering components (has a method for each component class)
- Simplified layout customizations
=> [feat] Update API for components used in Boards

src/aim/web/ui/public/aim_ui_core.py, src/aim/web/ui/public/index.html, src/aim/web/ui/src/pages/Board/newBoardCode.ts, src/aim/web/ui/src/pages/RunDetail/RunLogRecords/useRunLogRecords.tsx
- Set the `parent_block` field on elements during initial rendering
- Bumped up pyodide version to `0.23.2`
- Updated new board example code with the new API
- Fixed run messages with extra args height calculation
=> [feat] Optimize board rendering via updated layout blocks

src/aim/web/ui/public/aim_ui_core.py, src/aim/web/ui/src/components/kit_v2/index.ts, src/aim/web/ui/src/pages/Board/Board.scss, src/aim/web/ui/src/pages/Board/Board.tsx
- Added python interface for Tabs layout component
- Added contextmanager for Block elements
=> [feat] Add python interface for Tabs layout component

src/aim/web/ui/public/aim_ui_core.py, src/aim/web/ui/src/components/kit_v2/Text/Text.d.ts, src/aim/web/ui/src/components/kit_v2/Text/Text.style.ts, src/aim/web/ui/src/components/kit_v2/Text/Text.tsx, src/aim/web/ui/src/config/stitches/global.ts, src/aim/web/ui/src/pages/Board/components/VisualizationElements/NumberInputVizElement.tsx, src/aim/web/ui/src/pages/Board/components/VisualizationElements/index.ts
- Added python interface for Number input component
=> [feat] Add python interface for Number input component

src/aim/web/ui/public/aim_ui_core.py, src/aim/web/ui/src/components/kit_v2/Slider/Slider.style.ts, src/aim/web/ui/src/components/kit_v2/Slider/Slider.tsx, src/aim/web/ui/src/pages/Board/components/VisualizationElements/NumberInputVizElement.tsx, src/aim/web/ui/src/pages/Board/components/VisualizationElements/RangeSliderVizElement.tsx, src/aim/web/ui/src/pages/Board/components/VisualizationElements/SliderVizElement.tsx, src/aim/web/ui/src/pages/Board/components/VisualizationElements/index.ts
- Added python interface for RangeSlider component
=> [feat] Add python interface for RangeSlider component

src/aim/web/ui/public/aim_ui_core.py, src/aim/web/ui/src/pages/Board/components/VisualizationElements/HeaderVizElement.tsx, src/aim/web/ui/src/pages/Board/components/VisualizationElements/TextVizElement.tsx, src/aim/web/ui/src/pages/Board/components/VisualizationElements/index.ts
- Added TypographyComponent class for typography components
- Added pythonic interface for Header component
=> [feat] Add pythonic interface for `Header` component

src/aim/web/ui/src/pages/Board/Board.style.ts, src/aim/web/ui/src/pages/Board/Board.tsx, src/aim/web/ui/src/pages/Board/components/BoardConsole.tsx
- Fixed board page style issues
- Added ability to clear board console messages
=> [fix] Fix board page style issues

CHANGELOG.md, aim/web/ui/src/modules/BaseExplorer/components/BoxWrapper/BoxWrapper.scss
- Fixed issue with overflowing box content in full-view mode
=> [fix] Fix issue with overflowing box content in full-view mode

src/aim/web/ui/src/modules/BaseExplorer/components/BoxWrapper/BoxWrapper.scss
- Resolved text-box content overflowing issue in full-view mode
=> [fix] Resolve text-box content overflowing issue in full-view mode

src/aim/web/ui/public/aim_ui_core.py, src/aim/web/ui/src/components/kit_v2/Radio/Radio.style.ts, src/aim/web/ui/src/pages/Board/components/VisualizationElements/RadioVizElement.tsx
- resolved issue with setting default value of `Radio` component
- added `orientation` prop to `Radio` component
=> [fix] Resolve issue with setting default value of `Radio` component

src/aim/web/ui/src/components/kit_v2/Table/Table.d.ts, src/aim/web/ui/src/components/kit_v2/Table/Table.style.ts, src/aim/web/ui/src/components/kit_v2/Table/Table.tsx, src/aim/web/ui/src/components/kit_v2/Table/components/Table.style.ts, src/aim/web/ui/src/components/kit_v2/Table/components/TableBody.tsx, src/aim/web/ui/src/components/kit_v2/Table/components/TableCell.tsx, src/aim/web/ui/src/components/kit_v2/Table/components/TableFooter.tsx, src/aim/web/ui/src/components/kit_v2/Table/components/TableHead.tsx, src/aim/web/ui/src/components/kit_v2/Table/components/TableHeader.tsx, src/aim/web/ui/src/components/kit_v2/Table/components/TableRow.tsx, src/aim/web/ui/src/components/kit_v2/Table/components/index.ts, src/aim/web/ui/src/components/kit_v2/Table/index.ts, src/aim/web/ui/src/stories/Table.stories.tsx
Added `Table` component for UI kit
=> [feat] Add `Table` component for UI kit

src/aim/web/ui/src/modules/core/engine/explorer/groupings/state.ts
- Fixed inability to apply aggregation and display legends in Metrics v2 with default configs
=> [fix] Fix inability to apply aggregation in Metrics v2 with default configs

src/aimcore/web/ui/src/components/kit_v2/Tree/Tree.style.ts, src/aimcore/web/ui/src/components/kit_v2/Tree/Tree.tsx, src/aimcore/web/ui/src/pages/App/App.style.tsx, src/aimcore/web/ui/src/pages/App/App.tsx
Used Tree component to render board items
=> [feat] Use Tree for to render board items

src/aimcore/web/ui/src/pages/App/App.tsx, src/aimcore/web/ui/src/pages/Board/Board.tsx
Brought back `Board Editor` edit mode
=> [feat] Bring back `Board Editor` edit mode

src/aimcore/web/ui/public/aim_ui_core.py, src/aimcore/web/ui/src/components/kit/AudioBox/AudioBox.tsx, src/aimcore/web/ui/src/pages/Board/components/AudiosList.tsx, src/aimcore/web/ui/src/pages/Board/components/ImagesList.tsx, src/aimcore/web/ui/src/pages/Board/components/TextList.tsx, src/aimcore/web/ui/src/pages/Board/components/VisualizationElements/AudiosVizElement.tsx, src/aimcore/web/ui/src/pages/Board/components/VisualizationElements/ImagesVizElement.tsx, src/aimcore/web/ui/src/pages/Board/search.ts, src/aimcore/web/ui/src/pages/Report/Report.tsx, src/aimcore/web/ui/src/services/pyodide/pyodide.ts
Temp solution for sequences processing without lazy loading for blobs data
=> [feat] Enable processing for sequences in UI

src/aimcore/web/ui/public/aim_ui_core.py, src/aimcore/web/ui/src/pages/Board/search.ts, src/aimcore/web/ui/src/services/pyodide/pyodide.ts
Add ability to apply range slicing during data filtration in boards.
e.g.
```python
from asp import Metric
Metric.filter(query='True', count=10, start=100, stop=200)
```
=> [feat] Enable range slicing via sequence filter

src/aimcore/web/ui/src/components/SplitPane/SplitPane.d.ts, src/aimcore/web/ui/src/config/pageTitles/pageTitles.ts, src/aimcore/web/ui/src/pages/Board/Board.tsx, src/aimcore/web/ui/src/pages/Explorers/MetricsExplorer/index.ts, src/aimcore/web/ui/src/pages/Report/Report.tsx
- added missing property `sizes` to `SplitPane` component
=> [fix] Resolve pane resizing issue for boards

CHANGELOG.md, aim/web/ui/src/pages/Tags/Tags.scss
Fixed tags table rendering issue
=> [fix] Resolve tags list visibility issue in tags page

.gitignore, src/aimcore/web/ui/src/pages/Board/Board.tsx
- Added `liveUpdateEnabled` flag in `Board.tsx` to temporarily disable live update for Boards
- Added `.history` to `.gitignore` for vscode local history extension
=> [feat] Add flag to toggle live update in Board.tsx

src/aimcore/web/ui/public/aim_ui_core.py, src/aimcore/web/ui/src/hooks/useCodeHighlighter.ts, src/aimcore/web/ui/src/pages/Board/components/VisualizationElements/CodeVizElement.tsx, src/aimcore/web/ui/src/pages/Board/components/VisualizationElements/index.ts
Added pythonic interface for the `CodeBlock`  component
=> [feat] Add pythonic interface for `CodeBlock` component

pkgs/aimstack/asp/boards/charts.py, src/aimcore/web/ui/package-lock.json, src/aimcore/web/ui/package.json, src/aimcore/web/ui/public/aim_ui_core.py, src/aimcore/web/ui/src/pages/Board/components/VisualizationElements/ParallelPlotVizElement.tsx, src/aimcore/web/ui/src/pages/Board/components/VisualizationElements/ScatterPlotVizElement.tsx, src/aimcore/web/ui/src/pages/Board/components/VisualizationElements/index.ts
-  Integrated parallel plot in apps
=> [feat] Integrate parallel plot in apps

src/aimcore/web/ui/public/aim_ui_core.py
Refactored `data display` elements parameters
=> [refactor] Refactor data display element parameters

src/aimcore/web/ui/src/modules/core/pipeline/adapter/collectQueryableData.ts, src/aimcore/web/ui/src/modules/core/pipeline/adapter/processor.ts, src/aimcore/web/ui/src/modules/core/pipeline/adapter/types.ts, src/aimcore/web/ui/src/pages/Explorers/MetricsExplorer/index.ts, src/aimcore/web/ui/src/types/core/AimObjects/Run.d.ts
- Removed redundant range slicing in Metrics Explorer
=> [fix] Remove redundant range slicing in Metrics Explorer

src/aimcore/web/ui/src/components/kit_v2/Checkbox/Checkbox.style.ts, src/aimcore/web/ui/src/components/kit_v2/Checkbox/Checkbox.tsx, src/aimcore/web/ui/src/components/kit_v2/QueryBadge/QueryBadge.style.ts, src/aimcore/web/ui/src/components/kit_v2/QueryBadge/QueryBadge.tsx, src/aimcore/web/ui/src/components/kit_v2/Text/Text.tsx, src/aimcore/web/ui/src/components/kit_v2/Text/index.ts
Updated the `Checkbox` component colors
=> [feat] Update colors of the `Checkbox` component

docs/source/quick_start/supported_types.md
https://github.com/aimhubio/aim/blob/main/pkgs/aimstack/asp/models/objects/distribution.py#L23
=> Rename "distribution" to "samples" in supported_types.md

pkgs/aimstack/asp/boards/custom-board.py, pkgs/aimstack/asp/boards/metrics/loss/run.py, pkgs/aimstack/asp/boards/runs.py, pkgs/aimstack/asp/boards/test/run.py, src/aimcore/web/ui/public/aim_ui_core.py, src/aimcore/web/ui/src/components/kit_v2/Table/Table.style.ts, src/aimcore/web/ui/src/components/kit_v2/Table/Table.tsx, src/aimcore/web/ui/src/pages/Board/components/VisualizationElements/NumberInputVizElement.tsx, src/aimcore/web/ui/src/pages/Board/components/VisualizationElements/TableVizElement.tsx, src/aimcore/web/ui/src/pages/Board/components/VisualizationElements/TextInputVizElement.tsx, src/aimcore/web/ui/src/pages/Board/serverAPI/runFunction.ts, src/aimcore/web/ui/src/pages/Board/serverAPI/search.ts, src/aimcore/web/ui/src/services/pyodide/pyodide.ts
- Added additional controls for Runs table
- Removed dummy board files
- Fixed server functions cache issue
=> [feat] Extend Runs board functionality in ASP

pkgs/aimstack/asp/boards/run.py, src/aimcore/web/ui/src/components/kit_v2/Table/Table.tsx, src/aimcore/web/ui/src/components/kit_v2/Tabs/Tabs.style.ts, src/aimcore/web/ui/src/pages/Board/Board.style.ts, src/aimcore/web/ui/src/pages/Board/Board.tsx, src/aimcore/web/ui/src/pages/Board/components/VisualizationElements/NumberInputVizElement.tsx
- Added single run board initial version
=> [feat] Add single run board

src/aimcore/web/ui/src/components/kit_v2/Popover/Popover.style.ts, src/aimcore/web/ui/src/components/kit_v2/Tooltip/Tooltip.d.ts, src/aimcore/web/ui/src/components/kit_v2/Tooltip/Tooltip.style.ts, src/aimcore/web/ui/src/components/kit_v2/Tooltip/Tooltip.tsx, src/aimcore/web/ui/src/config/stitches/animations.ts, src/aimcore/web/ui/src/config/stitches/theme.ts, src/aimcore/web/ui/src/stories/Tooltip.stories.tsx
- Update Tooltip component styles
- Added semantic colors for Tooltip component
=> [feat] Enhance the `Tooltip` component 

src/aimcore/web/ui/package.json
Ui build failed
- Increased `--max_old_space_size=4096`  to `--max_old_space_size=6144`
=> [fix] Resolve issue with reaching js heap limit

src/aimcore/web/ui/src/pages/Board/Board.tsx
- Resolved querying issue in Runs board
=> [fix] Resolve querying issue in Runs board

pkgs/aimstack/asp/boards/audios.py, pkgs/aimstack/asp/boards/run.py, pkgs/aimstack/asp/boards/runs.py
- Replaced redundant `MutableMapping` type and to `dict`
=> [refactor] Improve performance of `flatten` dict function

pkgs/aimstack/asp/boards/audios.py, pkgs/aimstack/asp/boards/run.py, pkgs/aimstack/asp/models/objects/audio.py, pkgs/aimstack/asp/models/objects/image.py, src/aimcore/web/ui/public/aim_ui_core.py, src/aimcore/web/ui/public/index.html, src/aimcore/web/ui/src/pages/Board/Board.style.ts, src/aimcore/web/ui/src/pages/Board/Board.tsx, src/aimcore/web/ui/src/pages/Board/components/AudiosList.tsx, src/aimcore/web/ui/src/pages/Board/serverAPI/runFunction.ts, src/aimcore/web/ui/src/pages/Board/serverAPI/search.ts, src/aimcore/web/ui/src/services/pyodide/pyodide.ts
- Resolved memory leak caused by undestroyed proxy objects
- Fixed issue with proxy objects parsing for server functions
- Add pending requests cancellation on board unmount
=> [fix] Resolve memory leak caused by proxy objects

src/aimcore/web/ui/src/modules/core/pipeline/adapter/collectQueryableData.ts, src/aimcore/web/ui/src/modules/core/pipeline/adapter/types.ts, src/aimcore/web/ui/src/types/core/AimObjects/CustomObject.d.ts, src/aimcore/web/ui/src/types/core/AimObjects/Run.d.ts
- Resolved issue with processing record steps for RangePanel in Explorers
=> [fix] Resolve issue with processing record steps for RangePanel in Explorers

src/aimcore/web/ui/src/pages/Board/Board.style.ts, src/aimcore/web/ui/src/pages/Board/Board.tsx, src/aimcore/web/ui/src/pages/Board/components/BoardConsole.tsx
Fixed the BoardConsole width overflowing issue
=> [fix] Fix the `BoardConsole` components' width overflowing issue

pkgs/aimstack/asp/boards/audios.py, pkgs/aimstack/asp/boards/run.py
Added `Audios` tab in single run board
=> [feat] Add `Audios` tab in single run board

src/aimcore/web/ui/src/components/FigureBox/FigureBox.tsx, src/aimcore/web/ui/src/pages/Board/Board.tsx, src/aimcore/web/ui/src/pages/Board/components/AudiosList.tsx, src/aimcore/web/ui/src/pages/Board/components/FiguresList.tsx, src/aimcore/web/ui/src/pages/Board/components/ImagesList.tsx
- Added figures blob uri lazy loading in boards
=> [feat] Add figures blob uri lazy loading in boards

src/aimcore/web/ui/src/components/FigureBox/FigureBox.tsx, src/aimcore/web/ui/src/components/ImageBox/ImageBox.tsx, src/aimcore/web/ui/src/modules/BaseExplorer/components/Image/Image.tsx, src/aimcore/web/ui/src/modules/BaseExplorer/components/Image/index.ts, src/aimcore/web/ui/src/pages/Board/components/AudiosList.tsx, src/aimcore/web/ui/src/pages/Board/components/FiguresList.tsx, src/aimcore/web/ui/src/pages/Board/components/ImagesList.tsx, src/aimcore/web/ui/src/pages/Dashboard/components/ProjectStatistics/ProjectStatisticsStore.ts, src/aimcore/web/ui/src/pages/Dashboard/components/ProjectStatistics/useProjectStatistics.tsx, src/aimcore/web/ui/src/pages/Explorers/ImagesExplorer/config.ts, src/aimcore/web/ui/src/pages/Explorers/ImagesExplorer/getStaticContent.tsx, src/aimcore/web/ui/src/pages/Explorers/ImagesExplorer/index.tsx, src/aimcore/web/ui/src/routes/routes.tsx
=> [feat] Add Images Explorer

src/aimcore/web/ui/src/components/kit_v2/Table/Table.style.ts, src/aimcore/web/ui/src/components/kit_v2/Table/Table.tsx, src/aimcore/web/ui/src/pages/Board/components/VisualizationElements/TableVizElement.tsx
Added table content height on its container
=> [fix] Resolve table height issue in boards

pkgs/aimstack/asp/models/run.py
Hey,
just wanted to quickly update the invalid typings.
=> [fix] Replace invalid typing

src/aimcore/web/ui/public/aim_ui_core.py, src/aimcore/web/ui/src/components/kit_v2/Table/Table.d.ts, src/aimcore/web/ui/src/components/kit_v2/Table/Table.tsx
Refactor logic for storing focused and selected rows states for Table component.
=> [refactor] Clean up Table component states

src/aimcore/web/ui/public/aim_ui_core.py, src/aimcore/web/ui/src/pages/Board/Board.tsx, src/aimcore/web/ui/src/pages/Board/components/VisualizationElements/BoardVizElement.tsx, src/aimcore/web/ui/src/services/pyodide/pyodide.ts
Reset the current board state on unmount.
=> [feat] Reset board state on exit

pkgs/aimstack/asp/boards/run.py, src/aimcore/web/ui/public/aim_ui_core.py, src/aimcore/web/ui/src/modules/core/api/dataFetchApi/index.ts, src/aimcore/web/ui/src/pages/Board/Board.tsx, src/aimcore/web/ui/src/pages/Board/serverAPI/find.ts, src/aimcore/web/ui/src/services/api/endpoints.ts, src/aimcore/web/ui/src/services/pyodide/pyodide.ts
- Added API calls for `find-sequence` and `find-container` endpoints
- Added `find` method mock on packages type classes for pyodide
- Update `run.py` board in `asp` package with usage of `Run.find()` method
=> [feat] Register `find()` method on packages pyodide module

src/aimcore/web/ui/src/components/kit_v2/Button/Button.d.ts, src/aimcore/web/ui/src/pages/Board/components/VisualizationElements/FormVizElement.tsx
- Use `form` tag for form viz element in boards
- Add `onSubmit` action handler
- Fix types for `Button` component props
=> [feat] Enable form submissions with enter key

src/aimcore/web/ui/public/aim_ui_core.py, src/aimcore/web/ui/src/pages/App/App.d.ts, src/aimcore/web/ui/src/pages/App/App.tsx, src/aimcore/web/ui/src/pages/App/components/AppPage.tsx, src/aimcore/web/ui/src/pages/App/components/AppWrapper.tsx, src/aimcore/web/ui/src/pages/Board/Board.tsx, src/aimcore/web/ui/src/pages/Board/components/VisualizationElements/BoardLinkVizElement.tsx, src/aimcore/web/ui/src/pages/Board/components/VisualizationElements/BoardVizElement.tsx, src/aimcore/web/ui/src/services/pyodide/pyodide.ts
Added an ability to update the URL based on board components state updates and recover the state from the URL.
=> [feat] Sync board state with URL

src/aimcore/web/ui/src/modules/core/pipeline/adapter/processor.ts, src/aimcore/web/ui/src/types/core/AimObjects/GroupedSequences.d.ts
- Revamped query result processing for Explorers
=> [feat] Revamp query result processing for Explorers

pkgs/aimstack/asp/boards/audios.py, pkgs/aimstack/asp/boards/figures.py, pkgs/aimstack/asp/boards/images.py, pkgs/aimstack/asp/boards/texts.py, src/aimcore/web/ui/public/aim_ui_core.py, src/aimcore/web/ui/src/pages/Board/serverAPI/find.ts, src/aimcore/web/ui/src/pages/Board/serverAPI/search.ts
To keep consistency between SDK retrieving methods return data format and UI retrieving methods return data format:
- Removed data processing from search and find methods used for `.filter` and `.find` methods in boards
- Updated boards' code based on the data format change
=> [feat] Update query result processing for boards

src/aimcore/web/ui/src/Main.tsx, src/aimcore/web/ui/src/components/Illustration/config.tsx, src/aimcore/web/ui/src/pages/Apps/Apps.style.tsx, src/aimcore/web/ui/src/pages/Apps/Apps.tsx, src/aimcore/web/ui/src/pages/Apps/components/AppCard.tsx
Added a page with installed apps displayed as cards.
=> [feat] Add apps (packages) page in UI

pkgs/aimstack/asp/boards/logs_overview.py, src/aimcore/web/ui/src/components/kit_v2/Table/Table.style.ts, src/aimcore/web/ui/src/pages/Board/Board.style.ts, src/aimcore/web/ui/src/pages/Board/components/LoadingBar.tsx
Fix minor style issues as well:
- `cursor: pointer;` for table cells
- loading bar width calculation
=> [fix] Align row items by start in boards

aim/sdk/adapters/pytorch_lightning.py, examples/pytorch_lightning_track.py
Resolves #2746 
**Notes**
Have been manually tested via a local package install with the lightning `AimLogger`.
=> [fix] Fix pytorch_lightning aliases issue

aim/ext/resource/stat.py
typo in code led to these metrics not being collected at all
=> [fix] Fix typos in stat.py to collect gpu memory and power correctly

aim/web/api/views.py
Fixes #3108. I screwed up the check when I fixed the style issue.
=> [fix] Invert static files root check
