aim/cli/auth/commands.py
* Print any additional information to stderr so stout can be piped to
other commnds
* This change makes easy to copy the key to paste-buffer using tools
like `pbcopy` or `xclip`
Examples of usage:
```
aim auth -a <url> | pbcopy # for macOS
aim auth -a <url> |  xclip -selection clipboard # for Linux with X11
```
=> Change output of aim auth command to only contain key in stdout

aim/web/ui/src/components/hub/ContextTable/ContextTable.js, aim/web/ui/src/screens/hub/HubExperimentsDashboardScreen/components/Runs/Runs.js, aim/web/ui/src/screens/hub/HubMainScreen/HubMainScreen.js, aim/web/ui/src/screens/hub/HubMainScreen/components/ContextBox/ContextBox.js, aim/web/ui/src/screens/hub/HubMainScreen/models/HubMainScreenModel.js, aim/web/ui/src/ui/components/Table/Table.js
This adds an ability to easily manage `Explore Screen` state history for dashboard apps.
=> Hoist context table state to the parent container

aim/web/ui_v2/src/components/LineChart/LineChart.tsx, aim/web/ui_v2/src/types/components/LineChart/LineChart.d.ts, aim/web/ui_v2/src/types/utils/d3/drawBrush.d.ts, aim/web/ui_v2/src/utils/d3/drawBrush.ts, aim/web/ui_v2/src/utils/d3/drawHoverAttributes.ts
Fix: 
- Brush `active` or `focused` point location on zoom
Add: 
- `updateFocusedChart` function can call with an existing `active` or `focused` point(can call without receiving mouse position)
=> Fix linechart active point on zoom mode

aim/storage/structured/sql_engine/utils.py, aim/web/api/projects/views.py, aim/web/api/v2/views/experiments.py, aim/web/api/v2/views/tags.py
* Added run count per tag/experiment to APIs
* Added tag color set/get
* Optimized `ModelMappedColelction len()` method to return query.count() instead of caching all objects
=> tags/experiments API improvements

aim/storage/types.py, aim/web/api/experiments/pydantic_models.py, aim/web/api/experiments/views.py, aim/web/api/runs/pydantic_models.py, aim/web/api/runs/utils.py, aim/web/api/runs/views.py, aim/web/api/tags/pydantic_models.py, aim/web/api/tags/views.py, tests/api/test_run_api.py, tests/api/test_structured_data_api.py
- send props for run endpoints (info, search, metric_search)
- send experiment name and creation time for tag/tag_id/runs
- combine traces, params, and props into info instead of separate endpoints
- make necessary changes for pydantic models and unit tests
=> Make changes to runs and tags endpoints:

aim/storage/sdk/trace.py
This fixes the issue of empty strings being a query. Empty strings are treated as always-true matching queries.
=> Noop Query

aim/storage/sdk/run.py
This PR fixes the bug of missing contexts from storage - when already having a context in a global cache forbids it to be written in the run meta tree.
=> Always write contexts

aim/storage/encoding/encoding_native.pxd, aim/storage/encoding/encoding_native.pyx
This PR fixes issues with encoded values being truncated with null-byte because of c-style strings are used by cython.
=> Avoid null-terminating C-style strings

aim/sdk/errors.py, aim/storage/sdk/run.py, aim/storage/structured/entities.py, aim/storage/structured/sql_engine/entities.py, aim/storage/structured/sql_engine/factory.py, aim/storage/structured/sql_engine/utils.py, tests/api/test_project_api.py, tests/api/test_run_api.py, tests/api/test_structured_data_api.py, tests/base.py, tests/test_upgrade_cmd.py
Removed all the logic associated with the case when sqlite Run is missing. Added `run.experiment = 'default'` for newly created runs
=> add sqlite Run every time new Run is started

aim/web/ui_v2/src/components/CustomTable/Table.scss, aim/web/ui_v2/src/components/CustomTable/TableColumn.tsx
Currently, columns in our table have dynamic width. 
Depending on their content they can shrink and expand.
To avoid viewport overlapping by a column we're setting `max-width: 500px;` on table column.
=> Set max width on table column

aim/web/ui_v2/src/components/ControlPopover/ControlPopover.tsx, aim/web/ui_v2/src/pages/Metrics/components/Controls/Controls.tsx, aim/web/ui_v2/src/pages/Metrics/components/SelectForm/SelectForm.scss, aim/web/ui_v2/src/pages/Params/components/SelectForm/SelectForm.scss, aim/web/ui_v2/src/types/components/ControlPopover/ControlPopover.d.ts, aim/web/ui_v2/src/utils/d3/drawHoverAttributes.ts, aim/web/ui_v2/src/utils/formatXAxisValueByAlignment.ts
Fix: 
- Tune reset button of selected metrics tags
- Chart tooltip 0 step value from "--" to "0" (nullish coalescing)
-  Add ControlsPopover 'open' props
=> Fixed select form layout issues

aim/web/ui_v2/src/components/CustomTable/Table.tsx, aim/web/ui_v2/src/pages/Metrics/components/MetricsTableGrid/MetricsTableGrid.tsx, aim/web/ui_v2/src/pages/Metrics/components/Table/ManageColumnsPopover/ManageColumnsPopover.tsx, aim/web/ui_v2/src/pages/Params/components/ParamsTableGrid/ParamsTableGrid.tsx, aim/web/ui_v2/src/pages/Runs/components/RunsTableColumns/RunsTableColumns.tsx, aim/web/ui_v2/src/services/models/metrics/metricsAppModel.ts, aim/web/ui_v2/src/services/models/params/paramsAppModel.ts, aim/web/ui_v2/src/services/models/runs/runsAppModel.ts, aim/web/ui_v2/src/types/pages/metrics/components/TableColumns/TableColumns.d.ts, aim/web/ui_v2/src/types/services/models/params/paramsAppModel.d.ts
Fix:
- sorted by order
- filter hidden columns
- 'getDataAsTableRows' function
Add: 
- xStep value for table columns for value, epoch, timestamp
- tune grouped data export for table
=> Fix Table export CSV button for all (Metrics, Params, Runs) pages

aim/web/ui_v2/src/hooks/resize/usePanelResize.ts, aim/web/ui_v2/src/pages/Metrics/MetricsContainer.tsx, aim/web/ui_v2/src/pages/Params/ParamsContainer.tsx, aim/web/ui_v2/src/services/models/metrics/metricsAppModel.ts, aim/web/ui_v2/src/services/models/params/paramsAppModel.ts, aim/web/ui_v2/src/types/services/models/metrics/metricsAppModel.d.ts
Setting and recovering table and chart heights (resize mode) in params and metrics pages
=> Keep table resize state in model config

aim/sdk/run.py, tests/utils.py
This PR quickly replaces `trcs` directories into `seqs` (containers for metric sequences) in the `.aim` repo structure.
Note: This change is not backward-compatible with prior repositories, so one will need to manually rename existing directories.
=> Rename `trcs` into `seqs`

aim/web/ui_v2/src/components/ResizePanel/ResizePanel.tsx, aim/web/ui_v2/src/pages/Metrics/Metrics.scss, aim/web/ui_v2/src/pages/Metrics/Metrics.tsx, aim/web/ui_v2/src/pages/Params/Params.scss, aim/web/ui_v2/src/pages/Params/Params.tsx, aim/web/ui_v2/src/types/components/ResizePanel/ResizePanel.d.ts
Added className property on ResizePanel component
---
- Deleted unused `Params__resize` class name from Params.scss
=> Hide resize panel and table placeholder on empty data

aim/web/api/__init__.py, aim/web/api/views.py
Use separate sub apps for apis and static-files endpoints to avoid double zipping for static files (only apis sub app will have GZIPMiddleware)
=> Sub app division for apis and static files

aim/web/ui/src/pages/Metrics/components/SelectForm/SelectForm.tsx, aim/web/ui/src/pages/Params/components/ParamsTableGrid/ParamsTableGrid.tsx, aim/web/ui/src/pages/Runs/components/RunsTableGrid/RunsTableGrid.tsx
If the metric has an empty object as a context value we are removing it from Metrics Explorer select form autocomplete.
Also for Runs and Params Explorer we are rendering the `No context` label in the table column header.
=> Handle displaying of empty context in UI

aim/web/ui/src/services/models/metrics/metricsAppModel.ts
In order to make chart hover interactions more smooth, we are adding debouncing on `LineChart` hover callback.
So that it will be fired after the last call within a given offset (`35ms` for now)
=> Add debouncing on metrics explorer chart focused point change handler

aim/sdk/run.py
Wait for queue only if `Run.finalize()` is called explicitly.
When run object is garbage collected (in a separate gc thread) no refs are left for that run, hence queue doesn't have any pending tasks for that run.
=> skip queue wait_for_finished when Run is garbage-collected

aim/web/ui/src/services/models/metrics/metricsAppModel.ts, aim/web/ui/src/utils/getObjectPaths.ts
- Check the `null` case when extracting keys as paths from an object
- Add a small fix to prevent Metrics Explorer page fails during `hot reload` in `dev` mode
=> Fix convert null to object issue

aim/web/ui/src/services/models/params/paramsAppModel.ts
We had an issue while grouping charts. If the run doesn't include a value that matches with the dimension name we filtering it.
=> Filter out runs with missing params in HighPlot

aim/ext/sshfs/utils.py, aim/ext/task_queue/queue.py
- fix the issue with additional reference to run from tracking thread(this was causing the last run to not finalize) 
- remove `allow_other` option from sshfs options list as on ubuntu it was disabling the auto-mounting and is not really needed by aim
=> Remote fs and tracking queue fixes

aim/storage/union.py
In Union db we have an issue, let's call it `overshadowing` - when only a part of the given prefix is in the union but it ignores all the other chunks.
This PR fixes the issue when acquiring a view of union db (`PrefixView` in particular) on `chunks`, and it treats index db as a regular chunk db and always redirects the view into the index. The issue lead to undiscoverable `run`s and was able to only detect indexed / finalized ones.
=> Fix the issue with overshadowing

aim/web/ui/src/utils/encoder/encoder.ts
Add error handler for cases when URL can have a search query param which value is not an encoded object
=> Add errorHandler for decoding of wrong values from URL

aim/web/ui/src/pages/RunDetail/RunMetricCard.tsx, aim/web/ui/src/services/models/metrics/metricsAppModel.ts, aim/web/ui/src/services/models/params/paramsAppModel.ts, aim/web/ui/src/utils/contextToString.ts, aim/web/ui/src/utils/formatValue.ts
Use value formatter in explorer pages for `params` and `context` fields.
=> Add value formatter for params and context fields

CHANGELOG.md, aim/cli/init/commands.py, docs/source/refs/cli.md
Add ability to specify repository path during `aim init` via `--repo` argument
=> Add repo argument on aim init command

aim/web/ui/src/components/ChartPanel/PopoverContent/PopoverContent.tsx, aim/web/ui/src/pages/Metrics/components/Table/ManageColumnsPopover/ManageColumnsPopover.tsx, aim/web/ui/src/types/services/models/metrics/metricsAppModel.d.ts, aim/web/ui/src/utils/d3/drawAxes.ts, aim/web/ui/src/utils/formatByAlignment.ts
Fix: 
- Filtering highlighted columns on search in "manage-table-columns"
- LineChart x-axis alignment name to default "Steps"
- Add space between metric and context in LineChart popover
=> Fix filtering highlighted columns on search in "manage-table-columns"

aim/web/api/views.py
Fix security issue when incorrect path is given to the endpoint that serves static files which can lead to a leak of files (e.g. `/static-files/../../../../etc/passwd`)
=> Security issue fix for `/static-files/{path}` endpoint 

aim/web/api/experiments/views.py, aim/web/api/runs/utils.py, aim/web/api/runs/views.py, aim/web/api/tags/views.py
Fix endpoints that create `Run` object directly to account the repo as well (were using the default)
=> Fix run-repo bindings in web endpoints

CHANGELOG.md, aim/web/ui/src/components/ImagesList/ImageBox.tsx, aim/web/ui/src/components/ImagesList/ImagesList.tsx, aim/web/ui/src/components/ImagesPanel/ImagesPanel.tsx, aim/web/ui/src/components/ImagesSet/ImageSet.scss, aim/web/ui/src/components/ImagesSet/ImagesSet.d.ts, aim/web/ui/src/components/ImagesSet/ImagesSet.tsx, aim/web/ui/src/services/models/imagesExplore/imagesExploreAppModel.ts
- Reimplement vertical virtualization in `ImagesSet` component
- Change component rendering behavior by removing cyclic nested/recursive rendering
- Display an image right after it is received through the stream
- Add `imageHeight` prop on `ImagesSet` component
=> Improve Images Explorer rendering performance through better images list virtualization

aim/web/ui/src/components/HeatMap/HeatMap.tsx
Changed URL `search` param name to `select` to correspond to app config.
=> Fix activity cell click action functionality

performance_tests/BASELINE, performance_tests/conftest.py
Restructure performance tests to use in-place logs instead of downloading from S3 and extracting and adjust baselines for newly added tests. Also added env variable to fallback to the previous download/extract approach.
=> Performance tests fixes

aim/cli/up/commands.py, aim/web/api/runs/image_utils.py, aim/web/api/runs/utils.py, aim/web/api/runs/views.py
Provide `-w` or `--workers` option for `aim up` command to specify `uvicorn` workers count and make images/metrics search endpoints async to avoid memory piling up
=> Server side fixes and additions

aim/web/ui/src/components/ProjectWrapper/ProjectWrapper.tsx, aim/web/ui/src/pages/RunDetail/TraceVisualizationContainer/TraceVisualizationContainer.tsx, aim/web/ui/src/services/models/runs/util.ts
- Add analytics tracking for newly added tabs on Run Detail page (Images, Distributions, Figures, Texts, Audio)
=> Add analytics to Run detail's tabs

aim/web/ui/src/components/ChartPanel/ChartPopover/ChartPopover.tsx, aim/web/ui/src/components/kit/Dropdown/Dropdown.scss, aim/web/ui/src/components/kit/Dropdown/DropdownCustomOption.tsx, aim/web/ui/src/components/kit/ExpressionAutoComplete/ExpressionAutoComplete.scss, aim/web/ui/src/services/models/explorer/createAppModel.ts
When hovering over on table rows or chart, chart tooltip opens and Material UI Popover component changes focus on tooltip
Fix: 
- disable auto-focus on chart tooltip
- tuned Dropdown Component options style
Tested on browsers:  Chrome, Safari , Firefox
=> Added focused/hovered states style of search-inputs

.github/workflows/python-package.yml
Node versions < v16 do not support certain features required for UI build.
=> [fix] Use specific version of node during packaging.

aim/cli/reindex/utils.py, aim/storage/rockscontainer.py, aim/storage/union.py
While the `RocksContainer` should run above-mentioned optimizations when db is accessed, this was not the case due to inheritance. This fix makes sure that WAL flush is run regardless how the `RocksContainer` is used; as a separate object or a part of union DB.
=> [fix] Run on-the-fly WAL flushes and other optimizations for union DB.

aim/sdk/num_utils.py, aim/sdk/run.py, tests/sdk/test_run_metric_types.py
When saving tracked value type in run metadata, use the already
converted value instead of the original input value.
Added covering unit-test.
=> [fix] Track converted value type instead of the input value type.

CHANGELOG.md, aim/sdk/repo.py
Also added check to identify if run is still in progress and changed `repo` methods(delete, copy, move) to not stop execution in case of failure and try to handle remaining runs as well.
=> Fix stalled runs deletion

CHANGELOG.md, aim/sdk/repo.py
Avoid .aim folder creation for remote tracker when Repo object is created implicitly
=> Fix of Run class creates weird folder issue

aim/ext/resource/tracker.py, aim/sdk/run.py, tests/sdk/test_resource_tracker.py
Previously we've had system tracker tests requiring strictly
```{'__system__cpu', '__system__disk_percent', '__system__memory_percent', '__system__p_memory_percent'}```
while working on machine with GPUs, `aim` will automatically track GPU stats as well, resulting in extra metrics.
This PR checks whether the resulting metrics is superset of expected metrics instead of checking equality.
=> Allowing more system metrics, potentially GPU stats

performance_tests/conftest.py
Print performance baselines right before exiting.
This is supposed to be temporary change but I think we'll end up with printing summarized table of rows per test, something like:
`actual_time_min    actual_time_median    actual_time_max    baseline_min    baseline_median    baseline_max`
to get more helpful insights from the performance tests.
=> Cython Bindings / Print Performance Baselines

aim/sdk/objects/image.py, aim/storage/rockscontainer.pyx, aim/storage/types.py, aim/storage/utils.pxd, aim/storage/utils.py, setup.py
* Moving everything else other than type annotations from `types.py` to `utils.pyx`,
* Removing some (generic) type annotations to make it easier to optimize with Cython,
* Wrapper classes for `KeysIterator` and `ValuesIterator`.
=> Cython Bindings / Utils

CHANGELOG.md, aim/web/ui/src/services/models/explorer/createAppModel.ts
- Remove `__example_type__` substring from param names both in Params and Scatter explores
=> [fix] Remove example type substring from param name

aim/web/ui/src/components/kit/Card/Card.scss, aim/web/ui/src/components/kit/Spinner/Spinner.d.ts, aim/web/ui/src/components/kit/Spinner/Spinner.scss, aim/web/ui/src/components/kit/Spinner/Spinner.tsx, aim/web/ui/src/components/kit/Spinner/index.tsx, aim/web/ui/src/pages/RunDetail/RunDetail.scss, aim/web/ui/src/pages/RunDetail/RunDetail.tsx, aim/web/ui/src/pages/RunDetail/RunOverviewTab/RunOverviewTab.scss, aim/web/ui/src/pages/RunDetail/RunOverviewTab/RunOverviewTab.tsx, aim/web/ui/src/pages/RunDetail/RunOverviewTab/components/CLIArgumentsCard/RunOverviewTabCLIArgumentsCard.d.ts, aim/web/ui/src/pages/RunDetail/RunOverviewTab/components/CLIArgumentsCard/RunOverviewTabCLIArgumentsCard.tsx, aim/web/ui/src/pages/RunDetail/RunOverviewTab/components/EnvVariablesCard/RunOverviewTabEnvVariablesCard.d.ts, aim/web/ui/src/pages/RunDetail/RunOverviewTab/components/EnvVariablesCard/RunOverviewTabEnvVariablesCard.tsx, aim/web/ui/src/pages/RunDetail/RunOverviewTab/components/GitInfoCard/index.tsx, aim/web/ui/src/pages/RunDetail/RunOverviewTab/components/MetricsCard/RunOverviewTabMetricsCard.tsx, aim/web/ui/src/pages/RunDetail/RunOverviewTab/components/Packages/RunOverviewTabPackagesCard.d.ts, aim/web/ui/src/pages/RunDetail/RunOverviewTab/components/Packages/RunOverviewTabPackagesCard.tsx, aim/web/ui/src/pages/RunDetail/RunOverviewTab/components/RunOverviewSidebar/RunOverviewSidebar.scss, aim/web/ui/src/pages/RunDetail/TraceVisualizationContainer/TraceVisualizationContainer.tsx
- Used React `Lazy loading` to avoid large size chunk in single run page
- Fixed `RunOverViewSidebar` width
- Tuned `Archive/Unarchive` button styles in `settings tab`
- Added `Spinner` component
- Fixed `Card` component padding
=> [feat] Split code in the single run page

aim/sdk/repo.py
Resolves the following error during `aim runs cp`:
```
ValueError: Value b'' of type <class 'bytes'> is not supported
```
=> [fix] Correct run copy index prefix

CHANGELOG.md, aim/web/ui/src/pages/RunDetail/PlotlyVisualizer/PlotlyVisualizer.scss, aim/web/ui/src/pages/RunDetail/PlotlyVisualizer/PlotlyVisualizer.tsx, docs/source/ui/pages/run_management.md
- Deleted unnecessary styles from `Plotly` wrapper
- Added additional documentation for `Figures` tab
=> [fix] Render plotly figures properly in single run page

CHANGELOG.md, aim/web/ui/src/components/ChartPanel/ChartPanel.tsx, aim/web/ui/src/components/LineChart/LineChart.tsx, aim/web/ui/src/components/ScatterPlot/ScatterPlot.tsx, aim/web/ui/src/services/models/explorer/createAppModel.ts, aim/web/ui/src/types/utils/d3/drawHoverAttributes.d.ts, aim/web/ui/src/utils/d3/drawAxes.ts, aim/web/ui/src/utils/d3/drawHoverAttributes.ts
Expected behavior:
-  after focusing(clicking) on the active point, all charts should freeze(block mouse hovering on charts) before you unfocus the active point, it means before you don't click on one of the sibling charts 
Bug: 
- after focusing on the active point, it doesn’t focus
Solution: 
- on syncing hover state for charts, we immediately set the focused state for every sibling charts and itself
Improvement: 
- Improve d3 utils `drawHoverAttributes` function performance
1. `drawAxisLabel` (create/remove/create changed to create/update)
2. `drawHoverLine` (create/remove/create changed to create/update)
=> [fix] Fix chart active point focusing issue

CHANGELOG.md, docker/create-docker-image.sh
Added retry logic to docker image creation bash script.  Retry 5 times with 2 min. interval. Expected to pass after 2nd attempt, the rest are kept just in case
=> [fix] Retry docker image build when PyPI package is newly pushed

aim/sdk/adapters/xgboost.py
The type annotation was copied from base class callback, and causes
issues with certaain version of xgboost installed.
=> [fix] Remove type annotation from xgboost callback `after_iteration`

CHANGELOG.md, aim/cli/reindex/commands.py, aim/cli/runs/commands.py, aim/sdk/index_manager.py, aim/web/api/__init__.py, aim/web/api/projects/views.py, aim/web/middlewares/profiler/profiler.py
- Remove run reference from `RepoIndexManager` thread after explicitly finalizing the run instance
- Pass the repo path to index manager instead of repo instance to avoid infinitely alive reference on repo instance
=> [fix] Run reference cleanup from `RepoIndexManager` 

CHANGELOG.md, aim/web/ui/src/services/models/explorer/createAppModel.ts
There was a logic to update the request limit on state for live update, live update should get all data, but it shouldn't update the limit exactly on state, because the infinite scroll uses that limit, and it should always have constant value.
Now the I added a calculation logic for live update, and using it once the live updates' start function is called.
Please do your tests with live update enabled status and without it as well.
=> [fix] Fix issue with fetch on load more (infinite scroll) functionality in Runs Explorer

CHANGELOG.md, aim/web/ui/src/services/models/explorer/createAppModel.ts
- Add encoding to key property whose value contains `run.hash` for explorers `processData` functions to avoid setting invalid CSS selectors on HTML tags. 
- Add encoding to selectors `run.hash` for metric lines.
=> [fix] Encode run hash before including in CSS selectors

CHANGELOG.md, aim/sdk/adapters/pytorch_lightning.py
Have a copy of removed staticmethod `_convert_params()` on `AimLogger` class itself
=> Fix compatibility with PL v1.6.0

CHANGELOG.md, aim/cli/up/utils.py, aim/storage/migrations/utils.py
Call alembic and uvicorn via python and not directly to be sure that executables are present.
=> [fix] `PATH` related issues 

CHANGELOG.md, aim/web/ui/src/components/ChartPanel/ChartGrid/ChartGrid.tsx, aim/web/ui/src/components/HighPlot/HighPlot.scss, aim/web/ui/src/components/HighPlot/HighPlot.tsx, aim/web/ui/src/components/LineChart/LineChart.scss, aim/web/ui/src/components/LineChart/LineChart.tsx, aim/web/ui/src/components/ScatterPlot/ScatterPlot.tsx, aim/web/ui/src/config/charts/index.ts, aim/web/ui/src/config/dash-arrays/dashArrays.ts, aim/web/ui/src/services/models/explorer/createAppModel.ts, aim/web/ui/src/utils/app/getAggregatedData.ts, aim/web/ui/src/utils/d3/drawHoverAttributes.ts, aim/web/ui/src/utils/d3/drawParallelLines.ts, aim/web/ui/src/utils/d3/processLineChartData.ts
- use `shape-rendering: optimizeSpeed` CSS property in HighPlot and LineChart components when the display is small with high `dpi` and  the lines count is more than `limit`
- replace meaningless `stroke-dasharray: '5 0'` to `stroke-dasharray: 'none'` which is default value to improve rendering
=> [feat] Improve chart lines rendering performance

aim/web/ui/src/pages/RunDetail/RunDetail.scss
Sass `toRem` method used in css `calc` method crashed the ui
=> [fix] ToRem method in Calc method crush the ui

aim/web/api/runs/views.py
As requested by frontend - adding `updated_at` into get-note and update-note api responses
=> [fix] add updated_at property to note api response

CHANGELOG.md, aim/web/ui/src/services/models/explorer/createAppModel.ts, aim/web/ui/src/utils/d3/drawArea.ts
- Replaced run hush with encoded key.
- Remove needless `pointer-events: all` from the area drawing method.
=> [fix] Params/Scatters explorers' row hiding functionality

CHANGELOG.md, aim/web/ui/src/components/LineChart/LineChart.tsx, aim/web/ui/src/components/ScatterPlot/ScatterPlot.tsx, aim/web/ui/src/services/models/explorer/createAppModel.ts, aim/web/ui/src/utils/d3/drawHoverAttributes.ts, aim/web/ui/src/utils/d3/processLineChartData.ts, aim/web/ui/src/utils/minMaxOfArray.ts, aim/web/ui/src/utils/smoothingData.ts
Fix: 
- margin calculation for negative and small values [0, 1]
- smoothing algorithm when empty `y` and `x` values
=> [fix] LineChart y-dimension margin calculation for negative values

README.md
Links in the Integrations section of README are broken. This PR fix them. 
Resolves #1705
=> Fix broken links in the Integrations section of README

CHANGELOG.md, aim/sdk/adapters/pytorch_lightning.py
switch from `LightningLoggerBase.close` (deprecated in PL v1.5) to `LightningLoggerBase.finalize`
Fixes issue #1742
=> [fix] AimLogger deprecation issue with PyTorch Lightning v1.5

CHANGELOG.md, aim/web/ui/src/components/CustomTable/Table.scss, aim/web/ui/src/components/CustomTable/Table.tsx, aim/web/ui/src/components/CustomTable/TableColumn.tsx, aim/web/ui/src/components/Table/Table.tsx, aim/web/ui/src/components/kit/Badge/Badge.scss, aim/web/ui/src/components/kit/Button/Button.tsx, aim/web/ui/src/components/kit/DataList/DataList.scss, aim/web/ui/src/components/kit/DataList/DataList.tsx, aim/web/ui/src/config/enums/tableEnums.ts, aim/web/ui/src/config/table/tableConfigs.ts, aim/web/ui/src/pages/ImagesExplore/components/ImagesExploreTableGrid/ImagesExploreTableGrid.tsx, aim/web/ui/src/pages/Metrics/components/MetricsTableGrid/MetricsTableGrid.tsx, aim/web/ui/src/pages/Metrics/components/Table/RowHeightPopover/RowHeightPopover.tsx, aim/web/ui/src/pages/Params/components/ParamsTableGrid/ParamsTableGrid.tsx, aim/web/ui/src/pages/Runs/components/RunsTableGrid/RunsTableGrid.tsx
Following changes provide the ability to control the content density in Explorer tables
- Change row height sizes
- Rename row height modes names
- Decrease font size for compact mode
- Decrease `Badge` height for `xSmall` size
=> [feat] Add ability to adjust the density of the visible content in tables

CHANGELOG.md, aim/web/ui/src/components/GroupingPopover/GroupingPopover.tsx
Preserve the search input value of the grouping dropdown
=> [fix] Preserve the search input value of the grouping dropdown

CHANGELOG.md, aim/web/ui/src/components/ChartPanel/PopoverContent/PopoverContent.tsx, aim/web/ui/src/services/models/explorer/createAppModel.ts, aim/web/ui/src/utils/formatByAlignment.ts, aim/web/ui/src/utils/formatValue.ts
Round floating-point numbers to a maximum of 8 digits.
Improve `format_number` function used in the `formatValue` function.
Use the `formatValue` function
- for aggregated data in the table
- for visualization tooltip content
=> [feat] Improve number formatting by setting precision

aim/web/ui/src/components/HighPlot/HighPlot.scss, aim/web/ui/src/components/LineChart/LineChart.scss, aim/web/ui/src/components/ScatterPlot/styles.scss, aim/web/ui/src/utils/d3/drawHoverAttributes.ts, aim/web/ui/src/utils/d3/drawParallelHoverAttributes.ts
Chart focused point outline is square instead of a circle on safari
- removed `outline` styles
- added a new circle under the focused point for creating shadows
=> [fix] Chart focused point shadow styles support on safari

aim/web/ui/src/pages/Bookmarks/Bookmarks.scss, aim/web/ui/src/pages/Bookmarks/components/BookmarkCard/BookmarkCard.scss
- Remove the right space of the `CodeBlock` in the `BookmarkCard`.
- Add space under the last child of the `BookmarkCard`.
=> [fix] Tune spacings on the Bookmark page

aim/web/ui/src/components/GroupingItem/GroupingItem.tsx, aim/web/ui/src/components/ProgressBar/ProgressBar.tsx
The progress bar doesn’t render the progress of the search request.
After memorizing the `ProgressBar` component variables, missing a variable in the dependency array.
=> [Fix] Fix rendering progress bar

aim/web/ui/src/pages/Bookmarks/components/BookmarkCard/BookmarkCard.tsx
Don't show tags if the list is empty
=> [fix] Prevent empty tags rendering in bookmarks page

CHANGELOG.md, aim/web/ui/src/App.tsx, aim/web/ui/src/components/AutocompleteInput/AutocompleteInput.tsx
- Load monaco editor from the node modules instead of CDN across the Aim Ui
=> [fix] Fix the loading logic of the `monaco editor` across the Aim Ui

CHANGELOG.md, aim/web/ui/src/components/ChartPanel/PopoverContent/PopoverContent.tsx, aim/web/ui/src/components/ProgressBar/ProgressBar.scss, aim/web/ui/src/components/ProgressBar/ProgressBar.tsx, aim/web/ui/src/components/kit/Text/Text.scss, aim/web/ui/src/components/kit/Text/Text.tsx
- Progress bar matched runs color style overrides from `main.css` chunk in the production build
- Add `success` styles on `Text` component
- Fix Something went wrong issue in the `PopoverContent` component
=> [fix] Fix the "matched runs" sentence color style overriding issue in progress bars

CHANGELOG.md, aim/sdk/adapters/pytorch.py
When tracking histograms of gradients, some tensors may not have gradients during specific training loops.
So check if grad is not None before converting to numpy.
This commit fixes #1925
=> [fix] Check None value for Pytorch model gradients histogram

CHANGELOG.md, aim/web/ui/src/components/AutocompleteInput/ AutocompleteInput.d.ts, aim/web/ui/src/components/AutocompleteInput/AutocompleteInput.tsx, aim/web/ui/src/pages/ImagesExplore/components/SelectForm/SelectForm.tsx, aim/web/ui/src/pages/Metrics/components/SelectForm/SelectForm.tsx, aim/web/ui/src/pages/Params/components/SelectForm/SelectForm.tsx, aim/web/ui/src/pages/Runs/components/SearchBar/SearchBar.tsx, aim/web/ui/src/pages/Scatters/components/SelectForm/SelectForm.tsx, aim/web/ui/src/services/models/explorer/createAppModel.ts, aim/web/ui/src/services/models/explorer/index.ts, aim/web/ui/src/services/models/imagesExplore/imagesExploreAppModel.ts, aim/web/ui/src/types/services/models/imagesExplore/imagesExploreAppModel.d.ts, aim/web/ui/src/utils/app/getQueryStringFromSelect.ts, aim/web/ui/src/utils/app/toggleSelectAdvancedMode.ts, aim/web/ui/src/utils/encoder/encoder.ts
- Update URL after getting a valid response from the back-end.
- Fix decoding issue related to `BS64_ENCODING_PADDING` padding.
=> [fix] Avoid saving crashed or terminated search requests as the last state on explorers

aim/web/ui/src/utils/d3/drawLines.ts
Prevent the active run indicator appearance out of the chart
=> [fix] Prevent the active run indicator appearance out of the chart

aim/web/ui/src/components/AttachedTagsList/AttachedTagsList.scss, aim/web/ui/src/components/ChartPanel/PopoverContent/PopoverContent.scss, aim/web/ui/src/components/CodeBlock/CodeBlock.scss, aim/web/ui/src/components/CustomTable/Table.scss, aim/web/ui/src/components/HeatMap/HeatMapStyle.scss, aim/web/ui/src/components/HighPlot/HighPlot.scss, aim/web/ui/src/components/IllustrationBlock/IllustrationBlock.scss, aim/web/ui/src/components/LineChart/LineChart.scss, aim/web/ui/src/components/NotificationContainer/NotificationContainer.scss, aim/web/ui/src/components/ScatterPlot/styles.scss, aim/web/ui/src/components/SideBar/Sidebar.scss, aim/web/ui/src/components/SliderWithInput/SliderWithInput.scss, aim/web/ui/src/components/Table/BaseTable.scss, aim/web/ui/src/components/kit/Badge/Badge.scss, aim/web/ui/src/components/kit/Slider/Slider.scss, aim/web/ui/src/components/kit/Text/Text.scss, aim/web/ui/src/pages/Bookmarks/components/BookmarkCard/BookmarkCard.scss, aim/web/ui/src/pages/ImagesExplore/components/SelectForm/SelectForm.scss, aim/web/ui/src/pages/Metrics/components/Table/ManageColumnsPopover/ManageColumnsPopover.scss, aim/web/ui/src/pages/Metrics/components/Table/ManageColumnsPopover/ManageColumnsPopover.tsx, aim/web/ui/src/pages/RunDetail/DistributionsVisualizer/DistributionsVisualizer.scss, aim/web/ui/src/pages/RunDetail/RunDetail.scss, aim/web/ui/src/pages/RunDetail/RunDetailNotesTab/RunDetailNotesTab.scss, aim/web/ui/src/pages/RunDetail/RunDetailSettingsTab/RunDetailSettingsTab.scss, aim/web/ui/src/pages/Runs/Runs.scss, aim/web/ui/src/pages/Tags/Tags.scss, aim/web/ui/src/styles/abstracts/_variables.scss, aim/web/ui/src/styles/base/_reset.scss, aim/web/ui/src/styles/components/_inputs.scss
- Use style variable for font-weight across Aim UI
- Fix input width in manage columns popover
- Set the cell font-size to 15px for the tables in the RunDetail page
=> [feat] Use style variable for font-weight across Aim UI

CHANGELOG.md, aim/web/ui/src/components/CustomTable/Table.scss, aim/web/ui/src/components/CustomTable/Table.tsx, aim/web/ui/src/pages/RunDetail/RunDetail.scss
- Break long metric names into multiple lines in Run Page
- Fix a minor issue with the selection pane shadow for the Explorer table
=> [fix] Break long metric names into multiple lines in Run Page

aim/web/ui/src/modules/BaseExplorer/components/Controls/BoxConfig.tsx, aim/web/ui/src/modules/BaseExplorer/components/Controls/index.tsx, aim/web/ui/src/modules/BaseExplorer/components/Grouping/GroupingItem/GroupingItem.tsx, aim/web/ui/src/modules/BaseExplorer/components/QueryForm/QueryForm.tsx, aim/web/ui/src/modules/BaseExplorer/components/Visualizer/index.tsx, aim/web/ui/src/modules/BaseExplorer/index.tsx, aim/web/ui/src/modules/BaseExplorer/types.ts, aim/web/ui/src/modules/BaseExplorerCore/core-store/controls.ts, aim/web/ui/src/modules/BaseExplorerCore/core-store/index.ts, aim/web/ui/src/modules/BaseExplorerCore/core-store/utils.ts, aim/web/ui/src/modules/BaseExplorerCore/helpers.ts, aim/web/ui/src/modules/BaseExplorerCore/types.ts, aim/web/ui/src/pages/BaseExplorer/index.tsx, aim/web/ui/src/types/services/models/explorer/createAppModel.d.ts
This PR 
**adds**
- controls key in engine config, to pass controls config as it was possible for groupings (including settings, state, component keys)
- controls property of ui components on explorer config, to pass controls area wrapper, as it was for grouping
- `isInitial` flag on every state slice coming from engine, it is  `true` if the state is deeply equal to its `initialState`, otherwise it is false, and this property changes its value automatically, e.g. calling update or reset method of the state slice will automatically change this property, to compare states used `cyrb53` hashing algorithm, by comparing two objects hashes
**Includes**
- rendering controls component and inside default Controls component added code to render components array passed through engine's controls …
=> [feat] Add controls management in ui core, enhance state management on engine

aim/web/ui/package-lock.json, aim/web/ui/package.json, aim/web/ui/src/modules/BaseExplorer/components/QueryForm/QueryForm.tsx, aim/web/ui/src/modules/BaseExplorerCore/core-store/index.ts, aim/web/ui/src/modules/BaseExplorerCore/pipeline/adapter/processor.ts, aim/web/ui/src/pages/BaseExplorer/index.tsx, aim/web/ui/src/services/api/base-explorer/runsApi/types.ts, aim/web/ui/src/types/core/AimObjects/CustomObject.d.ts, aim/web/ui/src/types/core/shared/index.d.ts, aim/web/ui/src/types/services/models/explorer/createAppModel.d.ts
This PR includes
- type enhancement for run search query parameters, added new annotations for ranges and density parameters
- new key on engine named `queryableData` and its selector, the value of this key collected from run search result as record and index ranges information
- a simple query example of using newly added parameters for run search request
- added `zustand` as a dependency to have it on base-explorer
=> [feat] Add collected ranges info into engine and run-search request params

CHANGELOG.md, aim/web/ui/src/components/CustomTable/Table.tsx, aim/web/ui/src/pages/Runs/components/RunsTableGrid/RunsTableGrid.tsx
Format metric keys for run table grid columns correctly
=> [fix] Correct metric column key in run table grid

CHANGELOG.md, aim/cli/manager/manager.py
This problems came after adding warnings in `FileSystemInspector`.
The problem is,  the manager of the aim server running on notebook extension listens to the `stderr` to detect aim server is living or not to show the ui, and warnings are corrupting `stderr`.
Added `--log-level=error` argument while running `aim up` command, and the aim cli will log only errors.
Warnings aren't mandatory for the notebook user, since they are not using terminal to run aim.
=> [fix] Fix issue on rendering aim ui on notebooks

.github/workflows/nightly-release.yml, CHANGELOG.md
Added a job before packaging workflow to run unit tests for nightly releases. 
This is added as an extra job not a step, to be able to re-run without triggering the `version-override` job.
=> [feat] Run unit-tests before nightly releases

CHANGELOG.md, aim/cli/watcher_cli.py, aim/ext/notifier/__init__.py, aim/ext/notifier/base_notifier.py, aim/ext/notifier/config.py, aim/ext/notifier/config_default.json, aim/ext/notifier/config_empty.json, aim/ext/notifier/logging_notifier.py, aim/ext/notifier/notifier.py, aim/ext/notifier/notifier_builder.py, aim/ext/notifier/slack_notifier.py, aim/ext/notifier/utils.py, aim/ext/notifier/workplace_notifier.py, aim/sdk/checkins/__init__.py, aim/sdk/reporter/__init__.py, aim/sdk/run.py, aim/sdk/run_status_watcher.py, setup.py
This system is designed to let users to check if the run had any progress.
While it may seem an easy task, it's very difficult to have a reliable way to
check if everything is fine with the process; The main (rank0) process may be
killed having no chance of notifying about failure. Even if the main process is
alive, the other moving parts may be stuck (network sync with other nodes,
filesystem, dataloader) those are not necessarily part of the main execution
thread. It leaves no other choice other than defining:
> The run is considered to be failed if it had not reported any progress in the promised time.
Thus, we can mark progress (we call these `check-in`s) and the expected time of
the next check-in. We can report a check-in after each forwarding each batch and
promising the next …
=> [feat] Implement Run check-ins and watcher service

CHANGELOG.md, aim/web/ui/src/App.scss, aim/web/ui/src/components/AttachedTagsList/AttachedTagsList.scss, aim/web/ui/src/components/AttachedTagsList/AttachedTagsList.tsx, aim/web/ui/src/components/SelectTag/SelectTag.scss, aim/web/ui/src/modules/BaseExplorer/components/BoxFullViewPopover/BoxFullViewPopover.tsx, aim/web/ui/src/pages/RunDetail/RunOverviewTab/components/RunOverviewSidebar/RunOverviewSidebar.tsx, aim/web/ui/src/services/models/runs/runDetailAppModel.ts, aim/web/ui/src/types/components/AttachedTagsList/AttachedTagsList.d.ts
- Add the ability to edit tags from the Run Page overview sidebar
- Apply optimistic updates on tags edit functionality
- Tune styles for the edit button in <AttachedTagsList /> component
=> [feat] Add the ability to edit tags on the Run Page

aim/sdk/adapters/keras_tuner.py
Removed an unnecessary word in the message when keras-tuner is not installed
=> [fix] Tune error message when KerasTuner is not installed

.github/workflows/pull-request.yml, CHANGELOG.md, aim/sdk/run.py, aim/sdk/tracker.py, examples/pytorch_track.py, tests/sdk/test_run_track_type_checking.py
- Changed the value validation logic and `_track` implementation.
- Added unit-tests to cover dict tracking + negative cases with specifying `name` argument.
- Changed `examples/pytorch_track.py` to use the new interface.
=> [feat] Support dictionaries as argument of `Run.track`

CHANGELOG.md, aim/cli/convert/processors/mlflow.py
Changed the way of getting mlflow run id. Added the run_name and the description.
=> [feat] Tune mlflow converter run properties

CHANGELOG.md, aim/web/ui/src/components/ScatterPlot/styles.scss, aim/web/ui/src/components/kit/SelectDropdown/SelectDropdown.scss, aim/web/ui/src/components/kit/Slider/Slider.scss, aim/web/ui/src/modules/BaseExplorer/components/BoxWrapper/BoxWrapper.scss, aim/web/ui/src/utils/d3/drawScatterTrendline.ts
* add styles directly on the SVG path as attributes
Additional small style fixes
* fix the x-axis alignment popover overflowing issue
* fix the depth slider shifting issue
=> [fix] Fix regression line rendering issue on scatterplot exported image

CHANGELOG.md, aim/web/api/runs/utils.py, aim/web/ui/src/pages/RunDetail/RunLogsTab/LogRow.tsx, aim/web/ui/src/pages/RunDetail/RunLogsTab/RunLogsTab.d.ts, aim/web/ui/src/pages/RunDetail/RunLogsTab/RunLogsTab.tsx
- Prevent calling of the live update before the other request is in pending state
- Change the overscan count of the virtualized list from 1000 to 100
- Change per request logs count to 200
=> [fix] Fix the data live update handling in the Logs tab

aim/web/ui/src/modules/core/api/releaseNotesApi/index.ts, aim/web/ui/src/modules/core/api/releaseNotesApi/types.ts, aim/web/ui/src/services/api/endpoints.ts
Added release notes API using github's API to display on the `Dashboard Page`
=> [feat] Add release notes api with new network service

aim/web/ui/src/components/HeatMap/HeatMap.tsx
Fixed displaying run count issue in the HeatMap cell.
=> [fix] Fix displaying run count issue in the HeatMap cell

CHANGELOG.md, aim/mxnet.py, aim/sdk/adapters/mxnet.py, examples/mxnet_track.py
Added MXNet Gluon logging handler
=> [feat] Add MXNet integration

aim/web/ui/src/components/AttachedTagsList/AttachedTagsList.tsx
- Remove the `)` symbol from the attached tags popover
- Prevent unnecessary requesting the list of the tags
=> [fix] Prevent unnecessary requesting the list of the tags

aim/web/ui/src/components/StatisticsBar/StatisticsBar.d.ts, aim/web/ui/src/components/StatisticsBar/StatisticsBar.scss, aim/web/ui/src/components/StatisticsBar/StatisticsBar.tsx, aim/web/ui/src/components/StatisticsCard/StatisticsCard.d.ts, aim/web/ui/src/components/StatisticsCard/StatisticsCard.scss, aim/web/ui/src/components/StatisticsCard/StatisticsCard.tsx, aim/web/ui/src/pages/Dashboard/components/ProjectStatistics/ProjectStatistics.d.ts, aim/web/ui/src/pages/Dashboard/components/ProjectStatistics/ProjectStatistics.tsx, aim/web/ui/src/pages/Dashboard/components/ProjectStatistics/useProjectStatistics.tsx, aim/web/ui/src/styles/components/_tooltip.scss, aim/web/ui/src/types/core/AimObjects/CustomObject.d.ts, aim/web/ui/src/types/core/AimObjects/Run.d.ts, aim/web/ui/src/types/core/AimObjects/Sequence.d.ts
Add outlined state on cards:
- when hovering over on the self card 
- when hovering over on a statistics bar item
Divide statistics cards highlighting states into two states:
- filled:  when the card is also a link (to the corresponding explorer)
- default: when the card has no link to navigate (there is no explorer yet)
=> [feat] Add outlined state on project statistics cards

aim/web/ui/src/components/StatisticsCard/StatisticsCard.scss, aim/web/ui/src/components/StatisticsCard/StatisticsCard.tsx, aim/web/ui/src/services/models/explorer/createAppModel.ts, aim/web/ui/src/styles/abstracts/_variables.scss
Dashboard statistic cards have the ability to navigate to the corresponding explorer page.
As there are no `Audio`, `Text`, and `Distributions` explorers yet, we need to mark corresponding cards, to show explicitly, that they are not able to navigate to explorers.
=> [feat] Add soon badge on dashboard statistic cards

CHANGELOG.md, aim/web/ui/src/components/HighPlot/HighPlot.scss, aim/web/ui/src/components/LineChart/LineChart.scss, aim/web/ui/src/components/LineChart/LineChart.tsx, aim/web/ui/src/components/ScatterPlot/styles.scss, aim/web/ui/src/components/ScatterPlot/types.d.ts, aim/web/ui/src/types/utils/d3/drawHoverAttributes.d.ts, aim/web/ui/src/utils/d3/drawBrush.ts, aim/web/ui/src/utils/d3/drawHoverAttributes.ts, aim/web/ui/src/utils/d3/drawLines.ts, aim/web/ui/src/utils/d3/drawParallelHoverAttributes.ts, aim/web/ui/src/utils/d3/drawPoints.ts, aim/web/ui/src/utils/d3/index.ts
Active runs indicators overlap by hover attributes.
To fix the issue we need to add active runs indicators on hover attributes (on circles).
- add `inProgress` state on hover attributes
- add pulsating animation for `inProgress` circles
- tune pulsating dots animation styles
=> [fix] Fix in-progress runs indicators overlapping issue by active points

CHANGELOG.md, aim/web/ui/src/components/CustomTable/TableColumn.tsx, aim/web/ui/src/pages/Runs/RunsContainer.tsx
Before rendering `stroke-dasharray` badges in the table, we are processing (decreasing) the stroke styles, to have the ability to draw badges in a short area.
Fix:
- pass the 'none' values of the `stroke-dasharrays` on processing stroke styles
=> [fix] Fix solid stroke rendering issue

CHANGELOG.md, aim/web/ui/src/services/models/imagesExplore/imagesExploreAppModel.ts, aim/web/ui/src/utils/app/getQueryStringFromSelect.ts
when navigating to `/metrics` all the metrics are retrieved instead of asking to select metrics
=> [fix] Fix querying all data on empty query

CHANGELOG.md, aim/web/ui/src/services/models/runs/util.ts, aim/web/ui/src/utils/app/getGroupingSelectOptions.ts
Fix the group property name visibility in the images and audio tabs on the run page
=> [fix] Fix the group property name visibility in the images and audio tabs

CHANGELOG.md, aim/sdk/adapters/pytorch_lightning.py, setup.py
=> [fix] Use `packaging.version` to parse version strings

aim/web/ui/src/components/StatisticsCard/StatisticsCard.d.ts, aim/web/ui/src/components/StatisticsCard/StatisticsCard.scss, aim/web/ui/src/components/StatisticsCard/StatisticsCard.tsx, aim/web/ui/src/pages/Dashboard/components/ProjectStatistics/ProjectStatistics.d.ts, aim/web/ui/src/pages/Dashboard/components/ProjectStatistics/ProjectStatistics.tsx
- add a `new` badge to project statistics cards
- add a link to audio explorer
=> [feat] Revamp dashboard page project statistics cards

aim/ext/resource/tracker.py, examples/pytorch_lightning_track.py
Fix csi(cursor state) handling: do not remove color information as it is handled by UI side.
Remove from line only cursor up/down/right/left commands.
=> [fix] Leave color information in tracked terminal logs

CHANGELOG.md, aim/web/ui/src/services/models/explorer/createAppModel.ts
Fixes the condition for equality checks in runs, params and scatters explorers . As pointed by @roubkar the condition was broken for runs, params, and scatters explorers but worked for metrics. So we use the same condition checking as metrics in the remaining 3 places.
=> [fix] show table diff for when elements are container types

CHANGELOG.md, aim/storage/locking.py, aim/storage/rockscontainer.pyx, aim/web/ui/src/components/Illustration/Illustration.d.ts, aim/web/ui/src/components/Illustration/Illustration.scss, aim/web/ui/src/components/Illustration/Illustration.tsx, aim/web/ui/src/components/Illustration/config.tsx, aim/web/ui/src/components/Illustration/index.ts, aim/web/ui/src/components/IllustrationBlock/IllustrationBlock.scss, aim/web/ui/src/config/illustrationConfig/illustrationConfig.tsx, aim/web/ui/src/config/references/index.ts, aim/web/ui/src/modules/BaseExplorer/components/Explorer/Explorer.tsx, aim/web/ui/src/modules/BaseExplorer/components/ExplorerBar/ExplorerBar.tsx, aim/web/ui/src/modules/BaseExplorer/components/Visualizations/Visualizations.tsx, aim/web/ui/src/modules/BaseExplorer/components/VisualizerPanel/VisualizerPanel.d.ts, aim/web/ui/src/modules/BaseExplorer/components/VisualizerPanel/VisualizerPanel.tsx, aim/web/ui/src/modules/BaseExplorer/getDefaultHydration.tsx, aim/web/ui/src/modules/BaseExplorer/index.tsx, aim/web/ui/src/modules/BaseExplorer/types.ts, aim/web/ui/src/modules/BaseExplorer/utils/getBaseExplorerStaticContent.tsx, aim/web/ui/src/modules/core/engine/pipeline/state.ts, aim/web/ui/src/modules/core/engine/types.ts, aim/web/ui/src/pages/AudiosExplorer/config.ts, aim/web/ui/src/pages/AudiosExplorer/getStaticContent.tsx, aim/web/ui/src/pages/AudiosExplorer/index.tsx, aim/web/ui/src/pages/FiguresExplorer/getStaticContent.tsx, aim/web/ui/src/pages/FiguresExplorer/index.tsx
- create a dynamic `Illustration` component
- create a generic `getStaticContent` function for Base explorers, which will get the static content type and will return the corresponding empty-illustration or predefined static content
- create `getStaticContent` function for Base Explorers separately for Audios and Figures and set the function in the corresponding explorer configuration
=> [fix] Fix showing incorrect empty-illustration message in Audios explorer

aim/web/ui/src/modules/BaseExplorer/getDefaultHydration.tsx, aim/web/ui/src/pages/FiguresExplorer/config.ts, aim/web/ui/src/pages/FiguresExplorer/index.tsx
Figures explorer grouping fields and caption control fields are hardcoded in Base explorer default configuration.
- removed hardcoded fields from the Base explorer default configuration
- add a separate config file for Figures explorer default configuration
=> [feat] Separate Base explorer default config from Figures explorer config

CHANGELOG.md, aim/sdk/reporter/__init__.py
When setting log level to INFO, RunStatusReporter floods logs with tons of messages. Setting the log level for majority of logger calls to DEBUG as the real purpose of them is debugging.
=> [fix] Lower debug messages log level in `reporter/__init__.py`

aim/web/ui/src/modules/core/engine/custom-states/index.ts, aim/web/ui/src/modules/core/engine/explorer-engine/index.ts
**New functionalities**
- added an initializer on `custom-states`. The initializer is responsible to register `browserHistory` listener by the `key`. The `key` is generated using the prefix `cs-` and name of the state. The initializer returns a function by calling it you will be able to unregister listeners.
- Enhanced the `update` and `reset` methods of state slices to update the url if `persist` key is `url`.
**How to use with BaseExplorer renderer**
1. Configure `persist` key with your custom state
```js
...rendererConfig,
customStates: {
test: {
initialState: {
val: true
}
persist: 'url'
}  
}
```
2. Call `update` method of the state
```js
engine.test.update({ val: false });
```
After calling this function the engine updates the url by encoding the state object using base64. The looks …
=> [feat] Add custom-state persistence functionality using URL on BaseExplorer

docs/source/using/search.md
I thought the `object[item, item]` syntax was a typo, but I think this change makes it more clear (if I understand it correctly).
=> Added additional example to clarify performance diff

aim/sdk/run.py
I found a minor typo-ish part on the [`run` section](https://aimstack.readthedocs.io/en/latest/refs/sdk.html#aim.sdk.run.Run) as follows.
=> [doc] Add missing `

CHANGELOG.md, aim/ext/exception_resistant.py, aim/sdk/run.py, aim/sdk/training_flow.py, aim/utils/__init__.py, pyproject.toml, setup.py
Introduce the safe mode into tracking with Aim.
- In order to mark the function as "safe-mode-enabled", decorate it with  `@noexcept`
- In order to enable/disable safe mode:
```python
from aim.utils import enable_safe_mode
enable_safe_mode()
...
```
_By default, in safe mode the raised exception and the function name will be logged with WARNING log level._
- In order to customize the exception handling need to register the callback on `TrainingFlow` instance
```python
class ExceptionHanlderCallback:
@on.exception_raised
def handle_exception(self, exception, function, **kwargs):
flow.register(ExceptionHanlderCallback())
```
and call
```python
flow.handle_exceptions()
```
=> [feat] Add exception-free mode to Aim

CHANGELOG.md, aim/web/ui/src/config/table/tableConfigs.ts, aim/web/ui/src/pages/Metrics/components/Table/CompareSelectedRunsPopover/CompareSelectedRunsPopover.d.ts, aim/web/ui/src/pages/Metrics/components/Table/CompareSelectedRunsPopover/CompareSelectedRunsPopover.tsx, aim/web/ui/src/pages/RunDetail/RunDetail.scss, aim/web/ui/src/pages/RunDetail/RunDetail.tsx
- Added compare popover to the run page header
- Added `buttonText` property to compare popover
- Added missing explorer names to the compare selected runs config
=> [feat] Add quick navigation to explorers from the run page

CHANGELOG.md, aim/sdk/base_run.py, aim/sdk/repo_utils.py, aim/sdk/run.py
#2520 @tmynn @alberttorosyan could you please take a look at this
=> [feat] Add support for Path type to the repo attribute of the Run class

aim/web/ui/src/modules/BaseExplorer/components/Controls/ConfigureAxes/Popover/Alignment.tsx, aim/web/ui/src/modules/core/cache/inlineCache.ts, aim/web/ui/src/modules/core/engine/pipeline/index.ts, aim/web/ui/src/modules/core/pipeline/custom/index.ts, aim/web/ui/src/modules/core/pipeline/index.ts
- Fixed an issue with the caching of custom metric alignment.
Reproduction steps:
1. Attempt to align the x-axis using a custom metric that is not `alignable` with the current y-axis values. This will cause the x-axis alignment value to be changed to the default "Step" value.
2. Attempt to align the x-axis using the same `non-alignable` value.
3. The issue is that it sets the x-axis value to that custom metric value, which is incorrect.
Expected behavior:
- When the alignment is incorrect, the x-axis alignment value should be set back to the default "Step" value.
Solution:
- Clear the caching when attempting to align the x-axis using a custom metric that is `non-alignable` with the current y values.
=> [fix] Fix issue with custom metric alignment caching

CHANGELOG.md, aim/web/ui/src/pages/Metrics/Metrics.tsx, aim/web/ui/src/pages/Params/Params.tsx, aim/web/ui/src/pages/Scatters/Scatters.tsx
When opening Metrics, Params, or Scatters Explorers with empty chart data the UI crashes.
- Fixed the issue
=> [fix] Fix the UI crashing issue when opening the Metrics, Params, or Scatters Explorers

aim/web/ui/src/components/kit_v2/FormGroup/FormGroup.tsx, aim/web/ui/src/components/kit_v2/Link/Link.d.ts, aim/web/ui/src/components/kit_v2/Link/Link.style.ts, aim/web/ui/src/components/kit_v2/Link/Link.tsx, aim/web/ui/src/components/kit_v2/Select/Select.tsx, aim/web/ui/src/components/kit_v2/Text/Text.d.ts, aim/web/ui/src/components/kit_v2/Text/Text.style.ts, aim/web/ui/src/components/kit_v2/Text/Text.tsx, aim/web/ui/src/components/kit_v2/Tooltip/Tooltip.tsx, aim/web/ui/src/config/stitches/foundations/layout.ts, aim/web/ui/src/pages/Boards/Boards.style.ts, aim/web/ui/src/pages/Boards/components/BoardCard/BoardCard.tsx, aim/web/ui/src/pages/Explorers/Bookmarks/components/BookmarkCard/BookmarkCard.tsx, aim/web/ui/src/pages/Explorers/Explorers.style.ts, aim/web/ui/src/pages/Explorers/components/ExplorerCard/ExplorerCard.style.ts, aim/web/ui/src/pages/Explorers/components/ExplorerCard/ExplorerCard.tsx, aim/web/ui/src/pages/Reports/ReportCard/ReportCard.tsx, aim/web/ui/src/pages/Reports/Reports.style.ts, aim/web/ui/src/routes/routes.tsx, aim/web/ui/src/stories/FormGroup.stories.tsx, aim/web/ui/src/stories/Link.stories.tsx
- Match card colors with dashboard theme.
- Set 24px spacing between explorer cards.
- Underline card titles on hover.
- Standardize title font size to 18px across all pages.
- Implement title truncation with ellipsis.
=> [fix] Resolve style inconsistencies in Explorers, Boards, and Reports pages

aim/web/api/runs/utils.py
Send log records count instead of last item index
=> [fix] Correct log records count calculation

aim/web/ui/src/components/AutocompleteInput/AutocompleteInput.tsx
Windows browsers send `\r\n` instead of just `\n` when `Enter` is pressed in the search box. This PR changes the way we detect this keypress so that searching can be triggered in the same way on Windows as on other platforms.
=> Fix searching on <Enter> on Windows

src/aim/web/ui/public/aim_ui_core.py, src/aim/web/ui/src/components/kit_v2/Link/Link.tsx, src/aim/web/ui/src/pages/Board/components/VisualizationElements/LinkVizElement.tsx, src/aim/web/ui/src/pages/Board/components/VisualizationElements/index.ts
Add python interface for Link component which accepts 2 arguments:
- `text`: link content
- `to`: URL to navigate to
=> [feat] Add python interface for Link component

src/aimcore/web/ui/public/aim_ui_core.py, src/aimcore/web/ui/src/pages/App/App.d.ts, src/aimcore/web/ui/src/pages/App/App.tsx, src/aimcore/web/ui/src/pages/App/components/AppPage.tsx, src/aimcore/web/ui/src/pages/App/components/AppSidebar.tsx, src/aimcore/web/ui/src/pages/App/components/AppWrapper.tsx, src/aimcore/web/ui/src/pages/Board/Board.tsx, src/aimcore/web/ui/src/pages/Board/search.ts, src/aimcore/web/ui/src/services/pyodide/pyodide.ts
Added same query repeating logic with time delay (5s) after the initial (prev) query is resolved.
This PR includes also the following changes:
- File restructuring in `App` directory
- Cache management for queried data:
- Cleaning cache on board unmounting (page leave, or embedded board removal)
- Cleaning cache on live-update query resolved
=> [feat] Add data live-update functionality to Board

src/aimcore/web/ui/public/aim_ui_core.py, src/aimcore/web/ui/src/pages/Board/Board.tsx
Catch `WAIT_FOR_QUERY_RESULT` error and raise an exception to stop the execution to avoid wrong usage of fallback data
=> [feat] Block pyodide execution while fetching logs

src/aimcore/web/ui/src/components/kit/DictVisualizer/DictVisualizer.tsx
During re-render when JSON object reference is being changed the collapsed keys are not being taken into account.
Added `props.src` as a dependency for `useEffect` for dict's rows collecting.
=> [fix] Resolve DictVisualizer collapsed keys reset issue

pkgs/aimstack/asp/boards/run.py, pkgs/aimstack/asp/boards/runs.py
Performance improvements for utility dict flattening: 
1. f-strings are faster even for three items.
2. Using one dict to avoid allocation of intermediate dicts.
*Bonus point (not included)*: changing `MutableMapping` to `dict` in type checking will make it twice as fast.
=> [refactor] Improve performance of dict flattening for board runs

src/aimcore/web/ui/src/services/NetworkService/index.ts
Added `encodeURIcomponent` call for query params before providing to `fetch` method.
=> [fix] Encode URI query params to escape special chars

src/aimcore/web/ui/public/aim_ui_core.py
When passing `None` to `ui.json` a `Something went wrong` error is being thrown.
Use fallback monospace text rendering to prevent the board page from crashing.
=> [fix] Add fallback json rendering for None value

setup.py, src/python/aim/_core/storage/rockscontainer.pyx
Opening as a draft, as it should be merged after https://github.com/aimhubio/aimrocks/pull/29
=> [feat] Use open-as-secondary feature of rocksdb in read_only mode

pkgs/aimstack/asp/boards/run.py, src/aimcore/web/api/queries/views.py, src/aimcore/web/ui/public/aim_ui_core.py, src/aimcore/web/ui/src/modules/core/api/dataFetchApi/index.ts, src/aimcore/web/ui/src/pages/Board/Board.tsx, src/aimcore/web/ui/src/pages/Board/serverAPI/find.ts, src/aimcore/web/ui/src/services/api/endpoints.ts, src/aimcore/web/ui/src/services/pyodide/pyodide.ts, src/python/aim/_sdk/container.py, src/python/aim/_sdk/sequence.py
=> [feat] Add `find()` method to Container and Sequence types

src/aimcore/web/ui/public/aim_ui_core.py, src/aimcore/web/ui/src/components/kit_v2/Table/Table.tsx, src/aimcore/web/ui/src/pages/Board/components/VisualizationElements/TableVizElement.tsx
- Added `selected_rows_indices` and `focused_row_index` properties and state fields on the Table component in python SDK
- Reused `selectedIndices` and `focusedRowIndex` component props in JS
This will be used in state-URL sync.
=> [feat] Add ability to set initial state for Table

pkgs/aimstack/asp/boards/audios.py, pkgs/aimstack/asp/boards/figures.py, pkgs/aimstack/asp/boards/images.py, pkgs/aimstack/asp/boards/metrics.py, pkgs/aimstack/asp/boards/runs.py, pkgs/aimstack/asp/boards/texts.py, src/aimcore/web/ui/public/aim_ui_core.py, src/aimcore/web/ui/src/services/pyodide/pyodide.ts
- Signals are being used to invalidate query results cache on specific state updates
- By binding queries and components with the same signal you can control when to invalidate query results cache
- You can use signals as primitive strings or as Signal class instances
- With Signal class, you can also specify properties that should be present in state update to invalidate query results cache
=> [feat] Enable resending requests ignoring cache

src/aimcore/web/ui/src/pages/Board/Board.style.ts, src/aimcore/web/ui/src/pages/Board/Board.tsx, src/aimcore/web/ui/src/pages/Board/components/LoadingBar.tsx, src/aimcore/web/ui/src/pages/Board/serverAPI/find.ts, src/aimcore/web/ui/src/pages/Board/serverAPI/runAction.ts, src/aimcore/web/ui/src/pages/Board/serverAPI/search.ts
Use `pyodideEngine` events to dispatch the start and the end of API requests.
The loading bar component keeps track of progress for all pending requests.
It displays the minimum of all the current requests' progress values.
=> [feat] Add loading bar for API requests in boards

src/aimcore/web/ui/src/pages/App/components/AppWrapper.tsx, src/aimcore/web/ui/src/pages/Board/Board.tsx, src/aimcore/web/ui/src/pages/Board/components/VisualizationElements/BoardLinkVizElement.tsx
- Rename `Edit` to `Playground` in boards
- Keep board state in URL while switching to the playground
- Stay in the playground while navigating through board links
=> [fix] Keep state in URL for edit mode

src/aimcore/web/ui/src/pages/Board/Board.tsx, src/aimcore/web/ui/src/pages/Report/Report.tsx
Added `stateStr` and `externalPackage` props to the `Board` component in the `Report` page to prevent the app from crashing while rendering an embedded board.
=> [fix] Add new props to Board component in Report

pkgs/aimstack/base/types/run.py
This is a relatively quick fix on what seems to be a typo!
in `aimstack/base/types/run.py` the context is defined as `type` of `None` resulting in the following error, when context is not provided explicitly.
```shell
[...]
File "<env_path>/lib/python3.10/site-packages/aimstack/base/types/run.py", line 130, in track
sequence.track(value, step=step, **axis)
File "<env_path>/lib/python3.10/site-packages/aim/_sdk/sequence.py", line 240, in track
self._meta_tree[KeyNames.CONTEXTS, self._ctx_idx] = self._context.to_dict()
File "src/python/aim/_core/storage/treeview.py", line 82, in aim._core.storage.treeview.TreeView.__setitem__
File "src/python/aim/_core/storage/containertreeview.py", line 102, in aim._core.storage.containertreeview.ContainerTreeView.set
File …
```
=> [fix] Correct default value for `context` in run.py track method

CHANGELOG.md, src/aimcore/cli/migrate/utils.py
When the value is list/tuple of floats, and it contains only one element, it should be possible to track as a Metric or SystemMetric. Added check for this case.
=> [fix] Check values of type list/tuple when migrating Metric types

CHANGELOG.md, aim/sdk/adapters/pytorch_lightning.py
When running testing on a Run, this line failed with error similar to #2999 . It was quite hard to debug, but it seems this is the culprit. It appears that Run was already locked and it failed with traceback when trying to run pytorch lightning training+testing run
=> [fix] Force reacquire lock in torch lightning

CHANGELOG.md, aim/web/api/views.py
In certain conda environments, the files in the static files root directory can be symlinked from a different place. The fixed implementation only resolves relative .. segments in the request path without resolving any symlinks. This way, it still prevents reading arbitrary files through the web server while allowing the reading of symlinked files.
=> [fix] Serve files linked into the static files directory

CHANGELOG.md, aim/sdk/adapters/hugging_face.py
Current implementation of HF callback in Aim initializes the `Run` object at training begin time. This means if the users want to track any additional metrics they need to do so before training finishes while using `HFTrainer` object. 
This small change which initializes the `Run` object on `init_end` makes the run object available to user of this callback via `callback.experiment` and allows them to track any extra metrics or parameters with the same run other than the standard metrics output by HF.
=> [feat] Allow HF callback to initialize Aim run at init end

aim/sdk/adapters/pytorch_lightning.py
Before, the run name would only be set when a run hash has been specified by the user, which is only the case in unusual circumstances, e.g. when a previous model training is resumed at a later time. In effect, run names were never set in my case.
Best,
Marten
=> [fix] Always set the run name when initializing a run in lightning

CHANGELOG.md, aim/sdk/repo.py, aim/storage/structured/entities.py, aim/storage/structured/sql_engine/entities.py, aim/storage/structured/sql_engine/factory.py, aim/web/api/experiments/views.py, aim/web/ui/src/config/analytics/analyticsKeysMap.ts, aim/web/ui/src/modules/core/api/experimentsApi/index.ts, aim/web/ui/src/pages/Experiment/Experiment.tsx, aim/web/ui/src/pages/Experiment/ExperimentStore.ts, aim/web/ui/src/pages/Experiment/components/ExperimentSettingsTab/ExperimentSettingsTab.d.ts, aim/web/ui/src/pages/Experiment/components/ExperimentSettingsTab/ExperimentSettingsTab.scss, aim/web/ui/src/pages/Experiment/components/ExperimentSettingsTab/ExperimentSettingsTab.tsx, aim/web/ui/src/pages/Experiment/useExperimentState.tsx, aim/web/ui/src/services/api/endpoints.ts, aim/web/ui/src/services/api/experiments/experimentsService.ts, examples/optuna_track.py
This pull request introduces the ability to delete entire experiments directly from the user interface.
Users can now delete entire experiments without having to manually select and delete individual runs.
This resolves the issue of having empty experiments after all runs are deleted, providing a more streamlined workflow.
Delete all runs of an experiment:
The delete functionality for experiments is currently available only on the experiment settings tab, making it consistent with the existing run detail  deletion process.
How we should delete experiments from the dashboard needs further discussion (due to the space constraints)
Issues Resolved:
Closes #2528 , #2803
=> [feat] Add feature to delete full experiments

CHANGELOG.md, aim/cli/utils.py, aim/ext/transport/client.py
Set `max_size` in `connect` to `None` (unlimited) and `1073741824` (1024*1024*1024) for `unicorn`
This addresses issue #3154 of large validation images getting 1009 (message too big) errors when trying to upload.
Values chosen are arbitrary and very high.
=> [fix] Increase websockets max_size for large images sent to server

CHANGELOG.md, aim/cli/manager/manager.py
Currently the jupyter-lab extension is broken due to the `--force-init` flag that is added to the `aim up` call. See https://github.com/aimhubio/aim/issues/3123
This flag was removed from the cli in https://github.com/aimhubio/aim/commit/3373cbbea1f9d213c3113fdaea2d2b16951dfe2b
I've tested this with a local install of 3.20.1.
=> [fix] Remove no longer available --force-init flag from cli manager

CHANGELOG.md, aim/cli/init/commands.py
PR for #3177 
Adds a skip option for init in case the repo already exists.
Note: It does not seem like click has a standard way of dealing with conflicting options, so I decided to throw an error if "yes" and "skip-if-exists" are both specified.
=> [feat] Add skip option in init commands

CHANGELOG.md, aim/ext/transport/client.py
Currently, when making HTTP requests using `requests.get`, there is no timeout specified. This can lead to long waiting times (up to 2 minutes) during the `protocol_probe` process when connecting to incorrect or unresponsive addresses. This delay is due to the default TCP SYN-SENT timeout.
Add a default timeout parameter to all `requests.get` calls to allow for fast failure and better error handling in network operations.
=> [fix] Prevents long waiting times when connecting to incorrect or unresponsive addresses

examples/pytorch_track.py, examples/pytorch_track_images.py
Changed inference context to `torch.inference_mode()` in test stage. 
Setting `device` automatically with `torch.cuda.is_availble`.
=> [fix] torch.inference_mode inplace of torch.no_grad

CONTRIBUTING.md, docs/requirements.txt, docs/source/refs/cli.md
- clarifies the purpose of the `--dev` flag for `aim up`
- fixes formatting issue—replaces `|` with `,`
- updates doc build instructions 
fixes #3200 .
=> [fix] Update `up` docs, build instructions

CHANGELOG.md, aim/storage/union.pyx
`aimrocks.errors.RocksIOError` instead of `aimrocks.errorsRocksIOError`
=> [fix] Typo in exception name in `storage/union.pyx`

tests/requirements.txt
Restrict `deeplake` upper version, because they had major changes in the new release and there's no documentation available yet for the new major version: 4.0.0
=> [fix] Resolve issues with unit test failures

aim/cli/runs/commands.py, aim/sdk/reporter/file_manager.py, aim/sdk/run.py, aim/sdk/run_status_watcher.py, aim/sdk/sequences/sequence_type_map.py, aim/sdk/tracker.py
In order to skip sequences while iterating over them in query context, new mapping has been added. This will improve performance of metric queries in cases when there are many other types of sequences tracked/
=> [feat] Store Run sequence metadata by separate types

CHANGELOG.md, aim/sdk/reporter/__init__.py
Iterating the dictionary self.timed_tasks sometimes raises the following exception:
> RuntimeError: dictionary changed size during iteration
This PR resolves https://github.com/aimhubio/aim/issues/3181
https://github.com/GuHongyang actually included the fix to the issue they opened ( #3181 )
=> [fix] Copy the keys of RunStatusReporter.timed_tasks before iterating them

aim/sdk/run.py
#3266 
let run.artifact_uri return None if not set. 
Also raises useful warning and ValueError if uri improperly configured
=> [feat] Return `None` for `run.artifact_uri` if not set

aim/pytorch_lightning.py, aim/sdk/adapters/pytorch_lightning.py, docs/source/quick_start/integrations.md, examples/pytorch_lightning_track.py
addresses #3259 "PytorchLightning AimLogger custom contexts"
There are two commits. First commit e0dc418 simply adds an AimLoggerWithContext subclass that uses the context configuring mechanism described in the associated Issue. Args `train_metric_prefix`, `val_metric_prefix`, `test_metric_prefix` ("SUBSET_metric_prefixes")  are removed.
The Second commit 15c9da5 is more extensive. It DOESN'T come with AimLoggerWithContext, instead refactoring the regular Lightning AimLogger to use the new context configuring mechanism. Care was taken make sure the changes are totally backwards compatible. SUBSET_metric_prefixes are present and functional but will raise a deprecation warning if input value is not default. 
I also went ahead and updated the documentation for the new schema. 
If the latter …
=> [feat] PytorchLightning AimLogger custom contexts

aim/storage/artifacts/s3_storage.py
A fix for a minor type-hinting error for the **kwargs of `S3ArtifactStorage_clientconfig(...)`
Addresses #3275
=> [fix] Bad typing for S3ArtifactStorage_clientconfig args

CHANGELOG.md, aim/ext/transport/message_utils.py
The chunks returned by `response.iter_content(chunk_size=None)` can contain multiple messages. However, message parsing currently assumes that these chunks represent individual messages, causing an assertion failure if this is not the case. Fix this by allowing multiple messages to be parsed from a single chunk.
Fixes #3297.
I noticed that `unpack_args()` already supports parsing multiple messages, so I just replaced `unpack_helper()` with that.
This all assumes that chunks contain complete messages and not message parts. I'm not sure if there is an actual guarantee for that, so message parsing may need to be robustified more. But the changes in this PR seem to work for me.
=> [fix] Message stream parsing (#3297)

aim/distributed_hugging_face.py, aim/sdk/adapters/distributed_hugging_face.py
There is a singular aim.Run which the main worker initializes and manages. All auxiliary workers (local_rank 0 workers hosted on other nodes) collect their metrics and forward them to the main worker. The main worker records the metrics in AIM.
Resolves #3148
=> [feat] Add AimCallback for distributed runs using the hugging face API

aim/cli/manager/manager.py
The PR #2696 added more robust mechanism of initializing aim server, checking the health, and only then enabling the web ui. However, there's no endpoint /projects/status/ now as part of api, so currently aim web ui integration for jupyter always fails.
This PR:
- Relies on status code of /projects endpoint instead
- Removes unnecessary delay in case of failure (for loop always calling sleep even if no tries left)
- Implements delayed retries with exponential backoff, and lets it to wait longer, as some google colab machines are slow and take at least 10-15 seconds to start the aim server.
Possibly addresses #2672 and #3123
Tested on both local jupyter notebooks, and google colab
=> [fix] Aim web ui integration in jupyter/colab
